Repository woowacourse-teams/2023-festa-go, pull requests merged in 2023-07, with the labels that each got.

#14 [AN/USER] FEAT: 페스타고 유저 어플 프로젝트 초기 세팅한다. (#13)
  android/festago/.gitignore
  android/festago/.idea/.gitignore
  android/festago/.idea/compiler.xml
  android/festago/.idea/gradle.xml
  android/festago/.idea/kotlinc.xml
  android/festago/.idea/misc.xml
  android/festago/.idea/vcs.xml
  android/festago/app/.gitignore
  android/festago/app/build.gradle.kts
  android/festago/app/proguard-rules.pro
  android/festago/app/src/androidTest/java/com/festago/festago/ExampleInstrumentedTest.kt
  android/festago/app/src/main/AndroidManifest.xml
  android/festago/app/src/main/java/com/festago/festago/MainActivity.kt
  android/festago/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  android/festago/app/src/main/res/drawable/ic_launcher_background.xml
  android/festago/app/src/main/res/layout/activity_main.xml
  android/festago/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/festago/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/festago/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  android/festago/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  android/festago/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  android/festago/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  android/festago/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  android/festago/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  android/festago/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  android/festago/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  android/festago/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  android/festago/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  android/festago/app/src/main/res/values-night/themes.xml
  android/festago/app/src/main/res/values/colors.xml
  android/festago/app/src/main/res/values/strings.xml
  android/festago/app/src/main/res/values/themes.xml
  android/festago/app/src/main/res/xml/backup_rules.xml
  android/festago/app/src/main/res/xml/data_extraction_rules.xml
  android/festago/app/src/test/java/com/festago/festago/ExampleUnitTest.kt
  android/festago/build.gradle.kts
  android/festago/gradle.properties
  android/festago/gradle/wrapper/gradle-wrapper.jar
  android/festago/gradle/wrapper/gradle-wrapper.properties
  android/festago/gradlew
  android/festago/gradlew.bat
  android/festago/settings.gradle.kts
Labels: AN, USER

#20 [ALL] FEAT: dev 브랜치로 PR 요청, 병합 시 슬랙에 알림을 보낸다. (#17)
  .github/workflows/closed-pr-notification.yml
  .github/workflows/opened-pr-notification.yml
Labels: ALL

#29 [AN/USER] FEAT: 페스타고 유저 어플 Material 리소스 적용(#24)
  android/festago/app/src/main/res/values-night/themes.xml
  android/festago/app/src/main/res/values/colors.xml
  android/festago/app/src/main/res/values/dimens.xml
  android/festago/app/src/main/res/values/themes.xml
Labels: AN, USER

#30 [BE] FEAT: 개발환경을 구축한다. (#28)
  .gitignore
  backend/.gitignore
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/com/festago/FestaGoApplication.java
  backend/src/main/resources/application.properties
  backend/src/test/java/com/festago/FestaGoApplicationTests.java
Labels: BE

#32 [ALL] FEAT: 이슈 및 PR 템플릿을 수정한다 (#31)
  .github/ISSUE_TEMPLATE/all-issue-template.md
  .github/ISSUE_TEMPLATE/an-issue-template.md
  .github/ISSUE_TEMPLATE/be-issue-template.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/default-issue-template.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ALL

#35 [BE] CHORE: 스프링 부트 설정 변경 (#33)
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application.properties
  backend/src/main/resources/application.yml
Labels: BE

#36 [BE] style: Google Style Guide Format 적용 (#34)
  backend/build.gradle
  backend/intellij-java-festago-style.xml
  backend/src/main/java/com/festago/FestaGoApplication.java
  backend/src/test/java/com/festago/FestaGoApplicationTests.java
Labels: BE

#38 [ALL] docs: PR 제목의 타입을 소문자로 변경 (#37)
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ALL

#39 [AN/USER] feat: 티켓의 QR 코드를 생성한다.
  android/festago/app/build.gradle.kts
  android/festago/app/src/main/AndroidManifest.xml
  android/festago/app/src/main/java/com/festago/festago/data/repository/TicketDefaultRepository.kt
  android/festago/app/src/main/java/com/festago/festago/domain/model/TicketCode.kt
  android/festago/app/src/main/java/com/festago/festago/domain/model/timer/Timer.kt
  android/festago/app/src/main/java/com/festago/festago/domain/model/timer/TimerListener.kt
  android/festago/app/src/main/java/com/festago/festago/domain/repository/TicketRepository.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/mapper/TicketCodeMapper.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/model/TicketCodeUiModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketentry/QrImageBindingAdapter.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryViewModel.kt
  android/festago/app/src/main/res/drawable/img_festago_qr.png
  android/festago/app/src/main/res/layout/activity_ticket_entry.xml
  android/festago/app/src/test/java/com/festago/festago/ExampleUnitTest.kt
  android/festago/app/src/test/java/com/festago/festago/presentation/ticketentry/TicketEntryViewModelTest.kt
  android/festago/docs/README.md
Labels: AN, USER

#43 [BE] feat: 티켓 제시용 QR 생성 기능 구현 (#26)
  backend/build.gradle
  backend/src/main/java/com/festago/application/EntryService.java
  backend/src/main/java/com/festago/config/EntryProviderConfig.java
  backend/src/main/java/com/festago/domain/EntryCode.java
  backend/src/main/java/com/festago/domain/EntryCodeProvider.java
  backend/src/main/java/com/festago/domain/EntryState.java
  backend/src/main/java/com/festago/domain/Member.java
  backend/src/main/java/com/festago/domain/MemberTicket.java
  backend/src/main/java/com/festago/domain/MemberTicketRepository.java
  backend/src/main/java/com/festago/domain/Ticket.java
  backend/src/main/java/com/festago/dto/EntryCodeResponse.java
  backend/src/main/java/com/festago/infrastructure/JwtEntryCodeProvider.java
  backend/src/main/java/com/festago/presentation/TicketController.java
  backend/src/main/resources/application-local.yml
  backend/src/test/java/com/festago/application/EntryServiceTest.java
  backend/src/test/java/com/festago/domain/MemberTicketTest.java
  backend/src/test/java/com/festago/domain/TicketTest.java
  backend/src/test/java/com/festago/infrastructure/JwtEntryCodeProviderTest.java
  backend/src/test/java/com/festago/presentation/TicketControllerTest.java
Labels: BE, USER

#46 [AN/STAFF] feat: 페스타고 스태프 어플 프로젝트 초기 세팅(#15)
  android/festago-staff/.gitignore
  android/festago-staff/app/.gitignore
  android/festago-staff/app/build.gradle.kts
  android/festago-staff/app/proguard-rules.pro
  android/festago-staff/app/src/main/AndroidManifest.xml
  android/festago-staff/app/src/main/java/com/festago/festagostaff/presentation/ui/main/MainActivity.kt
  android/festago-staff/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  android/festago-staff/app/src/main/res/drawable/ic_launcher_background.xml
  android/festago-staff/app/src/main/res/drawable/img_festago_staff_logo.xml
  android/festago-staff/app/src/main/res/layout/activity_main.xml
  android/festago-staff/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/festago-staff/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/festago-staff/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  android/festago-staff/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  android/festago-staff/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  android/festago-staff/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  android/festago-staff/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  android/festago-staff/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  android/festago-staff/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  android/festago-staff/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  android/festago-staff/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  android/festago-staff/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  android/festago-staff/app/src/main/res/values-night/themes.xml
  android/festago-staff/app/src/main/res/values/colors.xml
  android/festago-staff/app/src/main/res/values/dimens.xml
  android/festago-staff/app/src/main/res/values/strings.xml
  android/festago-staff/app/src/main/res/values/themes.xml
  android/festago-staff/app/src/main/res/xml/backup_rules.xml
  android/festago-staff/app/src/main/res/xml/data_extraction_rules.xml
  android/festago-staff/build.gradle.kts
  android/festago-staff/gradle.properties
  android/festago-staff/gradle/wrapper/gradle-wrapper.jar
  android/festago-staff/gradle/wrapper/gradle-wrapper.properties
  android/festago-staff/gradlew
  android/festago-staff/gradlew.bat
  android/festago-staff/settings.gradle.kts
Labels: AN, STAFF

#50 [AN/USER] feat: 티켓 정보를 받아오는 API 연동 (#42)
  android/festago/app/build.gradle.kts
  android/festago/app/src/main/AndroidManifest.xml
  android/festago/app/src/main/java/com/festago/festago/data/MockWeb.kt
  android/festago/app/src/main/java/com/festago/festago/data/RetrofitClient.kt
  android/festago/app/src/main/java/com/festago/festago/data/dto/StageDto.kt
  android/festago/app/src/main/java/com/festago/festago/data/dto/TicketCodeDto.kt
  android/festago/app/src/main/java/com/festago/festago/data/dto/TicketDto.kt
  android/festago/app/src/main/java/com/festago/festago/data/repository/TicketDefaultRepository.kt
  android/festago/app/src/main/java/com/festago/festago/data/service/TicketRetrofitService.kt
  android/festago/app/src/main/java/com/festago/festago/domain/model/Stage.kt
  android/festago/app/src/main/java/com/festago/festago/domain/model/Ticket.kt
  android/festago/app/src/main/java/com/festago/festago/domain/model/TicketState.kt
  android/festago/app/src/main/java/com/festago/festago/domain/model/timer/Timer.kt
  android/festago/app/src/main/java/com/festago/festago/domain/repository/TicketRepository.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryViewModel.kt
Labels: AN, USER

#53 [BE] feat: 유저의 티켓 조회 기능 구현 (#25)
  backend/src/main/java/com/festago/application/EntryService.java
  backend/src/main/java/com/festago/application/MemberTicketService.java
  backend/src/main/java/com/festago/domain/MemberRepository.java
  backend/src/main/java/com/festago/domain/MemberTicket.java
  backend/src/main/java/com/festago/domain/MemberTicketRepository.java
  backend/src/main/java/com/festago/domain/Stage.java
  backend/src/main/java/com/festago/domain/StageRepository.java
  backend/src/main/java/com/festago/domain/Ticket.java
  backend/src/main/java/com/festago/domain/TicketRepository.java
  backend/src/main/java/com/festago/dto/EntryCodeResponse.java
  backend/src/main/java/com/festago/dto/MemberTicketResponse.java
  backend/src/main/java/com/festago/dto/MemberTicketsResponse.java
  backend/src/main/java/com/festago/dto/StageResponse.java
  backend/src/main/java/com/festago/presentation/TicketController.java
  backend/src/main/resources/application-local.yml
  backend/src/test/java/com/festago/application/MemberTicketServiceTest.java
  backend/src/test/java/com/festago/domain/MemberTicketRepositoryTest.java
  backend/src/test/java/com/festago/presentation/TicketControllerTest.java
Labels: BE

#48 [AN/USER] feat: 티켓 제시 화면에 티켓 정보 표시 (#44)
  android/festago/app/src/main/java/com/festago/festago/presentation/mapper/StageMapper.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/mapper/TicketMapper.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/mapper/TicketStateMapper.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/model/StageUiModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/model/TicketCodeUiModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/model/TicketStateUiModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/model/TicketUiModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketentry/TicketColorBindingAdapter.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryViewModel.kt
  android/festago/app/src/main/res/drawable/bg_ticket_gradient_primary.xml
  android/festago/app/src/main/res/drawable/bg_ticket_gradient_secondary.xml
  android/festago/app/src/main/res/drawable/btn_circle_primary.xml
  android/festago/app/src/main/res/drawable/ic_renew.xml
  android/festago/app/src/main/res/drawable/pb_ticket_remain_time.xml
  android/festago/app/src/main/res/layout/activity_ticket_entry.xml
  android/festago/app/src/main/res/values/strings.xml
Labels: AN, USER

#47 [AN/USER] feat: 페스타고 메인 화면 구현(#45)
  android/festago/app/build.gradle.kts
  android/festago/app/src/main/AndroidManifest.xml
  android/festago/app/src/main/java/com/festago/festago/MainActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/BindingAdapter.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/MainActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/MainEvent.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/MainViewModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/util/Event.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/util/MutableSingleLiveData.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/util/SingleLiveData.kt
  android/festago/app/src/main/res/drawable/img_festago_logo.xml
  android/festago/app/src/main/res/layout/activity_main.xml
  android/festago/app/src/main/res/values/strings.xml
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/MainViewModelTest.kt
Labels: AN, USER

#57 [AN/USER] test: 티켓 제시 화면 티켓 받기 테스트 작성 (#55)
  android/festago/app/src/test/java/com/festago/festago/presentation/ticketentry/TicketEntryViewModelTest.kt
Labels: AN, USER

#61 [BE] feat: 스태프 티겟 검사 기능 구현 (#27)
  backend/src/main/java/com/festago/application/EntryService.java
  backend/src/main/java/com/festago/config/EntryCodeConfig.java
  backend/src/main/java/com/festago/domain/EntryCode.java
  backend/src/main/java/com/festago/domain/EntryCodeExtractor.java
  backend/src/main/java/com/festago/domain/EntryCodePayload.java
  backend/src/main/java/com/festago/domain/EntryCodeProvider.java
  backend/src/main/java/com/festago/domain/EntryState.java
  backend/src/main/java/com/festago/domain/MemberTicket.java
  backend/src/main/java/com/festago/dto/TicketValidationRequest.java
  backend/src/main/java/com/festago/dto/TicketValidationResponse.java
  backend/src/main/java/com/festago/infrastructure/JwtEntryCodeExtractor.java
  backend/src/main/java/com/festago/infrastructure/JwtEntryCodeProvider.java
  backend/src/main/java/com/festago/presentation/StaffTicketController.java
  backend/src/test/java/com/festago/application/EntryServiceTest.java
  backend/src/test/java/com/festago/domain/EntryStateTest.java
  backend/src/test/java/com/festago/domain/MemberTicketTest.java
  backend/src/test/java/com/festago/infrastructure/JwtEntryCodeExtractorTest.java
  backend/src/test/java/com/festago/infrastructure/JwtEntryCodeProviderTest.java
  backend/src/test/java/com/festago/presentation/StaffTicketControllerTest.java
Labels: BE

#66 [BE] feat: 더미 데이터 생성 (#62)
  backend/src/main/java/com/festago/config/DemoDataInitConfig.java
  backend/src/main/java/com/festago/demo/DemoController.java
  backend/src/main/java/com/festago/domain/Ticket.java
  backend/src/main/resources/application-local.yml
Labels: BE

#60 [AN/USER] feat: 티켓 제시 화면이 티켓 상태에 따라 색 변경 (#59)
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketentry/QrImageBindingAdapter.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketentry/TicketColorBindingAdapter.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryBindingAdapter.kt
  android/festago/app/src/main/res/drawable/btn_circle_secondary.xml
  android/festago/app/src/main/res/drawable/pb_ticket_remain_time_primary.xml
  android/festago/app/src/main/res/drawable/pb_ticket_remain_time_secondary.xml
  android/festago/app/src/main/res/layout/activity_ticket_entry.xml
Labels: AN, USER

#68 [BE] feat: dev 브랜치에 CI workflow 추가 (#67)
  .github/workflows/ci-back.yml
  backend/src/main/java/com/festago/presentation/TicketController.java
Labels: BE

#64 [AN/USER] feat: 유저 메인 화면에서 받아온 정보에 따라 화면이 변환 (#56)
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/BindingAdapter.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/MainActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/MainBinding.kt
  android/festago/app/src/main/res/drawable/btn_festa.xml
  android/festago/app/src/main/res/drawable/btn_festa_disabled.xml
  android/festago/app/src/main/res/drawable/btn_festa_normal.xml
  android/festago/app/src/main/res/layout/activity_main.xml
  android/festago/app/src/main/res/values/strings.xml
  android/festago/app/src/main/res/values/style.xml
Labels: AN, USER

#70 [AN/USER/STAFF] feat: 유저와 스태프 어플 서버 비밀 값으로 변경 (#69)
  android/festago-staff/app/build.gradle.kts
  android/festago-staff/app/src/main/java/com/festago/festagostaff/data/RetrofitClient.kt
  android/festago-staff/gradle.properties
  android/festago/app/build.gradle.kts
  android/festago/app/src/main/java/com/festago/festago/data/RetrofitClient.kt
  android/festago/gradle.properties
Labels: AN, STAFF, USER

#65 [AN/STAFF] feat: QR 스캔 화면 커스텀 및 기능을 변경(#63)
  android/festago-staff/app/src/main/java/com/festago/festagostaff/data/dto/TicketValidationRequestDto.kt
  android/festago-staff/app/src/main/java/com/festago/festagostaff/data/repository/TicketDefaultRepository.kt
  android/festago-staff/app/src/main/java/com/festago/festagostaff/data/service/TicketRetrofitService.kt
  android/festago-staff/app/src/main/java/com/festago/festagostaff/presentation/ui/ticketvalidation/TicketValidationActivity.kt
  android/festago-staff/app/src/main/java/com/festago/festagostaff/presentation/ui/ticketvalidation/TicketValidationViewModel.kt
  android/festago-staff/app/src/main/res/drawable/btn_circle_primary.xml
  android/festago-staff/app/src/main/res/drawable/ic_refresh.xml
  android/festago-staff/app/src/main/res/layout/activity_ticket_validation.xml
  android/festago-staff/app/src/test/java/com/festago/festagostaff/presentation/ui/ticketvalidation/TicketValidationViewModelTest.kt
Labels: AN, STAFF

#73 [AN/USER] 리소스 변경사항 반영 (#72)
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/MainBinding.kt
Labels: AN, USER

#76 [AN] design: 앱 아이콘 적용
  android/festago-staff/app/src/main/AndroidManifest.xml
  android/festago-staff/app/src/main/ic_festago_staff_logo-playstore.png
  android/festago-staff/app/src/main/res/drawable/ic_festago_staff_logo_background.xml
  android/festago-staff/app/src/main/res/drawable/ic_festago_staff_logo_foreground.xml
  android/festago-staff/app/src/main/res/mipmap-anydpi-v26/ic_festago_staff_logo.xml
  android/festago-staff/app/src/main/res/mipmap-anydpi-v26/ic_festago_staff_logo_round.xml
  android/festago-staff/app/src/main/res/mipmap-hdpi/ic_festago_staff_logo.png
  android/festago-staff/app/src/main/res/mipmap-hdpi/ic_festago_staff_logo_round.png
  android/festago-staff/app/src/main/res/mipmap-mdpi/ic_festago_staff_logo.png
  android/festago-staff/app/src/main/res/mipmap-mdpi/ic_festago_staff_logo_round.png
  android/festago-staff/app/src/main/res/mipmap-xhdpi/ic_festago_staff_logo.png
  android/festago-staff/app/src/main/res/mipmap-xhdpi/ic_festago_staff_logo_round.png
  android/festago-staff/app/src/main/res/mipmap-xxhdpi/ic_festago_staff_logo.png
  android/festago-staff/app/src/main/res/mipmap-xxhdpi/ic_festago_staff_logo_round.png
  android/festago-staff/app/src/main/res/mipmap-xxxhdpi/ic_festago_staff_logo.png
  android/festago-staff/app/src/main/res/mipmap-xxxhdpi/ic_festago_staff_logo_round.png
  android/festago/app/src/main/AndroidManifest.xml
  android/festago/app/src/main/ic_festago_logo-playstore.png
  android/festago/app/src/main/res/drawable/ic_festago_logo_background.xml
  android/festago/app/src/main/res/drawable/ic_festago_logo_foreground.xml
  android/festago/app/src/main/res/mipmap-anydpi-v26/ic_festago_logo.xml
  android/festago/app/src/main/res/mipmap-anydpi-v26/ic_festago_logo_round.xml
  android/festago/app/src/main/res/mipmap-hdpi/ic_festago_logo.png
  android/festago/app/src/main/res/mipmap-hdpi/ic_festago_logo_round.png
  android/festago/app/src/main/res/mipmap-mdpi/ic_festago_logo.png
  android/festago/app/src/main/res/mipmap-mdpi/ic_festago_logo_round.png
  android/festago/app/src/main/res/mipmap-xhdpi/ic_festago_logo.png
  android/festago/app/src/main/res/mipmap-xhdpi/ic_festago_logo_round.png
  android/festago/app/src/main/res/mipmap-xxhdpi/ic_festago_logo.png
  android/festago/app/src/main/res/mipmap-xxhdpi/ic_festago_logo_round.png
  android/festago/app/src/main/res/mipmap-xxxhdpi/ic_festago_logo.png
  android/festago/app/src/main/res/mipmap-xxxhdpi/ic_festago_logo_round.png
Labels: AN, STAFF, USER

#75 [AN/USER] 티켓 상태가 외출중이면 다른 색을 보여준다 (#71)
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryBindingAdapter.kt
  android/festago/app/src/main/res/drawable/bg_ticket_gradient_tertiary.xml
  android/festago/app/src/main/res/drawable/btn_circle_tertiary.xml
  android/festago/app/src/main/res/drawable/pb_ticket_remain_time_tertiary.xml
Labels: AN, USER

#80 [AN/STAFF] fix: 카메라 권한 요청(#77)
  android/festago-staff/app/src/main/AndroidManifest.xml
  android/festago-staff/app/src/main/java/com/festago/festagostaff/presentation/extension/ActivityExtension.kt
  android/festago-staff/app/src/main/java/com/festago/festagostaff/presentation/ui/ticketvalidation/TicketValidationActivity.kt
  android/festago-staff/app/src/main/res/values/strings.xml
Labels: AN, STAFF

#83 [AN/STAFF] feat: 파이어 베이스 연동(#82)
  android/festago-staff/.gitignore
  android/festago-staff/app/build.gradle.kts
  android/festago-staff/build.gradle.kts
Labels: AN, STAFF

#84 [AN/USER] feat: 파이어 베이스 연동(#81)
  android/festago/app/.gitignore
  android/festago/app/build.gradle.kts
  android/festago/build.gradle.kts
Labels: AN, USER

#86 [ALL] feat: Assign Reviewer By Label에 사용되는 토큰을 GITHUB_TOKEN으로 변경 (#85)
  .github/workflows/assign-reviewer.yml
Labels: ALL, ETC

#88 [ALL] feat: .github 디렉터리 안에 있는 사용하지 않는 파일을 삭제 (#87)
  .github/all-create-jira-issue.yml
Labels: ALL, ETC

#98 [BE] refactor: JwtEntryCodeExtractor에서 사용하는 JwtParser를 로컬 변수에서 멤버 변수로 이동 (#97)
  backend/src/main/java/com/festago/infrastructure/JwtEntryCodeExtractor.java
Labels: BE

#104 [AN/USER] feat: 메인 화면을 프래그먼트, 바텀네비게이션 구현(#92)
  android/festago/app/src/main/AndroidManifest.xml
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/MainViewModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/HomeActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/HomeItemType.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListFragment.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageFragment.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListFragment.kt
  android/festago/app/src/main/res/drawable/ic_bottom_navigation_festival.xml
  android/festago/app/src/main/res/drawable/ic_bottom_navigation_user.xml
  android/festago/app/src/main/res/layout/activity_home.xml
  android/festago/app/src/main/res/layout/fragment_festival_list.xml
  android/festago/app/src/main/res/layout/fragment_my_page.xml
  android/festago/app/src/main/res/layout/fragment_ticket_list.xml
  android/festago/app/src/main/res/menu/menu_bottom_navigation.xml
  android/festago/app/src/main/res/values/strings.xml
Labels: AN, USER

#103 [ALL] feat: 라벨에 따라 리뷰어를 자동 할당하는 Action 변경 (#89)
  .github/workflows/assign-reviewer.yml
Labels: ALL

#107 [BE] feat: 테스트 픽스쳐 제작 및 불필요한 도메인 생성자 제거 (#54)
  backend/src/main/java/com/festago/demo/DemoController.java
  backend/src/main/java/com/festago/domain/MemberTicket.java
  backend/src/main/java/com/festago/domain/Ticket.java
  backend/src/main/java/com/festago/infrastructure/JwtEntryCodeProvider.java
  backend/src/test/java/com/festago/application/EntryServiceTest.java
  backend/src/test/java/com/festago/application/MemberTicketServiceTest.java
  backend/src/test/java/com/festago/domain/MemberTicketRepositoryTest.java
  backend/src/test/java/com/festago/domain/MemberTicketTest.java
  backend/src/test/java/com/festago/domain/TicketTest.java
  backend/src/test/java/com/festago/infrastructure/JwtEntryCodeExtractorTest.java
  backend/src/test/java/com/festago/infrastructure/JwtEntryCodeProviderTest.java
  backend/src/test/java/com/festago/support/MemberFixture.java
  backend/src/test/java/com/festago/support/MemberTicketFixture.java
  backend/src/test/java/com/festago/support/StageFixture.java
  backend/src/test/java/com/festago/support/TicketFixture.java
Labels: BE

#108 [BE] feat: 커스텀 예외 생성 및 예외 처리 도입 (#78)
  backend/src/main/java/com/festago/application/EntryService.java
  backend/src/main/java/com/festago/application/MemberTicketService.java
  backend/src/main/java/com/festago/domain/EntryCode.java
  backend/src/main/java/com/festago/domain/EntryCodePayload.java
  backend/src/main/java/com/festago/domain/EntryState.java
  backend/src/main/java/com/festago/domain/MemberTicket.java
  backend/src/main/java/com/festago/dto/ErrorResponse.java
  backend/src/main/java/com/festago/dto/MemberTicketResponse.java
  backend/src/main/java/com/festago/dto/MemberTicketsResponse.java
  backend/src/main/java/com/festago/exception/BadRequestException.java
  backend/src/main/java/com/festago/exception/ErrorCode.java
  backend/src/main/java/com/festago/exception/FestaGoException.java
  backend/src/main/java/com/festago/exception/InternalServerException.java
  backend/src/main/java/com/festago/exception/NotFoundException.java
  backend/src/main/java/com/festago/infrastructure/JwtEntryCodeExtractor.java
  backend/src/main/java/com/festago/infrastructure/JwtEntryCodeProvider.java
  backend/src/main/java/com/festago/presentation/GlobalExceptionHandler.java
  backend/src/main/java/com/festago/presentation/TicketController.java
  backend/src/test/java/com/festago/application/EntryServiceTest.java
  backend/src/test/java/com/festago/application/MemberTicketServiceTest.java
  backend/src/test/java/com/festago/domain/EntryStateTest.java
  backend/src/test/java/com/festago/domain/MemberTicketTest.java
  backend/src/test/java/com/festago/infrastructure/JwtEntryCodeExtractorTest.java
  backend/src/test/java/com/festago/infrastructure/JwtEntryCodeProviderTest.java
Labels: BE

#105 [AN/USER] feat: 티켓 예매 화면 - 화면 작업 (#90)
  android/festago/app/src/main/AndroidManifest.xml
  android/festago/app/src/main/java/com/festago/festago/data/repository/ReservationDefaultRepository.kt
  android/festago/app/src/main/java/com/festago/festago/domain/model/Reservation.kt
  android/festago/app/src/main/java/com/festago/festago/domain/model/ReservationStage.kt
  android/festago/app/src/main/java/com/festago/festago/domain/model/ReservationTicket.kt
  android/festago/app/src/main/java/com/festago/festago/domain/repository/ReservationRepository.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/mapper/ReservationMapper.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/mapper/ReservationStageMapper.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/mapper/ReservationTicketMapper.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/model/ReservationStageUiModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/model/ReservationTicketUiModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/model/ReservationUiModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/BindingAdapter.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveUiState.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveViewModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/adapter/TicketReserveAdapter.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/adapter/TicketReserveHeaderAdapter.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/viewHolder/TicketReserveHeaderViewHolder.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/viewHolder/TicketReserveViewHolder.kt
  android/festago/app/src/main/res/layout/activity_ticket_reserve.xml
  android/festago/app/src/main/res/layout/item_ticket_reserve.xml
  android/festago/app/src/main/res/layout/item_ticket_reserve_header.xml
  android/festago/app/src/main/res/values/strings.xml
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveViewModelTest.kt
Labels: AN, USER

#109 [BE] feat: 축제 도메인 추가 및 기존 도메인 수정 (#106)
  backend/src/main/java/com/festago/config/DemoDataInitConfig.java
  backend/src/main/java/com/festago/demo/DemoController.java
  backend/src/main/java/com/festago/domain/Festival.java
  backend/src/main/java/com/festago/domain/FestivalRepository.java
  backend/src/main/java/com/festago/domain/Member.java
  backend/src/main/java/com/festago/domain/MemberTicket.java
  backend/src/main/java/com/festago/domain/Stage.java
  backend/src/main/java/com/festago/domain/Ticket.java
  backend/src/main/java/com/festago/domain/TicketType.java
  backend/src/main/java/com/festago/dto/StageResponse.java
  backend/src/main/java/com/festago/exception/ErrorCode.java
  backend/src/test/java/com/festago/application/EntryServiceTest.java
  backend/src/test/java/com/festago/domain/FestivalTest.java
  backend/src/test/java/com/festago/domain/MemberTicketRepositoryTest.java
  backend/src/test/java/com/festago/domain/StageTest.java
  backend/src/test/java/com/festago/infrastructure/JwtEntryCodeProviderTest.java
  backend/src/test/java/com/festago/presentation/TicketControllerTest.java
  backend/src/test/java/com/festago/support/FestivalFixture.java
  backend/src/test/java/com/festago/support/MemberFixture.java
  backend/src/test/java/com/festago/support/MemberTicketFixture.java
  backend/src/test/java/com/festago/support/StageFixture.java
  backend/src/test/java/com/festago/support/TicketFixture.java
  backend/src/test/resources/application-test.yml
  backend/src/test/resources/application.yml
Labels: BE

#127 [AN/USER] feat: 축제 목록 화면 구현(#95)
  android/festago/app/src/main/AndroidManifest.xml
  android/festago/app/src/main/java/com/festago/festago/data/repository/FestivalDefaultRepository.kt
  android/festago/app/src/main/java/com/festago/festago/domain/model/Festival.kt
  android/festago/app/src/main/java/com/festago/festago/domain/repository/FestivalRepository.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/mapper/FestivalMapper.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/model/FestivalUiModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/BindingAdapter.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalItemViewHolder.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListAdapter.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListBindingAdapter.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListFragment.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListUiState.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListViewModel.kt
  android/festago/app/src/main/res/drawable/ic_image_placeholder.xml
  android/festago/app/src/main/res/layout/fragment_festival_list.xml
  android/festago/app/src/main/res/layout/item_festival.xml
  android/festago/app/src/main/res/values/strings.xml
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListViewModelTest.kt
Labels: AN, USER

#128 [BE] feat: 축제 도메인 추가 및 기존 도메인 수정 (#115)
  backend/src/main/java/com/festago/application/FestivalService.java
  backend/src/main/java/com/festago/domain/Festival.java
  backend/src/main/java/com/festago/dto/FestivalCreateRequest.java
  backend/src/main/java/com/festago/dto/FestivalResponse.java
  backend/src/main/java/com/festago/presentation/AdminController.java
  backend/src/test/java/com/festago/application/FestivalServiceTest.java
  backend/src/test/java/com/festago/dto/FestivalCreateRequestTest.java
  backend/src/test/java/com/festago/presentation/AdminControllerTest.java
Labels: BE

#130 [BE] feat: 관리자 공연 등록 구현(#116)
  backend/src/main/java/com/festago/application/StageService.java
  backend/src/main/java/com/festago/dto/StageCreateRequest.java
  backend/src/main/java/com/festago/exception/ErrorCode.java
  backend/src/main/java/com/festago/presentation/AdminController.java
  backend/src/test/java/com/festago/application/ApplicationTest.java
  backend/src/test/java/com/festago/application/FestivalServiceTest.java
  backend/src/test/java/com/festago/application/StageServiceTest.java
  backend/src/test/java/com/festago/presentation/AdminControllerTest.java
Labels: BE

#134 [BE] feat: 관리자 티켓 발급 구현(#117)
  backend/src/main/java/com/festago/application/TicketService.java
  backend/src/main/java/com/festago/domain/Ticket.java
  backend/src/main/java/com/festago/dto/TicketCreateRequest.java
  backend/src/main/java/com/festago/dto/TicketResponse.java
  backend/src/main/java/com/festago/exception/ErrorCode.java
  backend/src/main/java/com/festago/presentation/AdminController.java
  backend/src/test/java/com/festago/application/EntryServiceTest.java
  backend/src/test/java/com/festago/application/TicketServiceTest.java
  backend/src/test/java/com/festago/domain/TicketTest.java
  backend/src/test/java/com/festago/presentation/AdminControllerTest.java
  backend/src/test/java/com/festago/presentation/TicketControllerTest.java
  backend/src/test/java/com/festago/support/TicketFixture.java
Labels: BE, ADMIN

#137 [BE] fix: 티켓의 입장시간과 요청시간이 일치하는 경우 입장이 불가한 버그 수정 (#136)
  backend/src/main/java/com/festago/domain/Ticket.java
  backend/src/test/java/com/festago/domain/TicketTest.java
Labels: BE, FIX

#145 [BE] feat: TicketTest 테스트 실패 케이스 수정 (#144)
  backend/src/test/java/com/festago/domain/TicketTest.java
Labels: BE, ASAP, FIX

#143 [BE] feat: ErrorResponse 클래스 Record로 변경 (#142)
  backend/src/main/java/com/festago/dto/ErrorResponse.java
  backend/src/test/java/com/festago/presentation/AdminControllerTest.java
Labels: BE, 리팩터링

#146 [BE] feat: Ticket 도메인에 예매한 수량 필드 추가 (#141)
  backend/src/main/java/com/festago/domain/Ticket.java
  backend/src/main/java/com/festago/exception/ErrorCode.java
  backend/src/test/java/com/festago/domain/TicketTest.java
Labels: BE

#149 [BE] feat: Service 레이어 통합 테스트 분리 (#139)
  backend/src/test/java/com/festago/application/integration/ApplicationIntegrationTest.java
  backend/src/test/java/com/festago/application/integration/FestivalServiceIntegrationTest.java
  backend/src/test/java/com/festago/application/integration/StageServiceIntegrationTest.java
  backend/src/test/java/com/festago/application/integration/TicketServiceIntegrationTest.java
Labels: BE, 리팩터링

#135 [BE] refactor: 멤버 티켓 조회 API에 변경된 도메인 반영 (#102)
  backend/src/main/java/com/festago/config/DemoDataInitConfig.java
  backend/src/main/java/com/festago/demo/DemoController.java
  backend/src/main/java/com/festago/domain/MemberTicket.java
  backend/src/main/java/com/festago/dto/MemberTicketFestivalResponse.java
  backend/src/main/java/com/festago/dto/MemberTicketResponse.java
  backend/src/main/java/com/festago/presentation/MemberTicketController.java
  backend/src/test/java/com/festago/presentation/MemberTicketControllerTest.java
  backend/src/test/java/com/festago/support/MemberTicketFixture.java
Labels: BE, 리팩터링

#140 [BE] feat: 축제 전체 조회 API 구현 (#123)
  backend/src/main/java/com/festago/application/FestivalService.java
  backend/src/main/java/com/festago/dto/FestivalsResponse.java
  backend/src/main/java/com/festago/presentation/FestivalController.java
  backend/src/test/java/com/festago/application/FestivalServiceTest.java
  backend/src/test/java/com/festago/presentation/FestivalControllerTest.java
Labels: BE, USER

#150 [BE] feat: 티켓 도메인 구조 수정 (#147)
  backend/src/main/java/com/festago/application/TicketService.java
  backend/src/main/java/com/festago/config/DemoDataInitConfig.java
  backend/src/main/java/com/festago/demo/DemoController.java
  backend/src/main/java/com/festago/domain/MemberTicket.java
  backend/src/main/java/com/festago/domain/MemberTicketRepository.java
  backend/src/main/java/com/festago/domain/Ticket.java
  backend/src/main/java/com/festago/domain/TicketAmount.java
  backend/src/main/java/com/festago/domain/TicketEntryTime.java
  backend/src/main/java/com/festago/domain/TicketRepository.java
  backend/src/main/java/com/festago/dto/MemberTicketResponse.java
  backend/src/main/java/com/festago/dto/TicketCreateRequest.java
  backend/src/main/java/com/festago/dto/TicketCreateResponse.java
  backend/src/main/java/com/festago/dto/TicketResponse.java
  backend/src/main/java/com/festago/presentation/AdminController.java
  backend/src/test/java/com/festago/application/EntryServiceTest.java
  backend/src/test/java/com/festago/application/MemberTicketServiceTest.java
  backend/src/test/java/com/festago/application/TicketServiceTest.java
  backend/src/test/java/com/festago/domain/MemberTicketRepositoryTest.java
  backend/src/test/java/com/festago/domain/MemberTicketTest.java
  backend/src/test/java/com/festago/domain/TicketAmountTest.java
  backend/src/test/java/com/festago/domain/TicketEntryTimeTest.java
  backend/src/test/java/com/festago/domain/TicketTest.java
  backend/src/test/java/com/festago/presentation/AdminControllerTest.java
  backend/src/test/java/com/festago/support/MemberTicketFixture.java
  backend/src/test/java/com/festago/support/TicketFixture.java
Labels: BE, 리팩터링

#131 [AN/USER] feat: 축제 목록 화면 -> 티켓 예매 화면 연결(#129)
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalItemViewHolder.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListAdapter.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListBindingAdapter.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListEvent.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListFragment.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListViewModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveActivity.kt
  android/festago/app/src/main/res/layout/item_festival.xml
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListViewModelTest.kt
Labels: AN, USER

#154 [AN/USER] 예매 티켓 리스트 화면 - 화면 작업 (#99)
  android/festago/app/src/main/java/com/festago/festago/data/dto/TicketDto.kt
  android/festago/app/src/main/java/com/festago/festago/data/repository/TicketDefaultRepository.kt
  android/festago/app/src/main/java/com/festago/festago/domain/model/Ticket.kt
  android/festago/app/src/main/java/com/festago/festago/domain/repository/TicketRepository.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/mapper/TicketMapper.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/model/TicketUiModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListAdapter.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListEvent.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListFragment.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListItemViewHolder.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListUiState.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListViewModel.kt
  android/festago/app/src/main/res/drawable/img_ticket.xml
  android/festago/app/src/main/res/layout/fragment_ticket_list.xml
  android/festago/app/src/main/res/layout/item_ticket_list.xml
  android/festago/app/src/main/res/values/strings.xml
  android/festago/app/src/test/java/com/festago/festago/presentation/ticketentry/TicketEntryViewModelTest.kt
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/MainViewModelTest.kt
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListViewModelTest.kt
Labels: AN, USER

#132 [AN/USER] feat: 티켓 예매 화면 - 바텀 시트 추가 (#93)
  android/festago/app/src/main/java/com/festago/festago/presentation/model/ReservationStageUiModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/model/ReservationTicketUiModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveEvent.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveViewModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/adapter/TicketReserveAdapter.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/bottomSheet/TicketReserveBottomItem.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/bottomSheet/TicketReserveBottomSheetAdapter.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/bottomSheet/TicketReserveBottomSheetCallback.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/bottomSheet/TicketReserveBottomSheetFragment.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/bottomSheet/TicketReserveBottomViewHolder.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/viewHolder/TicketReserveViewHolder.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/util/ParcelizeUtil.kt
  android/festago/app/src/main/res/drawable/bg_ticket_reserve_bottom_sheet.xml
  android/festago/app/src/main/res/drawable/bg_ticket_reserve_bottom_sheet_item.xml
  android/festago/app/src/main/res/layout/fragment_ticket_reserve_bottom_sheet.xml
  android/festago/app/src/main/res/layout/item_ticket_reserve.xml
  android/festago/app/src/main/res/layout/item_ticket_reserve_bottom_sheet.xml
  android/festago/app/src/main/res/values/strings.xml
Labels: AN, USER

#152 [BE] feat: 티켓을 생성할 때 데이터베이스에 INSERT 되지 않는 버그 수정 (#151)
  backend/src/main/java/com/festago/application/TicketService.java
  backend/src/main/java/com/festago/domain/Ticket.java
Labels: BE, ASAP, ADMIN, FIX

#161 [BE] feat: TicketEntryTime 검증 로직 Ticket의 addTicketEntryTime 메소드로 이동 (#155)
  backend/src/main/java/com/festago/domain/Ticket.java
  backend/src/main/java/com/festago/domain/TicketEntryTime.java
  backend/src/test/java/com/festago/domain/TicketEntryTimeTest.java
  backend/src/test/java/com/festago/domain/TicketTest.java
Labels: BE, 리팩터링
