Repository woowacourse-teams/2023-festa-go, pull requests merged in 2023-10, with the labels that each got.

#475 [AN/USER] refactor: 학교 선택 화면 success 캐스팅 코드 리팩(#473)
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/selectschool/SelectSchoolViewModel.kt
Labels: AN, USER, 리팩터링

#492 [AN/USER] LifecycleOwner 확장함수 리팩터링
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/selectschool/SelectSchoolActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/studentverification/StudentVerificationActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/util/LifecycleOwnerUtil.kt
Labels: AN, USER, 리팩터링

#489 [BE] feat: Cucumber 테스트 수정(#487)
  backend/src/test/java/com/festago/acceptance/steps/ExampleStep.java
  backend/src/test/java/com/festago/acceptance/steps/ExampleStep2.java
  backend/src/test/resources/features/example.feature
Labels: BE, 테스트

#481 [BE] refactor: 불필요한 메서드 분리 제거 (#479)
  backend/src/main/java/com/festago/auth/application/AuthService.java
Labels: BE, 리팩터링, 머지🚀

#452 [BE] feat: Lombok 라이브러리 추가 (#415)
  backend/build.gradle
  backend/src/main/java/com/festago/admin/application/AdminService.java
  backend/src/main/java/com/festago/admin/domain/Admin.java
  backend/src/main/java/com/festago/auth/application/AdminAuthService.java
  backend/src/main/java/com/festago/auth/application/AuthFacadeService.java
  backend/src/main/java/com/festago/auth/application/AuthService.java
  backend/src/main/java/com/festago/auth/config/LoginConfig.java
  backend/src/main/java/com/festago/entry/application/EntryCodeManager.java
  backend/src/main/java/com/festago/entry/application/EntryService.java
  backend/src/main/java/com/festago/festival/application/FestivalService.java
  backend/src/main/java/com/festago/festival/domain/Festival.java
  backend/src/main/java/com/festago/member/application/MemberService.java
  backend/src/main/java/com/festago/member/domain/Member.java
  backend/src/main/java/com/festago/presentation/AdminController.java
  backend/src/main/java/com/festago/presentation/AuthController.java
  backend/src/main/java/com/festago/presentation/FestivalController.java
  backend/src/main/java/com/festago/presentation/GlobalExceptionHandler.java
  backend/src/main/java/com/festago/presentation/MemberController.java
  backend/src/main/java/com/festago/presentation/MemberTicketController.java
  backend/src/main/java/com/festago/presentation/SchoolController.java
  backend/src/main/java/com/festago/presentation/StaffMemberTicketController.java
  backend/src/main/java/com/festago/presentation/StageController.java
  backend/src/main/java/com/festago/presentation/StudentController.java
  backend/src/main/java/com/festago/school/application/SchoolService.java
  backend/src/main/java/com/festago/school/domain/School.java
  backend/src/main/java/com/festago/stage/application/StageService.java
  backend/src/main/java/com/festago/stage/domain/Stage.java
  backend/src/main/java/com/festago/student/application/StudentService.java
  backend/src/main/java/com/festago/student/domain/Student.java
  backend/src/main/java/com/festago/student/domain/StudentCode.java
  backend/src/main/java/com/festago/student/domain/VerificationCode.java
  backend/src/main/java/com/festago/ticket/application/TicketService.java
  backend/src/main/java/com/festago/ticket/domain/Ticket.java
  backend/src/main/java/com/festago/ticket/domain/TicketAmount.java
  backend/src/main/java/com/festago/ticket/domain/TicketEntryTime.java
  backend/src/main/java/com/festago/ticketing/application/MemberTicketService.java
  backend/src/main/java/com/festago/ticketing/application/TicketingService.java
  backend/src/main/java/com/festago/ticketing/domain/MemberTicket.java
Labels: BE, 리팩터링

#486 [BE] feat: 슬랙으로 오는 로그 알림에서 기본 WARN 알림 제외 (#485)
  backend/src/main/resources/logback-spring.xml
Labels: BE, 인프라, FIX

#477 [BE] refactor: assertThatThrownBy.hasMessage()에서 ErrorCode를 활용하도록 수정 (#476)
  backend/src/test/java/com/festago/application/EntryServiceTest.java
  backend/src/test/java/com/festago/application/FestivalServiceTest.java
  backend/src/test/java/com/festago/application/MemberTicketServiceTest.java
  backend/src/test/java/com/festago/application/StudentServiceTest.java
  backend/src/test/java/com/festago/application/integration/StageServiceIntegrationTest.java
  backend/src/test/java/com/festago/application/integration/TicketServiceIntegrationTest.java
  backend/src/test/java/com/festago/application/integration/TicketingServiceIntegrationTest.java
  backend/src/test/java/com/festago/auth/application/AdminAuthServiceTest.java
  backend/src/test/java/com/festago/auth/application/AuthServiceTest.java
  backend/src/test/java/com/festago/auth/domain/OAuth2ClientsTest.java
  backend/src/test/java/com/festago/auth/infrastructure/HeaderTokenExtractorTest.java
  backend/src/test/java/com/festago/auth/infrastructure/JwtAuthExtractorTest.java
  backend/src/test/java/com/festago/auth/infrastructure/KakaoOAuth2UserInfoClientTest.java
  backend/src/test/java/com/festago/auth/presentation/RoleArgumentResolverTest.java
  backend/src/test/java/com/festago/domain/EntryCodeTest.java
  backend/src/test/java/com/festago/domain/EntryStateTest.java
  backend/src/test/java/com/festago/domain/FestivalTest.java
  backend/src/test/java/com/festago/domain/StageTest.java
  backend/src/test/java/com/festago/domain/TicketAmountTest.java
  backend/src/test/java/com/festago/domain/TicketEntryTimeTest.java
  backend/src/test/java/com/festago/domain/TicketTest.java
  backend/src/test/java/com/festago/infrastructure/JwtEntryCodeExtractorTest.java
  backend/src/test/java/com/festago/infrastructure/JwtEntryCodeProviderTest.java
  backend/src/test/java/com/festago/ticketing/application/TicketingServiceTest.java
Labels: BE, 머지🚀

#493 [AN/USER] refactor: LiveData to Flow 리팩터링 (축제 목록, 마이페이지)
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListFragment.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListViewModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageFragment.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageViewModel.kt
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListViewModelTest.kt
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/mypage/MyPageViewModelTest.kt
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/selectschool/SelectSchoolViewModelTest.kt
Labels: AN, USER, 리팩터링

#495 [AN/USER] refactor: LiveData to Flow 리팩터링 (티켓 목록, 티켓 예매, 티켓 기록, 홈화면)
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/HomeActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/HomeViewModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListFragment.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListViewModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/tickethistory/TicketHistoryActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/tickethistory/TicketHistoryViewModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveViewModel.kt
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/HomeViewModelTest.kt
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListViewModelTest.kt
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/selectschool/SelectSchoolViewModelTest.kt
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/studentverification/StudentVerificationViewModelTest.kt
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/tickethistory/TicketHistoryViewModelTest.kt
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveViewModelTest.kt
Labels: AN, USER, 리팩터링

#469 [BE] feat: Festival, Ticket 테이블의 school_id의 not null 제약조건 추가(#468)
  backend/src/main/java/com/festago/festival/domain/Festival.java
  backend/src/main/java/com/festago/ticket/domain/Ticket.java
  backend/src/main/resources/db/migration/V6__school_notnull.sql
Labels: BE, flyway, 머지🚀

#463 [BE] refactor: request DTO Validation 추가(#462)
  backend/src/main/java/com/festago/auth/dto/AdminLoginRequest.java
  backend/src/main/java/com/festago/auth/dto/AdminSignupRequest.java
  backend/src/main/java/com/festago/auth/dto/LoginRequest.java
  backend/src/main/java/com/festago/auth/dto/RootAdminInitializeRequest.java
  backend/src/main/java/com/festago/common/exception/dto/ErrorResponse.java
  backend/src/main/java/com/festago/entry/dto/TicketValidationRequest.java
  backend/src/main/java/com/festago/festival/dto/FestivalCreateRequest.java
  backend/src/main/java/com/festago/presentation/AuthController.java
  backend/src/main/java/com/festago/presentation/GlobalExceptionHandler.java
  backend/src/main/java/com/festago/presentation/StudentController.java
  backend/src/main/java/com/festago/school/dto/SchoolCreateRequest.java
  backend/src/main/java/com/festago/stage/dto/StageCreateRequest.java
  backend/src/main/java/com/festago/student/dto/StudentSendMailRequest.java
  backend/src/main/java/com/festago/student/dto/StudentVerificateRequest.java
  backend/src/main/java/com/festago/ticket/dto/TicketCreateRequest.java
  backend/src/main/java/com/festago/ticketing/dto/TicketingRequest.java
Labels: BE

#467 [BE] feat: 학생 인증 메일 전송 잦은 재요청시 예외처리 (#466)
  backend/src/main/java/com/festago/common/exception/ErrorCode.java
  backend/src/main/java/com/festago/common/exception/TooManyRequestException.java
  backend/src/main/java/com/festago/presentation/GlobalExceptionHandler.java
  backend/src/main/java/com/festago/student/application/StudentService.java
  backend/src/main/java/com/festago/student/domain/StudentCode.java
  backend/src/main/java/com/festago/student/repository/StudentCodeRepository.java
  backend/src/main/resources/db/migration/V7__studnet_code__unique.sql
  backend/src/test/java/com/festago/student/application/StudentServiceTest.java
  backend/src/test/java/com/festago/student/domain/StudentCodeTest.java
  backend/src/test/java/com/festago/support/SetUpMockito.java
  backend/src/test/java/com/festago/support/StudentCodeFixture.java
  backend/src/test/java/com/festago/ticketing/application/TicketingServiceTest.java
Labels: BE, flyway

#501 [BE] fix: sql 문법 에러 해결 (#500)
  backend/src/main/resources/db/migration/V7__studnet_code__unique.sql
Labels: BE, FIX

#504 [BE] chore: SpringBoot version 3.1.4로 업데이트
  backend/build.gradle
Labels: BE

#460 [BE] feat: 어드민 페이지 추가 관리 기능 추가, 개선 (#459)
  backend/src/main/java/com/festago/auth/config/LoginConfig.java
  backend/src/main/java/com/festago/common/exception/ErrorCode.java
  backend/src/main/java/com/festago/common/util/Validator.java
  backend/src/main/java/com/festago/festival/application/FestivalService.java
  backend/src/main/java/com/festago/festival/domain/Festival.java
  backend/src/main/java/com/festago/festival/dto/FestivalDetailResponse.java
  backend/src/main/java/com/festago/festival/dto/FestivalResponse.java
  backend/src/main/java/com/festago/festival/dto/FestivalUpdateRequest.java
  backend/src/main/java/com/festago/presentation/AdminController.java
  backend/src/main/java/com/festago/presentation/AdminViewController.java
  backend/src/main/java/com/festago/presentation/SchoolController.java
  backend/src/main/java/com/festago/presentation/StageController.java
  backend/src/main/java/com/festago/school/application/SchoolService.java
  backend/src/main/java/com/festago/school/domain/School.java
  backend/src/main/java/com/festago/school/dto/SchoolUpdateRequest.java
  backend/src/main/java/com/festago/school/repository/SchoolRepository.java
  backend/src/main/java/com/festago/stage/application/StageService.java
  backend/src/main/java/com/festago/stage/domain/Stage.java
  backend/src/main/java/com/festago/stage/dto/StageResponse.java
  backend/src/main/java/com/festago/stage/dto/StageUpdateRequest.java
  backend/src/main/resources/static/js/admin/admin-page.js
  backend/src/main/resources/static/js/admin/festival/common-festival.js
  backend/src/main/resources/static/js/admin/festival/manage-festival-detail.js
  backend/src/main/resources/static/js/admin/festival/manage-festival.js
  backend/src/main/resources/static/js/admin/school/manage-school-detail.js
  backend/src/main/resources/static/js/admin/school/manage-school.js
  backend/src/main/resources/static/js/admin/signup.js
  backend/src/main/resources/static/js/admin/stage/manage-stage-detail.js
  backend/src/main/resources/static/js/common/UrlParser.js
  backend/src/main/resources/static/js/login.js
  backend/src/main/resources/templates/admin/admin-page.html
  backend/src/main/resources/templates/admin/festival/manage-festival-detail.html
  backend/src/main/resources/templates/admin/festival/manage-festival.html
  backend/src/main/resources/templates/admin/login.html
  backend/src/main/resources/templates/admin/school/manage-school-detail.html
  backend/src/main/resources/templates/admin/school/manage-school.html
  backend/src/main/resources/templates/admin/signup.html
  backend/src/main/resources/templates/admin/stage/manage-stage-detail.html
  backend/src/test/java/com/festago/acceptance/steps/ExampleStep.java
  backend/src/test/java/com/festago/application/FestivalServiceTest.java
  backend/src/test/java/com/festago/common/util/ValidatorTest.java
  backend/src/test/java/com/festago/domain/FestivalTest.java
  backend/src/test/java/com/festago/domain/StageTest.java
  backend/src/test/java/com/festago/presentation/AdminControllerTest.java
  backend/src/test/java/com/festago/presentation/AdminViewControllerTest.java
  backend/src/test/java/com/festago/presentation/FestivalControllerTest.java
  backend/src/test/java/com/festago/presentation/MemberTicketControllerTest.java
  backend/src/test/java/com/festago/presentation/SchoolControllerTest.java
  backend/src/test/java/com/festago/presentation/StageControllerTest.java
  backend/src/test/java/com/festago/school/domain/SchoolTest.java
Labels: BE, ADMIN

#511 [AN/USER] feat: 축제 목록, 축제 상세 API 변경사항 반영
  android/festago/app/src/main/java/com/festago/festago/data/dto/FestivalResponse.kt
  android/festago/app/src/main/java/com/festago/festago/data/dto/ReservationFestivalResponse.kt
  android/festago/app/src/test/java/com/festago/festago/data/repository/ReservationTicketRetrofitServiceTest.kt
Labels: AN, USER

#510 [AN/USER] Json convert시 생긴 에러 Catch 하도록 수정 (#509)
  android/festago/app/src/main/java/com/festago/festago/data/repository/AuthDefaultRepository.kt
  android/festago/app/src/main/java/com/festago/festago/data/repository/FestivalDefaultRepository.kt
  android/festago/app/src/main/java/com/festago/festago/data/repository/ReservationTicketDefaultRepository.kt
  android/festago/app/src/main/java/com/festago/festago/data/repository/SchoolDefaultRepository.kt
  android/festago/app/src/main/java/com/festago/festago/data/repository/StudentVerificationDefaultRepository.kt
  android/festago/app/src/main/java/com/festago/festago/data/repository/TicketDefaultRepository.kt
  android/festago/app/src/main/java/com/festago/festago/data/repository/TokenDefaultRepository.kt
  android/festago/app/src/main/java/com/festago/festago/data/repository/UserDefaultRepository.kt
  android/festago/app/src/main/java/com/festago/festago/data/util/ResponseExt.kt
  android/festago/app/src/main/java/com/festago/festago/data/util/ResultExt.kt
Labels: AN, USER, FIX

#474 [AN/USER] feat: 로그인 FCM 연동 추가(#458)
  android/festago/app/build.gradle.kts
  android/festago/app/src/main/AndroidManifest.xml
  android/festago/app/src/main/java/com/festago/festago/data/di/singletonscope/ApiModule.kt
  android/festago/app/src/main/java/com/festago/festago/data/di/singletonscope/FirebaseModule.kt
  android/festago/app/src/main/java/com/festago/festago/data/dto/OauthRequest.kt
  android/festago/app/src/main/java/com/festago/festago/data/repository/TokenDefaultRepository.kt
  android/festago/app/src/main/java/com/festago/festago/data/retrofit/TokenManager.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/service/TicketEntryService.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/signin/SignInViewModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryActivity.kt
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/signin/SignInViewModelTest.kt
  android/festago/domain/src/main/java/com/festago/festago/repository/TokenRepository.kt
Labels: AN, USER

#506 [AN/USER] 테스트 코드 리팩터링 (티켓 목록, 티켓 예매, 티켓 기록, 홈화면) (#497)
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/HomeViewModelTest.kt
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListViewModelTest.kt
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/tickethistory/TicketHistoryViewModelTest.kt
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveViewModelTest.kt
Labels: AN, USER, 리팩터링

#498 [AN/USER] refactor: LiveData to Flow 리팩터링 (티켓 제시, 로그인 화면) (#494)
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/signin/SignInActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/signin/SignInViewModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryViewModel.kt
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/signin/SignInViewModelTest.kt
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryViewModelTest.kt
Labels: AN, USER, 리팩터링

#516 [AN/USER] fix: SwipeRefresh 무한 로딩 버그 수정 (#514)
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListFragment.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageFragment.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListFragment.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveActivity.kt
Labels: AN, USER, BUG

#520 [AN/USER] 티켓 제시 화면 2개 버그 해결 (#519)
  android/festago/app/src/main/java/com/festago/festago/presentation/service/TicketEntryService.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryViewModel.kt
Labels: AN, USER, FIX

#521 [AN/USER] feat: 재학생, 방문객 영문 값 한글로 번역(#345)
  android/festago/app/src/main/java/com/festago/festago/data/dto/ReservationStageResponse.kt
  android/festago/app/src/main/java/com/festago/festago/data/dto/ReservationTicketResponse.kt
  android/festago/app/src/main/java/com/festago/festago/data/dto/ReservationTicketsResponse.kt
  android/festago/app/src/main/java/com/festago/festago/data/repository/ReservationTicketDefaultRepository.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveViewModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/bottomsheet/BottomSheetReservationTicketArg.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/bottomsheet/BottomSheetTicketTypeArg.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/bottomsheet/TicketReserveBottomViewHolder.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/viewHolder/TicketReserveViewHolder.kt
  android/festago/app/src/main/res/layout/item_ticket_reserve_bottom_sheet.xml
  android/festago/app/src/main/res/values/strings.xml
  android/festago/app/src/test/java/com/festago/festago/data/repository/ReservationTicketRetrofitServiceTest.kt
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveViewModelTest.kt
  android/festago/domain/src/main/java/com/festago/festago/model/ReservationStage.kt
  android/festago/domain/src/main/java/com/festago/festago/model/ReservationTicket.kt
  android/festago/domain/src/main/java/com/festago/festago/model/ReservationTickets.kt
  android/festago/domain/src/main/java/com/festago/festago/model/TicketType.kt
  android/festago/domain/src/main/java/com/festago/festago/repository/ReservationTicketRepository.kt
Labels: AN, USER

#472 [BE] feat: 유저 FCM 로직 변경(#471)
  backend/src/main/java/com/festago/fcm/application/FCMNotificationEventListener.java
  backend/src/main/java/com/festago/fcm/application/MemberFCMService.java
  backend/src/main/java/com/festago/fcm/repository/MemberFCMRepository.java
  backend/src/main/java/com/festago/presentation/AuthController.java
  backend/src/main/resources/db/migration/V8__unique_member_fcm.sql
  backend/src/test/java/com/festago/auth/presentation/AuthControllerTest.java
  backend/src/test/java/com/festago/fcm/application/FCMNotificationEventListenerTest.java
  backend/src/test/java/com/festago/fcm/application/MemberFCMServiceTest.java
Labels: BE, flyway

#528 [AN/USER] feat: 인앱 업데이트 적용 및 스플래시 화면 구현 (#525)
  android/festago/app/build.gradle.kts
  android/festago/app/src/main/AndroidManifest.xml
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/splash/SplashActivity.kt
  android/festago/app/src/main/res/layout/activity_splash.xml
  android/festago/app/src/main/res/values-night/themes.xml
  android/festago/app/src/main/res/values/strings.xml
  android/festago/app/src/main/res/values/themes.xml
Labels: AN, USER

#541 [BE] feat: application.yml infra 프로파일 추가(#540)
  backend/src/main/resources/application.yml
Labels: BE

#543 [BE] fix: MockMailClient 빈으로 등록되는 프로파일 변경 (#542)
  backend/src/main/java/com/festago/fcm/application/FCMNotificationEventListener.java
  backend/src/main/java/com/festago/student/infrastructure/MockMailClient.java
Labels: BE, FIX

#549 [BE] feat: MockMailClient Profile 변경 (#548)
  backend/src/main/java/com/festago/student/infrastructure/MockMailClient.java
Labels: BE, FIX

#544 [AN/USER] 홈 화면 회전시 이전에 선택한 화면을 그대로 보여준다. (#534)
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/HomeActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/HomeEvent.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/HomeViewModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/signin/SignInActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/signin/SignInEvent.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/signin/SignInViewModel.kt
  android/festago/app/src/main/res/layout/activity_sign_in.xml
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/HomeViewModelTest.kt
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/signin/SignInViewModelTest.kt
Labels: AN, USER

#537 [AN/USER] feat: fcm 푸시 알림 구현 (#522)
  android/festago/app/src/main/AndroidManifest.xml
  android/festago/app/src/main/java/com/festago/festago/FestagoApplication.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/fcm/FcmMessageType.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/fcm/NotificationManager.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/fcm/TicketEntryService.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/service/TicketEntryService.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/HomeActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/util/PermissionUtil.kt
  android/festago/app/src/main/res/values/strings.xml
Labels: AN, USER

#553 [BE] fix: 컴포넌트 스캔 대상이 되는 빈의 @Profile 설정 수정 (#551)
  backend/src/main/java/com/festago/fcm/application/FCMNotificationEventListener.java
  backend/src/main/java/com/festago/fcm/config/FCMConfig.java
  backend/src/main/java/com/festago/student/infrastructure/GoogleMailClient.java
  backend/src/main/java/com/festago/student/infrastructure/MockMailClient.java
Labels: BE, FIX

#554 [AN/USER] refactor: 마이페이지 스크롤 적용, 레이아웃 리팩터링, 다크모드 적용(#547)
  android/festago/app/src/main/res/layout/fragment_my_page.xml
  android/festago/app/src/main/res/layout/item_ticket_history.xml
Labels: AN, USER, 리팩터링

#558 [AN/USER] feat: 학생 인증 화면 학교 도메인 디폴트 값 제거 (#550)
  android/festago/app/src/main/java/com/festago/festago/data/repository/SchoolDefaultRepository.kt
Labels: AN, USER

#560 [AN/USER] fix: 학교 선택, 학교 인증 화면 다크모드 대응(#556)
  android/festago/app/src/main/res/layout/activity_select_school.xml
  android/festago/app/src/main/res/layout/activity_student_verification.xml
  android/festago/app/src/main/res/layout/item_select_school.xml
  android/festago/app/src/main/res/values/style.xml
Labels: AN, USER

#566 [BE] FCMNotificationEventListener의 FCMChannel을 수정 (#565)
  backend/src/main/java/com/festago/entry/dto/event/EntryProcessEvent.java
  backend/src/main/java/com/festago/fcm/application/FCMNotificationEventListener.java
  backend/src/main/java/com/festago/fcm/domain/FCMChannel.java
Labels: BE, FIX

#570 [AN/USER] feat: 티켓 예매 디자인 수정 (#567)
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/bottomsheet/TicketReserveBottomSheetFragment.kt
  android/festago/app/src/main/res/layout/fragment_ticket_reserve_bottom_sheet.xml
  android/festago/app/src/main/res/layout/item_ticket_reserve_header.xml
  android/festago/app/src/main/res/values/strings.xml
Labels: AN, USER

#572 [AN/USER] feat: 페스타고 유저 앱 버전 변경 (#571)
  android/festago/app/build.gradle.kts
Labels: AN, USER

#513 [BE] refactor: 사용하지 않게된 클래스를 제거 (#512)
  backend/src/main/java/com/festago/auth/dto/KakaoAccessTokenResponse.java
  backend/src/main/java/com/festago/auth/dto/LoginMember.java
Labels: BE

#531 [BE] feat: 회원의 학생 인증 정보 조회 API 구현 (#496)
  backend/src/main/java/com/festago/presentation/StudentController.java
  backend/src/main/java/com/festago/student/application/StudentService.java
  backend/src/main/java/com/festago/student/dto/StudentResponse.java
  backend/src/main/java/com/festago/student/dto/StudentSchoolResponse.java
  backend/src/main/java/com/festago/student/repository/StudentRepository.java
  backend/src/test/java/com/festago/presentation/StudentControllerTest.java
  backend/src/test/java/com/festago/student/application/StudentServiceTest.java
  backend/src/test/java/com/festago/student/repository/StudentRepositoryTest.java
  backend/src/test/java/com/festago/support/StudentFixture.java
Labels: BE

#577 [ALL] 프로젝트 README 추가 (#552)
  README.md
Labels: ALL

#590 [AN/USER] refactor: ViewModel Test Code Dispatcher Rule 추가
  android/festago/app/src/test/java/com/festago/festago/presentation/rule/MainDispatcherRule.kt
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/HomeViewModelTest.kt
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListViewModelTest.kt
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/mypage/MyPageViewModelTest.kt
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListViewModelTest.kt
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/selectschool/SelectSchoolViewModelTest.kt
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/signin/SignInViewModelTest.kt
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/studentverification/StudentVerificationViewModelTest.kt
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryViewModelTest.kt
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/tickethistory/TicketHistoryViewModelTest.kt
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveViewModelTest.kt
Labels: AN, USER, 리팩터링, 테스트

#585 [AN/USER] feat: 버튼 더블 클릭 막기(#584)
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/studentverification/StudentVerificationActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/bottomsheet/TicketReserveBottomSheetFragment.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/util/SingleClickUtil.kt
  android/festago/app/src/main/res/layout/fragment_ticket_reserve_bottom_sheet.xml
  android/festago/app/src/main/res/layout/item_ticket_reserve.xml
Labels: AN, USER

#588 [AN/USER] feat: 홈 화면에서 뒤로가기 누르면 곧바로 종료되지 않는다.
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/HomeActivity.kt
  android/festago/app/src/main/res/values/strings.xml
Labels: AN, USER

#587 [AN/USER] feat: SingleLivedata 제거 (#586)
  android/festago/app/src/main/java/com/festago/festago/presentation/util/Event.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/util/MutableSingleLiveData.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/util/SingleLiveData.kt
Labels: AN, USER
