Repository woowacourse-teams/2023-festa-go, pull requests merged in 2023-08, with the labels that each got.

#163 [AN/USER] feat: 마이페이지 로그인 화면 작업(#158)
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageFragment.kt
  android/festago/app/src/main/res/drawable/bg_mypage_kakao_login.xml
  android/festago/app/src/main/res/drawable/ic_mypage_kakao_logo.xml
  android/festago/app/src/main/res/drawable/img_mypage_logo.xml
  android/festago/app/src/main/res/layout/fragment_my_page.xml
  android/festago/app/src/main/res/values/colors.xml
  android/festago/app/src/main/res/values/strings.xml
Labels: AN, USER

#166 [AN/USER] feat: 예매 티켓 리스트 화면 - API 연동(#100)
  android/festago/app/src/main/java/com/festago/festago/data/MockWeb.kt
  android/festago/app/src/main/java/com/festago/festago/data/dto/MemberTicketFestivalResponse.kt
  android/festago/app/src/main/java/com/festago/festago/data/dto/MemberTicketResponse.kt
  android/festago/app/src/main/java/com/festago/festago/data/dto/MemberTicketsResponse.kt
  android/festago/app/src/main/java/com/festago/festago/data/dto/StageResponse.kt
  android/festago/app/src/main/java/com/festago/festago/data/dto/TicketDto.kt
  android/festago/app/src/main/java/com/festago/festago/data/repository/TicketDefaultRepository.kt
  android/festago/app/src/main/java/com/festago/festago/data/service/TicketRetrofitService.kt
  android/festago/app/src/main/java/com/festago/festago/domain/model/MemberTicketFestival.kt
  android/festago/app/src/main/java/com/festago/festago/domain/model/Stage.kt
  android/festago/app/src/main/java/com/festago/festago/domain/model/Ticket.kt
  android/festago/app/src/main/java/com/festago/festago/domain/model/TicketCondition.kt
  android/festago/app/src/main/java/com/festago/festago/domain/model/TicketState.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/mapper/StageMapper.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/mapper/TicketMapper.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/mapper/TicketStateMapper.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/model/StageUiModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/model/TicketConditionUiModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/model/TicketUiModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/MainBinding.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryBindingAdapter.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/viewHolder/TicketReserveViewHolder.kt
  android/festago/app/src/main/res/layout/activity_ticket_entry.xml
  android/festago/app/src/main/res/layout/item_ticket_list.xml
  android/festago/app/src/test/java/com/festago/festago/presentation/fixture/TicketFixture.kt
  android/festago/app/src/test/java/com/festago/festago/presentation/ticketentry/TicketEntryViewModelTest.kt
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/MainViewModelTest.kt
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListViewModelTest.kt
Labels: AN, USER

#165 [BE] feat: 티켓 예매 API 구현 (#120)
  backend/src/main/java/com/festago/application/TicketService.java
  backend/src/main/java/com/festago/domain/Ticket.java
  backend/src/main/java/com/festago/domain/TicketAmount.java
  backend/src/main/java/com/festago/domain/TicketAmountRepository.java
  backend/src/main/java/com/festago/domain/TicketEntryTime.java
  backend/src/main/java/com/festago/dto/TicketingRequest.java
  backend/src/main/java/com/festago/dto/TicketingResponse.java
  backend/src/main/java/com/festago/exception/ErrorCode.java
  backend/src/test/java/com/festago/application/integration/TicketServiceIntegrationTest.java
  backend/src/test/resources/ticketing-test-data.sql
Labels: BE, USER

#169 [BE] feat: 축제 상세 정보 조회 Api 구현(#119)
  backend/src/main/java/com/festago/application/FestivalService.java
  backend/src/main/java/com/festago/domain/Festival.java
  backend/src/main/java/com/festago/domain/Stage.java
  backend/src/main/java/com/festago/domain/StageRepository.java
  backend/src/main/java/com/festago/domain/TicketAmount.java
  backend/src/main/java/com/festago/dto/FestivalDetailResponse.java
  backend/src/main/java/com/festago/dto/FestivalDetailStageResponse.java
  backend/src/main/java/com/festago/dto/FestivalDetailTicketResponse.java
  backend/src/main/java/com/festago/presentation/FestivalController.java
  backend/src/test/java/com/festago/application/FestivalServiceTest.java
  backend/src/test/java/com/festago/application/integration/FestivalServiceIntegrationTest.java
  backend/src/test/java/com/festago/presentation/FestivalControllerTest.java
Labels: BE, USER

#173 [BE] feat: 티켓 목록 조회 API와 예매 목록 조회 API 분리 (#79)
  backend/src/main/java/com/festago/application/MemberTicketService.java
  backend/src/main/java/com/festago/domain/MemberTicket.java
  backend/src/main/java/com/festago/dto/CurrentFestivalResponse.java
  backend/src/main/java/com/festago/dto/CurrentMemberTicketResponse.java
  backend/src/main/java/com/festago/dto/CurrentMemberTicketsResponse.java
  backend/src/main/java/com/festago/dto/CurrentStageResponse.java
  backend/src/main/java/com/festago/dto/MemberTicketResponse.java
  backend/src/main/java/com/festago/dto/MemberTicketsResponse.java
  backend/src/main/java/com/festago/presentation/MemberTicketController.java
  backend/src/test/java/com/festago/application/MemberTicketServiceTest.java
  backend/src/test/java/com/festago/domain/MemberTicketTest.java
  backend/src/test/java/com/festago/presentation/MemberTicketControllerTest.java
Labels: BE, USER

#168 [AN/USER] feat: 축제 리스트 화면 - API 연동(#96)
  android/festago/app/src/main/java/com/festago/festago/data/MockWeb.kt
  android/festago/app/src/main/java/com/festago/festago/data/RetrofitClient.kt
  android/festago/app/src/main/java/com/festago/festago/data/dto/FestivalResponse.kt
  android/festago/app/src/main/java/com/festago/festago/data/dto/FestivalsResponse.kt
  android/festago/app/src/main/java/com/festago/festago/data/repository/FestivalDefaultRepository.kt
  android/festago/app/src/main/java/com/festago/festago/data/service/FestivalRetrofitService.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalItemViewHolder.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListFragment.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListUiState.kt
  android/festago/app/src/main/res/layout/fragment_festival_list.xml
  android/festago/app/src/main/res/layout/item_festival_list.xml
  android/festago/app/src/main/res/values/strings.xml
Labels: AN, USER

#180 [AN/STAFF] feat: 티켓 확인 api 변동 사항 반영(#178)
  android/festago-staff/app/src/main/java/com/festago/festagostaff/data/service/TicketRetrofitService.kt
Labels: AN, STAFF

#186 [BE] fix: 티켓 생성 요청의 개수 필드 이름 수정 (#185)
  backend/src/main/resources/static/admin.js
  backend/src/main/resources/templates/admin.html
Labels: BE, ASAP, FIX

#177 [AN/USER] feat: 티켓 예매 화면 - API 연동(#91)
  android/festago/app/src/androidTest/java/com/festago/festago/presentation/ui/reservationcomplete/ReservationCompleteActivityTest.kt
  android/festago/app/src/main/java/com/festago/festago/data/RetrofitClient.kt
  android/festago/app/src/main/java/com/festago/festago/data/dto/ReservationFestivalResponse.kt
  android/festago/app/src/main/java/com/festago/festago/data/dto/ReservationStageResponse.kt
  android/festago/app/src/main/java/com/festago/festago/data/dto/ReservationTicketResponse.kt
  android/festago/app/src/main/java/com/festago/festago/data/dto/ReservationTicketsResponse.kt
  android/festago/app/src/main/java/com/festago/festago/data/dto/ReservedTicketRequest.kt
  android/festago/app/src/main/java/com/festago/festago/data/dto/ReservedTicketResponse.kt
  android/festago/app/src/main/java/com/festago/festago/data/repository/ReservationDefaultRepository.kt
  android/festago/app/src/main/java/com/festago/festago/data/service/ReservationRetrofitService.kt
  android/festago/app/src/main/java/com/festago/festago/domain/model/Reservation.kt
  android/festago/app/src/main/java/com/festago/festago/domain/model/ReservationTicket.kt
  android/festago/app/src/main/java/com/festago/festago/domain/model/ReservedTicket.kt
  android/festago/app/src/main/java/com/festago/festago/domain/repository/ReservationRepository.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/mapper/ReservationTicketMapper.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/mapper/ReservedTicketMapper.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/model/ReservationTicketUiModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/model/ReservationUiModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/model/ReservedTicketUiModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/customview/OkDialogFragment.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/reservationcomplete/ReservationCompleteActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveEvent.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveViewModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/bottomsheet/TicketReserveBottomSheetAdapter.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/bottomsheet/TicketReserveBottomSheetCallback.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/bottomsheet/TicketReserveBottomSheetFragment.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/bottomsheet/TicketReserveBottomViewHolder.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/util/ParcelizeUtil.kt
  android/festago/app/src/main/res/layout/activity_reservation_complete.xml
  android/festago/app/src/main/res/layout/fragment_ticket_reserve_bottom_sheet.xml
  android/festago/app/src/test/java/com/festago/festago/data/repository/ReservationRetrofitServiceTest.kt
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveViewModelTest.kt
Labels: AN, USER

#188 [BE] faet: 축제 조회 DTO의 공연의 시작 시간 필드 이름 수정 (#187)
  backend/src/main/java/com/festago/dto/FestivalDetailStageResponse.java
Labels: BE, FIX

#201 [BE] feat: 티켓 예매 Api 구현 (#198)
  backend/src/main/java/com/festago/presentation/MemberTicketController.java
  backend/src/test/java/com/festago/presentation/MemberTicketControllerTest.java
Labels: BE, ASAP

#195 [BE] test: 일부 누락된 테스트 코드 작성 (#193)
  backend/src/main/java/com/festago/config/DemoDataInitConfig.java
  backend/src/main/java/com/festago/demo/DemoController.java
  backend/src/test/java/com/festago/application/EntryServiceTest.java
  backend/src/test/java/com/festago/application/StageServiceTest.java
  backend/src/test/java/com/festago/domain/EntryCodeTest.java
  backend/src/test/java/com/festago/domain/TicketTest.java
Labels: BE, 리팩터링, 테스트

#184 [BE] feat: 에러 로깅 추가 (#126)
  backend/.gitignore
  backend/src/main/java/com/festago/presentation/GlobalExceptionHandler.java
  backend/src/main/resources/console-appender.xml
  backend/src/main/resources/logback-spring.xml
  backend/src/main/resources/logs/common/file-error-appender.xml
  backend/src/main/resources/logs/common/file-info-appender.xml
  backend/src/main/resources/logs/common/file-warn-appender.xml
  backend/src/main/resources/logs/error/file-error-appender.xml
  backend/src/main/resources/logs/error/file-info-appender.xml
  backend/src/main/resources/logs/error/file-warn-appender.xml
Labels: BE

#205 [BE] 축제 상세정보 조회시 무대의 ticket이 없을시 무대가 조회되지 않는 버그 수정 (#204)
  backend/src/main/java/com/festago/domain/StageRepository.java
  backend/src/test/java/com/festago/domain/StageRepositoryTest.java
Labels: BE, FIX

#197 [AN/USER] 디자인 세부 내용 수정 (#196)
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/bottomsheet/TicketReserveBottomSheetFragment.kt
  android/festago/app/src/main/res/layout/fragment_ticket_reserve_bottom_sheet.xml
  android/festago/app/src/main/res/layout/item_ticket_reserve.xml
  android/festago/app/src/main/res/values/style.xml
Labels: AN, USER

#202 [AN/USER] delete: 사용하지 않는 main 화면 삭제 (#156)
  android/festago/app/src/androidTest/java/com/festago/festago/ExampleInstrumentedTest.kt
  android/festago/app/src/main/AndroidManifest.xml
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/MainActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/MainBinding.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/MainEvent.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/MainViewModel.kt
  android/festago/app/src/main/res/layout/activity_main.xml
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/MainViewModelTest.kt
Labels: AN, USER

#210 [BE] refactor: 멤버티켓 조회 DTO 통일 (#209)
  backend/src/main/java/com/festago/application/MemberTicketService.java
  backend/src/main/java/com/festago/dto/CurrentFestivalResponse.java
  backend/src/main/java/com/festago/dto/CurrentMemberTicketResponse.java
  backend/src/main/java/com/festago/dto/CurrentMemberTicketsResponse.java
  backend/src/main/java/com/festago/dto/CurrentStageResponse.java
  backend/src/main/java/com/festago/dto/MemberTicketResponse.java
  backend/src/main/java/com/festago/presentation/MemberTicketController.java
  backend/src/test/java/com/festago/application/MemberTicketServiceTest.java
  backend/src/test/java/com/festago/presentation/MemberTicketControllerTest.java
Labels: BE, 리팩터링

#211 [AN/USER] 유저 전용 앱 Crashlytics 기능 추가 (#208)
  android/festago/app/build.gradle.kts
  android/festago/build.gradle.kts
Labels: AN, USER

#214 [BE] refactor: 멤버티켓 조회 응답 DTO 네이밍 수정 (#213)
  backend/src/main/java/com/festago/dto/MemberTicketResponse.java
Labels: BE, 리팩터링

#217 [BE] refactor: 스태프 티켓 검사 url 수정 (#215)
  backend/src/main/java/com/festago/presentation/StaffMemberTicketController.java
  backend/src/test/java/com/festago/presentation/StaffMemberTicketControllerTest.java
Labels: BE, 리팩터링

#191 [BE] feat: 어드민 페이지에 현재 존재하는 축제, 공연, 티켓의 정보를 포함한다 (#190)
  backend/src/main/java/com/festago/application/AdminService.java
  backend/src/main/java/com/festago/dto/AdminFestivalResponse.java
  backend/src/main/java/com/festago/dto/AdminResponse.java
  backend/src/main/java/com/festago/dto/AdminStageResponse.java
  backend/src/main/java/com/festago/dto/AdminTicketResponse.java
  backend/src/main/java/com/festago/presentation/AdminController.java
  backend/src/main/resources/static/admin.js
  backend/src/main/resources/static/style.css
  backend/src/main/resources/templates/admin.html
  backend/src/test/java/com/festago/presentation/AdminControllerTest.java
Labels: BE, ADMIN

#218 [BE] feat: info log 는 stack trace 를 포함하지 않는다 (#216)
  backend/src/main/java/com/festago/presentation/GlobalExceptionHandler.java
Labels: BE, 리팩터링

#224 [AN/USER] 축제 예매 화면 새로고침 기능 (#222)
  android/festago/app/build.gradle.kts
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveViewModel.kt
  android/festago/app/src/main/res/layout/activity_ticket_reserve.xml
Labels: AN, USER

#219 [AN/USER] 유저 어플 레트로핏 에러처리 (#212)
  android/festago/app/src/main/java/com/festago/festago/data/repository/FestivalDefaultRepository.kt
  android/festago/app/src/main/java/com/festago/festago/data/repository/ReservationDefaultRepository.kt
  android/festago/app/src/main/java/com/festago/festago/data/repository/TicketDefaultRepository.kt
Labels: AN, USER

#221 [AN/USER] 축제 예매 화면 오픈시간 전에 버튼 비활성화 (#220)
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/viewHolder/TicketReserveViewHolder.kt
  android/festago/app/src/main/res/layout/item_ticket_reserve.xml
  android/festago/app/src/main/res/values/strings.xml
Labels: AN, USER

#223 [AN/USER] feat: 티켓 목록 API 수정 및 새로고침 (#203)
  android/festago/app/src/main/java/com/festago/festago/data/dto/MemberTicketResponse.kt
  android/festago/app/src/main/java/com/festago/festago/data/service/TicketRetrofitService.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListFragment.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListFragment.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryActivity.kt
Labels: AN, USER

#229 [AN/USER] 페스티벌 축제 화면 새로고침 기능 추가 (#228)
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListFragment.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListViewModel.kt
  android/festago/app/src/main/res/layout/fragment_festival_list.xml
Labels: AN, USER

#231 [AN/USER] feat: 티켓 목록 새로고침(#227)
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListFragment.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListViewModel.kt
  android/festago/app/src/main/res/layout/fragment_ticket_list.xml
  android/festago/app/src/main/res/layout/item_ticket_list.xml
Labels: AN, USER

#237 [BE] chore: Appender 상대 경로, 로그 저장 위치 변경 (#236)
  backend/src/main/resources/logback-spring.xml
  backend/src/main/resources/logs/common/file-error-appender.xml
  backend/src/main/resources/logs/common/file-info-appender.xml
  backend/src/main/resources/logs/common/file-warn-appender.xml
  backend/src/main/resources/logs/error/file-error-appender.xml
  backend/src/main/resources/logs/error/file-info-appender.xml
  backend/src/main/resources/logs/error/file-warn-appender.xml
Labels: BE, FIX

#235 [AN/USER] fix: 티켓 예매 새로고침 수정 (#234)
  android/festago/app/src/main/java/com/festago/festago/presentation/mapper/ReservationStageMapper.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/model/ReservationStageUiModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/viewHolder/TicketReserveViewHolder.kt
Labels: AN, USER

#238 [AN/USER] 유저앱 화면 바텀 네비게이션 적용 (#230)
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/HomeActivity.kt
  android/festago/app/src/main/res/drawable/ic_festago_coupon.xml
  android/festago/app/src/main/res/drawable/menu_selector_color.xml
  android/festago/app/src/main/res/layout/activity_home.xml
  android/festago/app/src/main/res/menu/menu_bottom_navigation.xml
Labels: AN, USER

#241 [BE] fix: 실패하는 입장 가능 여부 검사 테스트 수정 (#240)
  backend/src/test/java/com/festago/domain/MemberTicketTest.java
Labels: BE, ASAP, FIX

#175 [BE] feat: 카카오 인증을 통한 OAuth 회원가입 및 로그인 기능 추가 (#111)
  backend/src/main/java/com/festago/auth/application/AuthService.java
  backend/src/main/java/com/festago/auth/config/AuthConfig.java
  backend/src/main/java/com/festago/auth/domain/AuthProvider.java
  backend/src/main/java/com/festago/auth/domain/OAuth2Client.java
  backend/src/main/java/com/festago/auth/domain/OAuth2Clients.java
  backend/src/main/java/com/festago/auth/domain/SocialType.java
  backend/src/main/java/com/festago/auth/domain/UserInfo.java
  backend/src/main/java/com/festago/auth/dto/KakaoAccessTokenResponse.java
  backend/src/main/java/com/festago/auth/dto/KakaoUserInfo.java
  backend/src/main/java/com/festago/auth/dto/LoginRequest.java
  backend/src/main/java/com/festago/auth/dto/LoginResponse.java
  backend/src/main/java/com/festago/auth/infrastructure/FestagoOAuth2Client.java
  backend/src/main/java/com/festago/auth/infrastructure/JwtAuthProvider.java
  backend/src/main/java/com/festago/auth/infrastructure/KakaoOAuth2AccessTokenClient.java
  backend/src/main/java/com/festago/auth/infrastructure/KakaoOAuth2AccessTokenErrorHandler.java
  backend/src/main/java/com/festago/auth/infrastructure/KakaoOAuth2Client.java
  backend/src/main/java/com/festago/auth/infrastructure/KakaoOAuth2UserInfoClient.java
  backend/src/main/java/com/festago/auth/infrastructure/KakaoOAuth2UserInfoErrorHandler.java
  backend/src/main/java/com/festago/auth/presentation/AuthController.java
  backend/src/main/java/com/festago/domain/Member.java
  backend/src/main/java/com/festago/domain/MemberRepository.java
  backend/src/main/java/com/festago/exception/ErrorCode.java
  backend/src/main/resources/application-local.yml
  backend/src/test/java/com/festago/auth/domain/OAuth2ClientsTest.java
  backend/src/test/java/com/festago/auth/infrastructure/JwtAuthProviderTest.java
  backend/src/test/java/com/festago/auth/infrastructure/KakaoOAuth2AccessTokenClientTest.java
  backend/src/test/java/com/festago/auth/infrastructure/KakaoOAuth2UserInfoClientTest.java
  backend/src/test/java/com/festago/auth/presentation/AuthControllerTest.java
  backend/src/test/java/com/festago/domain/MemberRepositoryTest.java
  backend/src/test/java/com/festago/support/MemberFixture.java
  backend/src/test/resources/application-test.yml
Labels: BE

#243 [BE] chore: 로그 파일 저장 위치를 실행 환경 별로 분리한다 (#242)
  .gitignore
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/console-appender.xml
  backend/src/main/resources/logback-spring.xml
  backend/src/main/resources/logs/common/file-error-appender.xml
  backend/src/main/resources/logs/common/file-info-appender.xml
  backend/src/main/resources/logs/common/file-warn-appender.xml
  backend/src/main/resources/logs/error/file-error-appender.xml
  backend/src/main/resources/logs/error/file-info-appender.xml
  backend/src/main/resources/logs/error/file-warn-appender.xml
Labels: BE

#275 [AN/USER]feat: xml 색상 다크모드 대응 (#239)
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/bottomsheet/TicketReserveBottomSheetFragment.kt
  android/festago/app/src/main/res/drawable/bg_custom_dialog.xml
  android/festago/app/src/main/res/drawable/bg_ticket_reserve_bottom_sheet.xml
  android/festago/app/src/main/res/drawable/bg_ticket_reserve_bottom_sheet_item.xml
  android/festago/app/src/main/res/drawable/btn_festa_normal.xml
  android/festago/app/src/main/res/layout/activity_home.xml
  android/festago/app/src/main/res/layout/fragment_ticket_reserve_bottom_sheet.xml
  android/festago/app/src/main/res/layout/item_festival_list.xml
  android/festago/app/src/main/res/layout/item_ticket_reserve_bottom_sheet.xml
  android/festago/app/src/main/res/values-night/colors.xml
  android/festago/app/src/main/res/values/style.xml
Labels: AN, USER

#276 [AN/USER] feat: 카카오 로그인 기본 세팅 (#200)
  android/festago/app/build.gradle.kts
  android/festago/app/proguard-rules.pro
  android/festago/app/src/main/AndroidManifest.xml
  android/festago/app/src/main/java/com/festago/festago/FestagoApplication.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageFragment.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/util/UserApiClientExt.kt
  android/festago/settings.gradle.kts
Labels: AN, USER

#271 [BE] feat: 회원 soft delete 탈퇴 기능 구현 (#268)
  backend/src/main/java/com/festago/domain/Member.java
  backend/src/test/java/com/festago/application/integration/TicketServiceIntegrationTest.java
  backend/src/test/java/com/festago/auth/application/integration/AuthServiceIntegrationTest.java
  backend/src/test/java/com/festago/domain/MemberRepositoryTest.java
  backend/src/test/java/com/festago/domain/MemberTicketRepositoryTest.java
  backend/src/test/java/com/festago/support/DatabaseCleaner.java
  backend/src/test/java/com/festago/support/DatabaseClearExtension.java
  backend/src/test/resources/application-test.yml
Labels: BE

#272 [BE] feat: 로그인한 유저 인증/인가 처리 (#262)
  backend/src/main/java/com/festago/application/MemberTicketService.java
  backend/src/main/java/com/festago/auth/application/AuthService.java
  backend/src/main/java/com/festago/auth/config/AuthConfig.java
  backend/src/main/java/com/festago/auth/config/LoginConfig.java
  backend/src/main/java/com/festago/auth/domain/AuthExtractor.java
  backend/src/main/java/com/festago/auth/domain/AuthPayload.java
  backend/src/main/java/com/festago/auth/domain/AuthProvider.java
  backend/src/main/java/com/festago/auth/domain/Login.java
  backend/src/main/java/com/festago/auth/dto/LoginMember.java
  backend/src/main/java/com/festago/auth/infrastructure/JwtAuthExtractor.java
  backend/src/main/java/com/festago/auth/infrastructure/JwtAuthProvider.java
  backend/src/main/java/com/festago/auth/presentation/LoginMemberResolver.java
  backend/src/main/java/com/festago/domain/Member.java
  backend/src/main/java/com/festago/exception/ErrorCode.java
  backend/src/main/java/com/festago/exception/UnauthorizedException.java
  backend/src/main/java/com/festago/presentation/GlobalExceptionHandler.java
  backend/src/main/java/com/festago/presentation/MemberTicketController.java
  backend/src/test/java/com/festago/application/MemberTicketServiceTest.java
  backend/src/test/java/com/festago/auth/infrastructure/JwtAuthExtractorTest.java
  backend/src/test/java/com/festago/auth/infrastructure/JwtAuthProviderTest.java
  backend/src/test/java/com/festago/auth/presentation/AuthControllerTest.java
  backend/src/test/java/com/festago/auth/presentation/LoginMemberResolverTest.java
  backend/src/test/java/com/festago/infrastructure/JwtEntryCodeExtractorTest.java
  backend/src/test/java/com/festago/presentation/AdminControllerTest.java
  backend/src/test/java/com/festago/presentation/FestivalControllerTest.java
  backend/src/test/java/com/festago/presentation/MemberTicketControllerTest.java
  backend/src/test/java/com/festago/presentation/StaffMemberTicketControllerTest.java
  backend/src/test/java/com/festago/presentation/StageControllerTest.java
  backend/src/test/java/com/festago/support/TestConfig.java
Labels: BE, USER

#266 [BE] feat: JpaAuditing 적용 (#253)
  backend/src/main/java/com/festago/config/JpaAuditingConfig.java
  backend/src/main/java/com/festago/domain/BaseTimeEntity.java
  backend/src/main/java/com/festago/domain/Festival.java
  backend/src/main/java/com/festago/domain/Member.java
  backend/src/main/java/com/festago/domain/MemberTicket.java
  backend/src/main/java/com/festago/domain/Stage.java
  backend/src/main/java/com/festago/domain/Ticket.java
  backend/src/main/java/com/festago/domain/TicketAmount.java
  backend/src/main/java/com/festago/domain/TicketEntryTime.java
Labels: BE

#284 [BE] feat: 소셜 로그인을 인가 코드에서 엑세스 토큰을 사용하도록 변경 (#274)
  backend/src/main/java/com/festago/auth/application/AuthService.java
  backend/src/main/java/com/festago/auth/domain/OAuth2Client.java
  backend/src/main/java/com/festago/auth/dto/LoginRequest.java
  backend/src/main/java/com/festago/auth/infrastructure/FestagoOAuth2Client.java
  backend/src/main/java/com/festago/auth/infrastructure/KakaoOAuth2AccessTokenClient.java
  backend/src/main/java/com/festago/auth/infrastructure/KakaoOAuth2AccessTokenErrorHandler.java
  backend/src/main/java/com/festago/auth/infrastructure/KakaoOAuth2Client.java
  backend/src/main/java/com/festago/auth/presentation/AuthController.java
  backend/src/test/java/com/festago/auth/domain/OAuth2ClientsTest.java
  backend/src/test/java/com/festago/auth/infrastructure/KakaoOAuth2AccessTokenClientTest.java
  backend/src/test/java/com/festago/auth/presentation/AuthControllerTest.java
  backend/src/test/resources/application-test.yml
Labels: BE, USER

#245 [BE] feat: 시간 관련 도메인 요구사항 적용 (#244)
  backend/src/main/java/com/festago/application/FestivalService.java
  backend/src/main/java/com/festago/application/TicketService.java
  backend/src/main/java/com/festago/domain/Festival.java
  backend/src/main/java/com/festago/domain/Ticket.java
  backend/src/main/java/com/festago/exception/ErrorCode.java
  backend/src/test/java/com/festago/application/FestivalServiceTest.java
  backend/src/test/java/com/festago/application/TicketServiceTest.java
  backend/src/test/java/com/festago/application/integration/FestivalServiceIntegrationTest.java
  backend/src/test/java/com/festago/application/integration/TicketServiceIntegrationTest.java
  backend/src/test/java/com/festago/domain/FestivalTest.java
  backend/src/test/java/com/festago/domain/TicketTest.java
Labels: BE

#269 [BE] feat: 마이페이지 전용 API 추가 (#267)
  backend/src/main/java/com/festago/application/MemberService.java
  backend/src/main/java/com/festago/application/MemberTicketService.java
  backend/src/main/java/com/festago/domain/MemberTicketRepository.java
  backend/src/main/java/com/festago/dto/MemberProfileResponse.java
  backend/src/main/java/com/festago/dto/MemberTicketResponse.java
  backend/src/main/java/com/festago/presentation/MemberController.java
  backend/src/main/java/com/festago/presentation/MemberTicketController.java
  backend/src/test/java/com/festago/application/MemberTicketServiceTest.java
  backend/src/test/java/com/festago/application/integration/MemberTicketIntegrationTest.java
  backend/src/test/java/com/festago/domain/MemberTicketRepositoryTest.java
  backend/src/test/java/com/festago/presentation/MemberControllerTest.java
  backend/src/test/java/com/festago/presentation/MemberTicketControllerTest.java
Labels: BE

#281 [BE] refactor: EnumType String 변경 (#249)
  backend/src/main/java/com/festago/domain/MemberTicket.java
Labels: BE, 리팩터링

#290 [AN/USER] feat: 로그인 후 마이페이지 구현 (#199)
  android/festago/app/src/main/java/com/festago/festago/data/RetrofitClient.kt
  android/festago/app/src/main/java/com/festago/festago/data/dto/UserProfileResponse.kt
  android/festago/app/src/main/java/com/festago/festago/data/repository/TicketDefaultRepository.kt
  android/festago/app/src/main/java/com/festago/festago/data/repository/UserDefaultRepository.kt
  android/festago/app/src/main/java/com/festago/festago/data/service/TicketRetrofitService.kt
  android/festago/app/src/main/java/com/festago/festago/data/service/UserRetrofitService.kt
  android/festago/app/src/main/java/com/festago/festago/domain/model/UserProfile.kt
  android/festago/app/src/main/java/com/festago/festago/domain/repository/TicketRepository.kt
  android/festago/app/src/main/java/com/festago/festago/domain/repository/UserRepository.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/mapper/UserProfileMapper.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/model/StageUiModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/model/TicketUiModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/model/UserProfileUiModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/BindingAdapter.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageEvent.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageFragment.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageUiState.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageViewModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListFragment.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListViewModel.kt
  android/festago/app/src/main/res/layout/fragment_my_page.xml
  android/festago/app/src/main/res/values/strings.xml
  android/festago/app/src/main/res/values/style.xml
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/mypage/MyPageViewModelTest.kt
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListViewModelTest.kt
Labels: AN, USER

#283 [BE] feat: 신규, 기존 회원 구분 기능 추가 (#179)
  backend/src/main/java/com/festago/auth/application/AuthService.java
  backend/src/main/java/com/festago/auth/dto/LoginResponse.java
  backend/src/test/java/com/festago/auth/application/AuthServiceTest.java
  backend/src/test/java/com/festago/auth/presentation/AuthControllerTest.java
Labels: BE

#292 [BE] refactor: 불필요한 oauth2 redirect용 API 삭제 (#291)
  backend/src/main/java/com/festago/auth/presentation/AuthController.java
  backend/src/test/java/com/festago/auth/presentation/AuthControllerTest.java
Labels: BE, 리팩터링

#287 [BE] refactor: 티켓 목록 API에서 입장 시간 이전 티켓 모두 활성화되도록 수정 (#265)
  backend/src/main/java/com/festago/application/MemberTicketService.java
  backend/src/main/java/com/festago/domain/MemberTicket.java
  backend/src/test/java/com/festago/application/MemberTicketServiceTest.java
  backend/src/test/java/com/festago/domain/MemberTicketTest.java
Labels: BE, 리팩터링

#286 [BE] refactor: DatabaseCleaner의 스프링 빈 등록을 제외하고, ExtendWith에만 등록될 때 작동하게 변경 (#285)
  backend/src/test/java/com/festago/support/DatabaseCleaner.java
  backend/src/test/java/com/festago/support/DatabaseClearExtension.java
Labels: BE, 리팩터링

#282 [BE] feat: EntryCode의 offset에 검증 로직 추가 (#194)
  backend/src/main/java/com/festago/domain/EntryCode.java
  backend/src/main/java/com/festago/exception/ErrorCode.java
  backend/src/test/java/com/festago/domain/EntryCodeTest.java
Labels: BE

#294 [AN/USER] feat: 로그인 구현 (#277)
  android/festago/app/build.gradle.kts
  android/festago/app/src/main/AndroidManifest.xml
  android/festago/app/src/main/java/com/festago/festago/FestagoApplication.kt
  android/festago/app/src/main/java/com/festago/festago/data/AuthInterceptor.kt
  android/festago/app/src/main/java/com/festago/festago/data/RetrofitClient.kt
  android/festago/app/src/main/java/com/festago/festago/data/datasource/AuthDataSource.kt
  android/festago/app/src/main/java/com/festago/festago/data/datasource/SharedPrefAuthDataSource.kt
  android/festago/app/src/main/java/com/festago/festago/data/dto/OauthRequest.kt
  android/festago/app/src/main/java/com/festago/festago/data/dto/OauthTokenResponse.kt
  android/festago/app/src/main/java/com/festago/festago/data/repository/AuthDefaultRepository.kt
  android/festago/app/src/main/java/com/festago/festago/data/service/AuthRetrofitService.kt
  android/festago/app/src/main/java/com/festago/festago/domain/model/Token.kt
  android/festago/app/src/main/java/com/festago/festago/domain/repository/AuthRepository.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/HomeActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListFragment.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageFragment.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListFragment.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/signin/SignInActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/signin/SignInEvent.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/signin/SignInViewModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/util/UserApiClientExt.kt
  android/festago/app/src/main/res/layout/activity_sign_in.xml
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/signin/SignInViewModelTest.kt
Labels: AN, USER

#300 [BE] fix: 회원 프로필을 제대로 못받아오는 문제를 수정 (#299)
  backend/src/main/java/com/festago/presentation/MemberController.java
  backend/src/test/java/com/festago/presentation/MemberControllerTest.java
Labels: BE, FIX

#306 [AN/USER] fix: 로그인 오류 수정 (#304)
  android/festago/app/src/main/java/com/festago/festago/data/RetrofitClient.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/signin/SignInActivity.kt
Labels: AN, USER, FIX

#309 [AN/USER] feat: 마이페이지에 로그인, 로그아웃 적용(#293)
  android/festago/app/src/main/java/com/festago/festago/data/RetrofitClient.kt
  android/festago/app/src/main/java/com/festago/festago/data/dto/OauthTokenResponse.kt
  android/festago/app/src/main/java/com/festago/festago/data/dto/UserProfileResponse.kt
  android/festago/app/src/main/java/com/festago/festago/data/repository/AuthDefaultRepository.kt
  android/festago/app/src/main/java/com/festago/festago/data/service/UserRetrofitService.kt
  android/festago/app/src/main/java/com/festago/festago/domain/repository/AuthRepository.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/HomeActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageEvent.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageFragment.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageViewModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/signin/SignInActivity.kt
  android/festago/app/src/main/res/layout/fragment_my_page.xml
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/mypage/MyPageViewModelTest.kt
Labels: AN, USER

#308 [AN/USER] refactor: 싱글톤 패턴 리팩터링 (#305)
  android/festago/app/src/main/java/com/festago/festago/FestagoApplication.kt
  android/festago/app/src/main/java/com/festago/festago/analytics/FirebaseAnalyticsHelper.kt
  android/festago/app/src/main/java/com/festago/festago/data/AuthInterceptor.kt
  android/festago/app/src/main/java/com/festago/festago/data/RetrofitClient.kt
  android/festago/app/src/main/java/com/festago/festago/data/datasource/AuthLocalDataSource.kt
  android/festago/app/src/main/java/com/festago/festago/data/retrofit/AuthInterceptor.kt
  android/festago/app/src/main/java/com/festago/festago/data/retrofit/AuthRetrofitClient.kt
  android/festago/app/src/main/java/com/festago/festago/data/retrofit/NormalRetrofitClient.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListFragment.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageFragment.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListFragment.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/signin/SignInActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveActivity.kt
Labels: AN, USER, 리팩터링

#318 [AN/USER] feat: PR시에 안드로이드 CI 적용 (#23)
  .github/workflows/ci-user-aos.yml
  android/festago/app/build.gradle.kts
  android/festago/app/src/main/AndroidManifest.xml
  android/festago/app/src/main/java/com/festago/festago/data/MockWeb.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/mapper/TicketStateMapper.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/signin/SignInActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/bottomsheet/TicketReserveBottomSheetFragment.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/util/ParcelizeUtil.kt
  android/festago/app/src/test/java/com/festago/festago/data/repository/ReservationRetrofitServiceTest.kt
Labels: AN, USER, 비개발

#319 [AN/USER] feat: 티켓 목록 새로고침 해결 (#314)
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListFragment.kt
  android/festago/app/src/main/res/layout/fragment_ticket_list.xml
  android/festago/app/src/main/res/values/strings.xml
Labels: AN, USER

#298 [BE] feat: 회원 탈퇴 API 구현 (#295)
  backend/src/main/java/com/festago/auth/application/AuthService.java
  backend/src/main/java/com/festago/auth/presentation/AuthController.java
  backend/src/test/java/com/festago/auth/application/AuthServiceTest.java
  backend/src/test/java/com/festago/auth/application/integration/AuthServiceIntegrationTest.java
Labels: BE

#297 [BE] refactor: Oauth2 카카오 서버의 4xx에러 발생할 경우 BadRequestException으로 수정 (#296)
  backend/src/main/java/com/festago/auth/infrastructure/FestagoOAuth2Client.java
  backend/src/main/java/com/festago/auth/infrastructure/KakaoOAuth2UserInfoErrorHandler.java
  backend/src/main/java/com/festago/exception/ErrorCode.java
  backend/src/test/java/com/festago/auth/infrastructure/KakaoOAuth2UserInfoClientTest.java
Labels: BE, 리팩터링

#303 [BE] feat: profileImage 기본값 추가 (#301)
  backend/src/main/java/com/festago/auth/dto/KakaoUserInfo.java
Labels: BE

#320 [AN/USER] feat: 홈 화면에서 로그인하지 않은 경우 처리 (#317)
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/HomeActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/HomeEvent.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/HomeViewModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageFragment.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/signin/SignInActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/signin/SignInViewModel.kt
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/HomeViewModelTest.kt
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/signin/SignInViewModelTest.kt
Labels: AN, USER

#321 [AN/USER] feat: 공연 목록 화면에서 로그인하지 않은 경우 처리(#315)
  android/festago/app/src/main/java/com/festago/festago/presentation/mapper/ReservationStageMapper.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/model/TicketReserveItemUiModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveEvent.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveUiState.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveViewModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/adapter/TicketReserveAdapter.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/viewHolder/TicketReserveViewHolder.kt
  android/festago/app/src/main/res/layout/item_ticket_reserve.xml
  android/festago/app/src/main/res/values/strings.xml
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveViewModelTest.kt
Labels: AN, USER

#322 [AN/USER] feat: 마이페이지에서 티켓 히스토리 목록 추가 (#273)
  android/festago/app/src/main/AndroidManifest.xml
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/BindingAdapter.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageEvent.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageFragment.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageViewModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/tickethistory/TicketHistoryActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/tickethistory/TicketHistoryAdapter.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/tickethistory/TicketHistoryUiState.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/tickethistory/TicketHistoryViewHolder.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/tickethistory/TicketHistoryViewModel.kt
  android/festago/app/src/main/res/layout/activity_ticket_history.xml
  android/festago/app/src/main/res/layout/fragment_my_page.xml
  android/festago/app/src/main/res/layout/item_ticket_history.xml
  android/festago/app/src/main/res/layout/item_ticket_list.xml
  android/festago/app/src/main/res/values/strings.xml
  android/festago/app/src/main/res/xml/activity_ticket_history_scene.xml
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/tickethistory/TicketHistoryViewModelTest.kt
Labels: AN, USER

#333 [AN/USER] feat: 예매 목록, 마이페이지의 티켓 카드뷰 수정 (#323)
  android/festago/app/src/main/res/layout/activity_ticket_history.xml
  android/festago/app/src/main/res/layout/fragment_my_page.xml
  android/festago/app/src/main/res/layout/item_ticket_history.xml
Labels: AN, USER

#327 [AN/USER] feat: 마이페이지 회원 탈퇴 기능(#310)
  android/festago/app/src/main/java/com/festago/festago/data/dto/UserProfileResponse.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageEvent.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageFragment.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageViewModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/signin/SignInActivity.kt
  android/festago/app/src/main/res/layout/fragment_my_page.xml
  android/festago/app/src/main/res/values/strings.xml
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/mypage/MyPageViewModelTest.kt
Labels: AN, USER

#336 [AN/USER] 유저 어플 Auth 토큰 만료 후 재발급 (#324)
  android/festago/app/src/main/java/com/festago/festago/FestagoApplication.kt
  android/festago/app/src/main/java/com/festago/festago/data/repository/AuthDefaultRepository.kt
  android/festago/app/src/main/java/com/festago/festago/data/repository/FestivalDefaultRepository.kt
  android/festago/app/src/main/java/com/festago/festago/data/repository/ReservationTicketDefaultRepository.kt
  android/festago/app/src/main/java/com/festago/festago/data/repository/TicketDefaultRepository.kt
  android/festago/app/src/main/java/com/festago/festago/data/repository/UserDefaultRepository.kt
  android/festago/app/src/main/java/com/festago/festago/data/retrofit/AuthInterceptor.kt
  android/festago/app/src/main/java/com/festago/festago/data/retrofit/AuthRetrofitClient.kt
  android/festago/app/src/main/java/com/festago/festago/data/util/ResponseExt.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/HomeActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageFragment.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageViewModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListFragment.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/signin/SignInActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/signin/SignInViewModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/tickethistory/TicketHistoryActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveActivity.kt
Labels: AN, USER

#338 [AN/USER] feat: 티켓 목록 새로고침 시 목록 업데이트 (#337)
  android/festago/app/src/main/java/com/festago/festago/presentation/mapper/TicketMapper.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/model/MemberTicketUiModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListAdapter.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListItemViewHolder.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListUiState.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListViewModel.kt
  android/festago/app/src/main/res/layout/item_ticket_list.xml
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListViewModelTest.kt
Labels: AN, USER

#344 [AN/USER] feat: 예매 티켓 목록 없을 때 보이지 않게 수정(#341)
  android/festago/app/src/main/res/layout/fragment_my_page.xml
Labels: AN, USER

#349 [BE] feat: 어드민 컨트롤러에 디버깅용 핸들러 메서드 추가 (#348)
  backend/build.gradle
  backend/src/main/java/com/festago/exception/ErrorCode.java
  backend/src/main/java/com/festago/presentation/AdminController.java
Labels: BE, ETC, ADMIN

#302 [BE] feat: 회원이 동일한 무대의 티켓을 1장만 예약할 수 있게 변경 (#288)
  backend/src/main/java/com/festago/application/TicketService.java
  backend/src/main/java/com/festago/domain/MemberTicketRepository.java
  backend/src/main/java/com/festago/domain/Ticket.java
  backend/src/main/java/com/festago/exception/ErrorCode.java
  backend/src/test/java/com/festago/application/integration/ApplicationIntegrationTest.java
  backend/src/test/java/com/festago/application/integration/FestivalServiceIntegrationTest.java
  backend/src/test/java/com/festago/application/integration/TicketServiceIntegrationTest.java
  backend/src/test/java/com/festago/auth/infrastructure/KakaoOAuth2UserInfoClientTest.java
  backend/src/test/resources/ticketing-test-data.sql
Labels: BE

#312 [BE] refactor: OAuth2Clients를 Supplier를 사용하지 않는 방식으로 리팩토링 (#311)
  backend/src/main/java/com/festago/auth/domain/OAuth2Clients.java
Labels: BE, 리팩터링

#359 [BE] fix: 회원 가입시 프로필 사진을 권한을 주지 않으면 null로 저장되는 문제를 해결 (#358)
  backend/src/main/java/com/festago/auth/dto/KakaoUserInfo.java
  backend/src/main/java/com/festago/domain/Member.java
  backend/src/test/java/com/festago/domain/MemberTest.java
Labels: BE, ASAP, FIX, BUG

#362 [BE] fix: profile 기본 이미지 변경 (#361)
  backend/src/main/java/com/festago/domain/Member.java
  backend/src/main/resources/static/images/default-profile.png
Labels: BE, ASAP, 핫픽스

#356 [AN/USER] chore: 앱 출시 버전 적용 (#346)
  android/festago/app/build.gradle.kts
Labels: AN, USER

#368 [BE] feat: School, Student 도메인 추가(#367)
  backend/src/main/java/com/festago/domain/School.java
  backend/src/main/java/com/festago/domain/Student.java
Labels: BE

#373 [AN/USER] refactor: 어댑터로 뷰모델을 직접 넘기지 않도록 리팩터링 (#357)
  android/festago/app/src/main/java/com/festago/festago/presentation/mapper/ReservationMapper.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/mapper/ReservationStageMapper.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/mapper/TicketMapper.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalItemUiState.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalItemViewHolder.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListAdapter.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListFragment.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListUiState.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListViewModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListAdapter.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListFragment.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListItemUiState.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListItemViewHolder.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListUiState.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListViewModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/ReservationFestivalUiState.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveEvent.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveItemUiState.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveUiState.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveViewModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/adapter/TicketReserveAdapter.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/adapter/TicketReserveHeaderAdapter.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/bottomsheet/TicketReserveBottomSheetAdapter.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/bottomsheet/TicketReserveBottomSheetFragment.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/viewHolder/TicketReserveHeaderViewHolder.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/viewHolder/TicketReserveViewHolder.kt
  android/festago/app/src/main/res/layout/fragment_ticket_reserve_bottom_sheet.xml
  android/festago/app/src/main/res/layout/item_festival_list.xml
  android/festago/app/src/main/res/layout/item_ticket_list.xml
  android/festago/app/src/main/res/layout/item_ticket_reserve.xml
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListViewModelTest.kt
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListViewModelTest.kt
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveViewModelTest.kt
Labels: AN, USER

#380 [AN/USER] feat: 프로가드 난독화 수정(#378)
  android/festago/app/build.gradle.kts
  android/festago/app/proguard-rules.pro
Labels: AN, USER

#307 [BE] feat: 공연 시작 시간 이후 티켓을 예매하지 못하도록 변경 (#289)
  backend/build.gradle
  backend/src/main/java/com/festago/application/TicketService.java
  backend/src/main/java/com/festago/application/TicketingService.java
  backend/src/main/java/com/festago/config/TimeConfig.java
  backend/src/main/java/com/festago/domain/Stage.java
  backend/src/main/java/com/festago/domain/Ticket.java
  backend/src/main/java/com/festago/exception/ErrorCode.java
  backend/src/main/java/com/festago/presentation/MemberTicketController.java
  backend/src/test/java/com/festago/application/integration/TicketServiceIntegrationTest.java
  backend/src/test/java/com/festago/application/integration/TicketingServiceIntegrationTest.java
  backend/src/test/java/com/festago/domain/TicketTest.java
  backend/src/test/java/com/festago/presentation/MemberTicketControllerTest.java
Labels: BE

#381 [AN/USER] fix: 재설치 크래시 버그 수정(#379)
  android/festago/app/src/main/res/xml/backup_rules.xml
  android/festago/app/src/main/res/xml/data_extraction_rules.xml
Labels: AN, USER

#355 [BE] chore: swagger 적용(#124)
  backend/build.gradle
  backend/src/main/java/com/festago/auth/dto/LoginMember.java
  backend/src/main/java/com/festago/auth/presentation/AuthController.java
  backend/src/main/java/com/festago/config/SwaggerConfig.java
  backend/src/main/java/com/festago/presentation/AdminController.java
  backend/src/main/java/com/festago/presentation/FestivalController.java
  backend/src/main/java/com/festago/presentation/MemberController.java
  backend/src/main/java/com/festago/presentation/MemberTicketController.java
  backend/src/main/java/com/festago/presentation/StaffMemberTicketController.java
  backend/src/main/java/com/festago/presentation/StageController.java
Labels: BE

#383 [AN/USER] feat: 앱 아이콘 및 앱 네임 수정(#347)
  android/festago/app/src/main/ic_festago_logo-playstore.png
  android/festago/app/src/main/res/drawable/ic_festago_logo_background.xml
  android/festago/app/src/main/res/drawable/ic_festago_logo_foreground.xml
  android/festago/app/src/main/res/mipmap-hdpi/ic_festago_logo.png
  android/festago/app/src/main/res/mipmap-hdpi/ic_festago_logo_round.png
  android/festago/app/src/main/res/mipmap-mdpi/ic_festago_logo.png
  android/festago/app/src/main/res/mipmap-mdpi/ic_festago_logo_round.png
  android/festago/app/src/main/res/mipmap-xhdpi/ic_festago_logo.png
  android/festago/app/src/main/res/mipmap-xhdpi/ic_festago_logo_round.png
  android/festago/app/src/main/res/mipmap-xxhdpi/ic_festago_logo.png
  android/festago/app/src/main/res/mipmap-xxhdpi/ic_festago_logo_round.png
  android/festago/app/src/main/res/mipmap-xxxhdpi/ic_festago_logo.png
  android/festago/app/src/main/res/mipmap-xxxhdpi/ic_festago_logo_round.png
  android/festago/app/src/main/res/values/strings.xml
Labels: AN, USER

#385 [AN/USER] feat: 1.0.1 버전 업(#384)
  android/festago/app/build.gradle.kts
Labels: AN, USER

#387 [BE] feat: 파일 리소스를 BOM 파일로 변경한다 (#386)
  backend/src/main/resources/static/css/404.css
  backend/src/main/resources/static/css/admin/admin-page.css
  backend/src/main/resources/static/css/admin/login.css
  backend/src/main/resources/static/error/404.html
  backend/src/main/resources/static/js/admin/admin-page.js
  backend/src/main/resources/static/js/admin/signup.js
  backend/src/main/resources/static/js/login.js
  backend/src/main/resources/templates/admin/admin-page.html
  backend/src/main/resources/templates/admin/login.html
  backend/src/main/resources/templates/admin/signup.html
Labels: ETC, FIX

#382 [BE] feat: RequestBody 로깅 AOP 추가, errorLog format 변경 (#377)
  backend/src/main/java/com/festago/aop/LogRequestBody.java
  backend/src/main/java/com/festago/aop/LogRequestBodyAspect.java
  backend/src/main/java/com/festago/auth/config/LoginConfig.java
  backend/src/main/java/com/festago/config/RequestWrappingFilter.java
  backend/src/main/java/com/festago/presentation/ErrorLogger.java
  backend/src/main/java/com/festago/presentation/GlobalExceptionHandler.java
  backend/src/main/resources/logback-spring.xml
Labels: BE, 인프라

#391 [BE] fix: 회원 탈퇴 Path에 Interceptor 적용 (#389)
  backend/src/main/java/com/festago/auth/config/LoginConfig.java
  backend/src/main/java/com/festago/auth/domain/AuthPayload.java
  backend/src/test/java/com/festago/auth/infrastructure/JwtAuthExtractorTest.java
  backend/src/test/java/com/festago/auth/presentation/AuthControllerTest.java
Labels: BE, HOT-FIX, BUG

#394 [BE] hot-fix: #389 핫픽스 dev 브랜치 적용 (#389)
  backend/src/main/java/com/festago/auth/config/LoginConfig.java
  backend/src/main/java/com/festago/auth/domain/AuthPayload.java
  backend/src/test/java/com/festago/auth/infrastructure/JwtAuthExtractorTest.java
  backend/src/test/java/com/festago/auth/presentation/AuthControllerTest.java
Labels: BE, HOT-FIX, BUG

#400 [BE] refactor: LocalDateTime.now() 사용을 LocalDateTime.now(clock) 형식으로 변경 (#395)
  backend/src/main/java/com/festago/application/EntryService.java
  backend/src/main/java/com/festago/application/MemberTicketService.java
  backend/src/test/java/com/festago/application/EntryServiceTest.java
  backend/src/test/java/com/festago/application/MemberTicketServiceTest.java
  backend/src/test/java/com/festago/support/TimeInstantProvider.java
Labels: BE, 리팩터링

#393 [ALL] feat: Github Action workflow 실행 조건에 main 브랜치 포함 (#392)
  .github/workflows/assign-reviewer.yml
  .github/workflows/ci-back.yml
  .github/workflows/ci-user-aos.yml
  .github/workflows/closed-issue-notification.yml
  .github/workflows/closed-pr-notification.yml
  .github/workflows/opend-issue-notification.yml
  .github/workflows/opened-pr-notification.yml
Labels: ALL, 인프라

#404 [AN] 사용하지 않는 presentation model 삭제 (#403)
  android/festago/app/src/main/java/com/festago/festago/presentation/mapper/FestivalMapper.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/mapper/ReservationStageMapper.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/model/FestivalUiModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/model/ReservationStageUiModel.kt
Labels: AN, USER, 리팩터링

#388 [BE] feat: 학생 인증을 위한 이메일 전송 기능 구현 (#125)
  backend/build.gradle
  backend/src/main/java/com/festago/application/StudentService.java
  backend/src/main/java/com/festago/auth/config/LoginConfig.java
  backend/src/main/java/com/festago/config/AsyncConfig.java
  backend/src/main/java/com/festago/domain/MailClient.java
  backend/src/main/java/com/festago/domain/SchoolRepository.java
  backend/src/main/java/com/festago/domain/StudentCode.java
  backend/src/main/java/com/festago/domain/StudentCodeRepository.java
  backend/src/main/java/com/festago/domain/StudentRepository.java
  backend/src/main/java/com/festago/domain/VerificationCode.java
  backend/src/main/java/com/festago/domain/VerificationCodeProvider.java
  backend/src/main/java/com/festago/domain/VerificationMailPayload.java
  backend/src/main/java/com/festago/dto/StudentSendMailRequest.java
  backend/src/main/java/com/festago/exception/ErrorCode.java
  backend/src/main/java/com/festago/infrastructure/GoogleMailClient.java
  backend/src/main/java/com/festago/infrastructure/MockMailClient.java
  backend/src/main/java/com/festago/infrastructure/RandomVerificationCodeProvider.java
  backend/src/main/java/com/festago/presentation/StudentController.java
  backend/src/test/java/com/festago/application/StudentServiceTest.java
  backend/src/test/java/com/festago/domain/RandomVerificationCodeProviderTest.java
  backend/src/test/java/com/festago/domain/VerificationCodeTest.java
  backend/src/test/java/com/festago/presentation/StudentControllerTest.java
Labels: BE

#408 [AN] refactor: 예매 제시 화면 Presentation UiModel 제거 (#405)
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryUiState.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryViewModel.kt
  android/festago/app/src/main/res/layout/activity_ticket_entry.xml
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryViewModelTest.kt
Labels: AN, USER, 리팩터링

#412 [AN] refactor: 예매 완료 화면 Presentation UiModel to Arg (#407)
  android/festago/app/src/androidTest/java/com/festago/festago/presentation/ui/reservationcomplete/ReservationCompleteActivityTest.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/mapper/ReservedTicketMapper.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/reservationcomplete/ReservationCompleteActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/reservationcomplete/ReservedTicketArg.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveActivity.kt
  android/festago/app/src/main/res/layout/activity_reservation_complete.xml
Labels: AN

#413 [BE] 티켓팅시 Lazy loading으로 인한 N+1문제를 개선 (#398)
  backend/src/main/java/com/festago/application/TicketingService.java
  backend/src/main/java/com/festago/domain/TicketRepository.java
Labels: BE, 리팩터링
