Repository woowacourse-teams/2023-festa-go, pull requests merged in 2023-11, with the labels that each got.

#593 [AN/USER] feat: 예매 실패 케이스 처리(#369)
  android/festago/app/src/main/java/com/festago/festago/data/repository/TicketDefaultRepository.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveEvent.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveViewModel.kt
  android/festago/app/src/main/res/values/strings.xml
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveViewModelTest.kt
  android/festago/domain/src/main/java/com/festago/festago/model/ErrorCode.kt
Labels: AN, USER

#596 [AN/USER] refactor: 네트워크 에러 로깅을 확장함수 없이 직접 처리한다(#595)
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveViewModel.kt
Labels: AN, USER

#603 [BE] feat: 축제 조회 필터링 구현(#602)
  backend/src/main/java/com/festago/common/exception/ErrorCode.java
  backend/src/main/java/com/festago/festival/application/FestivalService.java
  backend/src/main/java/com/festago/festival/repository/FestivalFilter.java
  backend/src/main/java/com/festago/festival/repository/FestivalRepository.java
  backend/src/main/java/com/festago/festival/repository/FestivalSpecification.java
  backend/src/main/java/com/festago/presentation/FestivalController.java
  backend/src/main/resources/db/migration/V9__festival_date_index.sql
  backend/src/test/java/com/festago/application/FestivalServiceTest.java
  backend/src/test/java/com/festago/festival/domain/FestivalFilterTest.java
  backend/src/test/java/com/festago/festival/repository/FestivalRepositoryTest.java
  backend/src/test/java/com/festago/presentation/FestivalControllerTest.java
Labels: BE, flyway, API

#606 [AN/USER] feat: 홈화면 필터링 기능을 제공한다 (#600)
  android/festago/app/src/main/java/com/festago/festago/data/repository/FestivalDefaultRepository.kt
  android/festago/app/src/main/java/com/festago/festago/data/service/FestivalRetrofitService.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListFragment.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListUiState.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListViewModel.kt
  android/festago/app/src/main/res/drawable/bg_chip_festival_list_selected.xml
  android/festago/app/src/main/res/drawable/img_festago_home_logo.xml
  android/festago/app/src/main/res/drawable/text_chip_festival_list_selected.xml
  android/festago/app/src/main/res/layout/fragment_festival_list.xml
  android/festago/app/src/main/res/values/strings.xml
  android/festago/app/src/main/res/values/style.xml
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListViewModelTest.kt
  android/festago/domain/src/main/java/com/festago/festago/model/FestivalFilter.kt
  android/festago/domain/src/main/java/com/festago/festago/repository/FestivalRepository.kt
Labels: AN, USER

#578 [BE] refactor: /stages/{stageId}/tickets API의 N+1을 해결한다.(#517)
  backend/src/main/java/com/festago/ticket/application/TicketService.java
  backend/src/main/java/com/festago/ticket/repository/TicketRepository.java
  backend/src/test/java/com/festago/application/TicketServiceTest.java
  backend/src/test/java/com/festago/domain/TicketRepositoryTest.java
Labels: BE, 리팩터링

#607 [BE] test properties show sql 관련 설정 삭제 (#605)
  backend/src/test/resources/application-test.yml
Labels: BE, ETC

#598 [BE] 학교 정보 API에 Swagger Annotation을 추가 (#597)
  backend/src/main/java/com/festago/presentation/SchoolController.java
Labels: BE, ETC

#615 [AN/USER] feat: 축제 목록 화면 UX 개선(#614)
  android/festago/app/src/main/res/layout/fragment_festival_list.xml
Labels: AN, USER

#619 [AN] release: v1.2.0 (#618)
  android/festago/app/build.gradle.kts
Labels: RELEASE

#609 [BE] feat: Specification을 Querydsl로 대체한다 (#604)
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/com/festago/config/QuerydslConfig.java
  backend/src/main/java/com/festago/festival/application/FestivalService.java
  backend/src/main/java/com/festago/festival/repository/FestivalFilter.java
  backend/src/main/java/com/festago/festival/repository/FestivalRepository.java
  backend/src/main/java/com/festago/festival/repository/FestivalRepositoryCustom.java
  backend/src/main/java/com/festago/festival/repository/FestivalRepositoryCustomImpl.java
  backend/src/main/java/com/festago/festival/repository/FestivalSpecification.java
  backend/src/test/java/com/festago/fcm/repository/MemberFCMRepositoryTest.java
  backend/src/test/java/com/festago/festival/repository/FestivalRepositoryTest.java
  backend/src/test/java/com/festago/member/repository/MemberRepositoryTest.java
  backend/src/test/java/com/festago/stage/repository/StageRepositoryTest.java
  backend/src/test/java/com/festago/student/repository/StudentRepositoryTest.java
  backend/src/test/java/com/festago/support/RepositoryTest.java
  backend/src/test/java/com/festago/ticket/repository/TicketRepositoryTest.java
  backend/src/test/java/com/festago/ticketing/repository/MemberTicketRepositoryTest.java
Labels: BE, 리팩터링
