Repository woowacourse-teams/2023-festa-go, pull requests merged in 2023-12, with the labels that each got.

#626 [BE] refactor: StudentService 로직 개선 (#625)
  backend/src/main/java/com/festago/student/application/MailClient.java
  backend/src/main/java/com/festago/student/application/StudentService.java
  backend/src/main/java/com/festago/student/domain/StudentCode.java
  backend/src/main/java/com/festago/student/domain/VerificationCode.java
  backend/src/main/java/com/festago/student/domain/VerificationMailPayload.java
  backend/src/main/java/com/festago/student/dto/StudentResponse.java
  backend/src/main/java/com/festago/student/infrastructure/GoogleMailClient.java
  backend/src/main/java/com/festago/student/infrastructure/MockMailClient.java
  backend/src/test/java/com/festago/student/application/StudentServiceTest.java
  backend/src/test/java/com/festago/student/domain/StudentCodeTest.java
Labels: BE, 리팩터링

#634 [BE] feat: CI workflow에 캐싱 및 버전 업데이트 적용 (#633)
  .github/workflows/ci-back.yml
Labels: 💯 BE, 🏢 인프라, ⚙️ 리팩터링

#628 [BE] refactor: JPQL을 사용하는 Repository 메소드를 QueryDsl로 변경 (#627)
  backend/src/main/java/com/festago/stage/repository/StageRepository.java
  backend/src/main/java/com/festago/stage/repository/StageRepositoryCustom.java
  backend/src/main/java/com/festago/stage/repository/StageRepositoryCustomImpl.java
  backend/src/main/java/com/festago/student/repository/StudentRepository.java
  backend/src/main/java/com/festago/student/repository/StudentRepositoryCustom.java
  backend/src/main/java/com/festago/student/repository/StudentRepositoryCustomImpl.java
  backend/src/main/java/com/festago/ticket/repository/TicketAmountRepository.java
  backend/src/main/java/com/festago/ticket/repository/TicketAmountRepositoryCustom.java
  backend/src/main/java/com/festago/ticket/repository/TicketAmountRepositoryCustomImpl.java
  backend/src/main/java/com/festago/ticket/repository/TicketRepository.java
  backend/src/main/java/com/festago/ticket/repository/TicketRepositoryCustom.java
  backend/src/main/java/com/festago/ticket/repository/TicketRepositoryCustomImpl.java
Labels: 💯 BE, ⚙️ 리팩터링

#632 [BE] feat: 어드민 비밀번호 암호화하여 저장 (#631)
  backend/build.gradle
  backend/src/main/java/com/festago/admin/repository/AdminRepository.java
  backend/src/main/java/com/festago/auth/application/AdminAuthService.java
  backend/src/main/java/com/festago/auth/config/AuthConfig.java
  backend/src/test/java/com/festago/admin/repository/MemoryAdminRepository.java
  backend/src/test/java/com/festago/auth/application/AdminAuthServiceTest.java
Labels: 💯 BE

#617 [BE] refactor: MemberTicketService 로직을 개선한다. (#616)
  backend/src/main/java/com/festago/ticketing/application/MemberTicketService.java
  backend/src/main/java/com/festago/ticketing/dto/MemberTicketResponse.java
  backend/src/test/java/com/festago/ticketing/application/MemberTicketServiceTest.java
Labels: 💯 BE, ⚙️ 리팩터링

#638 [BE] refactor: build.gradle QueryDSL 설정 개선 (#637)
  backend/build.gradle
Labels: 💯 BE, ⚙️ 리팩터링

#624 [BE] test: SchoolService의 통합테스트를 작성 (#623)
  backend/src/main/java/com/festago/school/dto/SchoolCreateRequest.java
  backend/src/test/java/com/festago/school/intergration/SchoolServiceIntegrationTest.java
Labels: 💯 BE

#622 [BE] fix: 학생 인증 코드가 유효하지 않을 시 500이 아닌 400 에러를 반환 (#447)
  backend/src/main/java/com/festago/student/domain/VerificationCode.java
  backend/src/test/java/com/festago/student/domain/VerificationCodeTest.java
Labels: 💯 BE, 🛠 수정

#640 [BE] test: ApplicationContext 재사용을 통해, 테스트 속도 향상 (#639)
  backend/src/test/java/com/festago/acceptance/CucumberClient.java
  backend/src/test/java/com/festago/acceptance/CucumberSpringConfiguration.java
  backend/src/test/java/com/festago/acceptance/DataInitializer.java
  backend/src/test/java/com/festago/presentation/AdminControllerTest.java
  backend/src/test/java/com/festago/presentation/AdminViewControllerTest.java
  backend/src/test/java/com/festago/presentation/FestivalControllerTest.java
  backend/src/test/java/com/festago/presentation/MemberControllerTest.java
  backend/src/test/java/com/festago/presentation/MemberTicketControllerTest.java
  backend/src/test/java/com/festago/presentation/SchoolControllerTest.java
  backend/src/test/java/com/festago/presentation/StaffMemberTicketControllerTest.java
  backend/src/test/java/com/festago/presentation/StageControllerTest.java
  backend/src/test/java/com/festago/presentation/StudentControllerTest.java
  backend/src/test/java/com/festago/presentation/auth/AuthControllerTest.java
  backend/src/test/java/com/festago/presentation/auth/RoleArgumentResolverTest.java
  backend/src/test/java/com/festago/support/ApplicationIntegrationTest.java
  backend/src/test/java/com/festago/support/CustomWebMvcTest.java
  backend/src/test/java/com/festago/support/DatabaseClearExtension.java
  backend/src/test/java/com/festago/support/DatabaseClearTestExecutionListener.java
  backend/src/test/java/com/festago/support/MockAllServiceConfig.java
  backend/src/test/java/com/festago/support/MockAuthTestExecutionListener.java
  backend/src/test/java/com/festago/support/RepositoryTest.java
  backend/src/test/java/com/festago/support/ResetMockTestExecutionListener.java
  backend/src/test/java/com/festago/support/TestAuthConfig.java
  backend/src/test/java/com/festago/support/TestTimeConfig.java
  backend/src/test/java/com/festago/ticket/application/integration/TicketServiceIntegrationTest.java
  backend/src/test/java/com/festago/ticketing/repository/MemberTicketRepositoryTest.java
Labels: 💯 BE, ⚙️ 리팩터링, 🧪 테스트, 🙋‍♀️ 제안
