Repository woowacourse-teams/2023-festa-go, pull requests merged in 2023-09, with the labels that each got.

#416 [AN/USER] refactor: TicketHistory 화면 presentation model 제거 (#406) (#410)
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageUiState.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageViewModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/tickethistory/TicketHistoryAdapter.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/tickethistory/TicketHistoryItemUiState.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/tickethistory/TicketHistoryUiState.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/tickethistory/TicketHistoryViewHolder.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/tickethistory/TicketHistoryViewModel.kt
  android/festago/app/src/main/res/layout/fragment_my_page.xml
  android/festago/app/src/main/res/layout/item_ticket_history.xml
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/mypage/MyPageViewModelTest.kt
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/tickethistory/TicketHistoryViewModelTest.kt
Labels: AN, USER

#419 [AN/USER] refactor: TicketReserve 화면 presentation 모델 제거(#418)
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveEvent.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveItemUiState.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveViewModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/bottomsheet/BottomSheetReservationTicketArg.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/bottomsheet/TicketReserveBottomItem.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/bottomsheet/TicketReserveBottomSheetFragment.kt
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveViewModelTest.kt
Labels: AN, USER

#420 [AN/USER] refactor: 티켓 목록 화면 presentation model 을 사용하지 않도록 변경
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListItemUiState.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListItemViewHolder.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListViewModel.kt
  android/festago/app/src/main/res/layout/item_ticket_list.xml
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListViewModelTest.kt
Labels: AN, USER

#424 [AN/USER] 예매 선택을 하지 않으면 버튼이 비활성화 하도록 수정 (#423)
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/bottomsheet/TicketReserveBottomSheetFragment.kt
Labels: AN, USER, 리팩터링, FIX

#422 [AN/USER] 리팩토링 후 남아있는 ui model 모두 제거 (#421)
  android/festago/app/src/main/java/com/festago/festago/presentation/mapper/ReservationMapper.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/mapper/ReservationTicketMapper.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/mapper/StageMapper.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/mapper/TicketCodeMapper.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/mapper/TicketMapper.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/mapper/TicketStateMapper.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/mapper/UserProfileMapper.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/model/ReservationTicketUiModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/model/StageUiModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/model/TicketCodeUiModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/model/TicketConditionUiModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/model/TicketUiModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/model/UserProfileUiModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryActivity.kt
Labels: AN, USER, 리팩터링

#434 [BE] feat: 이메일 코드를 통한 학생 인증 기능을 추가 (#430)
  backend/src/main/java/com/festago/application/StudentService.java
  backend/src/main/java/com/festago/domain/School.java
  backend/src/main/java/com/festago/domain/Student.java
  backend/src/main/java/com/festago/domain/StudentCode.java
  backend/src/main/java/com/festago/domain/StudentCodeRepository.java
  backend/src/main/java/com/festago/dto/StudentVerificateRequest.java
  backend/src/main/java/com/festago/exception/ErrorCode.java
  backend/src/main/java/com/festago/presentation/StudentController.java
  backend/src/main/resources/db/migration/V2__student_code_add_username.sql
  backend/src/test/java/com/festago/application/StudentServiceTest.java
  backend/src/test/java/com/festago/presentation/StudentControllerTest.java
Labels: BE

#432 [BE] feat: 학교 목록 조회 기능 구현 (#431)
  backend/src/main/java/com/festago/application/SchoolService.java
  backend/src/main/java/com/festago/dto/SchoolResponse.java
  backend/src/main/java/com/festago/dto/SchoolsResponse.java
  backend/src/main/java/com/festago/presentation/SchoolController.java
  backend/src/test/java/com/festago/presentation/SchoolControllerTest.java
Labels: BE

#436 [BE] refactor: Oauth2 네트워크 통신을 Transaction 범위 밖으로 분리 (#435)
  backend/src/main/java/com/festago/auth/application/AuthFacadeService.java
  backend/src/main/java/com/festago/auth/application/AuthService.java
  backend/src/main/java/com/festago/auth/dto/LoginMemberDto.java
  backend/src/main/java/com/festago/auth/dto/LoginResponse.java
  backend/src/main/java/com/festago/auth/presentation/AuthController.java
  backend/src/test/java/com/festago/auth/application/AdminAuthFacadeServiceTest.java
  backend/src/test/java/com/festago/auth/application/AuthFacadeServiceTest.java
  backend/src/test/java/com/festago/auth/application/AuthServiceTest.java
  backend/src/test/java/com/festago/auth/application/integration/AuthFacadeServiceIntegrationTest.java
  backend/src/test/java/com/festago/auth/presentation/AuthControllerTest.java
Labels: BE, 제안

#397 [BE] refactor: 에러 로그 형식 Level에 따라 구분 및 Id와 Role 추가 (#396)
  backend/src/main/java/com/festago/aop/LogRequestBodyAspect.java
  backend/src/main/java/com/festago/auth/config/LoginConfig.java
  backend/src/main/java/com/festago/config/ErrorLoggerConfig.java
  backend/src/main/java/com/festago/presentation/AdminController.java
  backend/src/main/java/com/festago/presentation/ErrorLogger.java
  backend/src/main/java/com/festago/presentation/GlobalExceptionHandler.java
  backend/src/test/java/com/festago/support/CustomWebMvcTest.java
Labels: BE, 리팩터링

#438 [BE] feat: WARN 로그 스택 트레이스 출력 제거 (#437)
  backend/src/main/java/com/festago/presentation/GlobalExceptionHandler.java
Labels: BE, FIX

#365 [BE] feat: validation 추가 (#113)
  backend/src/main/java/com/festago/auth/dto/LoginRequest.java
  backend/src/main/java/com/festago/domain/Festival.java
  backend/src/main/java/com/festago/domain/Member.java
  backend/src/main/java/com/festago/domain/MemberTicket.java
  backend/src/main/java/com/festago/domain/Stage.java
  backend/src/main/java/com/festago/domain/Ticket.java
  backend/src/main/java/com/festago/domain/TicketAmount.java
  backend/src/main/java/com/festago/domain/TicketEntryTime.java
  backend/src/main/java/com/festago/dto/ErrorResponse.java
  backend/src/main/java/com/festago/dto/FestivalCreateRequest.java
  backend/src/main/java/com/festago/dto/StageCreateRequest.java
  backend/src/main/java/com/festago/dto/TicketCreateRequest.java
  backend/src/main/java/com/festago/dto/TicketValidationRequest.java
  backend/src/main/java/com/festago/dto/TicketingRequest.java
  backend/src/main/java/com/festago/exception/ErrorCode.java
  backend/src/main/java/com/festago/presentation/AdminController.java
  backend/src/main/java/com/festago/presentation/GlobalExceptionHandler.java
  backend/src/main/java/com/festago/presentation/MemberTicketController.java
  backend/src/main/java/com/festago/presentation/StaffMemberTicketController.java
  backend/src/main/java/com/festago/presentation/StudentController.java
  backend/src/test/java/com/festago/domain/TicketEntryTimeTest.java
Labels: BE

#401 [BE] refactor: EntryCode 도메인 개선 (#399)
  backend/src/main/java/com/festago/application/EntryCodeManager.java
  backend/src/main/java/com/festago/application/EntryService.java
  backend/src/main/java/com/festago/domain/EntryCode.java
  backend/src/main/java/com/festago/domain/EntryCodePayload.java
  backend/src/main/java/com/festago/infrastructure/JwtEntryCodeExtractor.java
  backend/src/test/java/com/festago/application/EntryServiceTest.java
  backend/src/test/java/com/festago/infrastructure/JwtEntryCodeExtractorTest.java
  backend/src/test/java/com/festago/infrastructure/JwtEntryCodeProviderTest.java
Labels: BE, 리팩터링, 제안

#440 [BE] feat: InvalidMediaTypeException 예외 핸들링 (#439)
  backend/src/main/java/com/festago/presentation/GlobalExceptionHandler.java
Labels: BE, FIX

#429 [AN/USER] feat: 학생 인증 화면 구현 (#370)
  android/festago/app/build.gradle.kts
  android/festago/app/src/main/AndroidManifest.xml
  android/festago/app/src/main/java/com/festago/festago/data/dto/SendVerificationRequest.kt
  android/festago/app/src/main/java/com/festago/festago/data/repository/SchoolDefaultRepository.kt
  android/festago/app/src/main/java/com/festago/festago/data/repository/StudentVerificationDefaultRepository.kt
  android/festago/app/src/main/java/com/festago/festago/data/service/StudentVerificationRetrofitService.kt
  android/festago/app/src/main/java/com/festago/festago/di/AuthServiceContainer.kt
  android/festago/app/src/main/java/com/festago/festago/di/RepositoryContainer.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ViewModelFactory.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageFragment.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/studentverification/StudentVerificationActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/studentverification/StudentVerificationEvent.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/studentverification/StudentVerificationUiState.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/studentverification/StudentVerificationViewModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/util/LifecycleOwnerUtil.kt
  android/festago/app/src/main/res/layout/activity_student_verification.xml
  android/festago/app/src/main/res/values/strings.xml
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/studentverification/StudentVerificationViewModelTest.kt
  android/festago/domain/src/main/java/com/festago/festago/model/StudentVerificationCode.kt
  android/festago/domain/src/main/java/com/festago/festago/model/TextValidator.kt
  android/festago/domain/src/main/java/com/festago/festago/repository/SchoolRepository.kt
  android/festago/domain/src/main/java/com/festago/festago/repository/StudentVerificationRepository.kt
  android/festago/domain/src/test/java/com/festago/festago/model/StudentVerificationCodeTest.kt
  android/festago/domain/src/test/java/com/festago/festago/model/TextValidatorTest.kt
Labels: AN, USER

#445 [BE] feat: 동시 요청 시 발생할 수 있는 중복 회원 생성 문제 해결 (#443)
  backend/src/main/java/com/festago/admin/domain/Admin.java
  backend/src/main/java/com/festago/auth/application/AuthService.java
  backend/src/main/java/com/festago/member/domain/Member.java
  backend/src/main/resources/db/migration/V3__unique_admin_social.sql
  backend/src/test/java/com/festago/domain/MemberTicketRepositoryTest.java
Labels: BE

#454 [AN/USER] refactor: Hilt 적용(#453)
  android/festago/app/build.gradle.kts
  android/festago/app/src/main/java/com/festago/festago/FestagoApplication.kt
  android/festago/app/src/main/java/com/festago/festago/analytics/FirebaseAnalyticsHelper.kt
  android/festago/app/src/main/java/com/festago/festago/data/datasource/TokenLocalDataSource.kt
  android/festago/app/src/main/java/com/festago/festago/data/di/ViewModelScopeModule.kt
  android/festago/app/src/main/java/com/festago/festago/data/di/singletonscope/AnalyticsModule.kt
  android/festago/app/src/main/java/com/festago/festago/data/di/singletonscope/ApiModule.kt
  android/festago/app/src/main/java/com/festago/festago/data/di/singletonscope/DataSourceModule.kt
  android/festago/app/src/main/java/com/festago/festago/data/di/singletonscope/RepositoryModule.kt
  android/festago/app/src/main/java/com/festago/festago/data/di/singletonscope/ServiceModule.kt
  android/festago/app/src/main/java/com/festago/festago/data/repository/AuthDefaultRepository.kt
  android/festago/app/src/main/java/com/festago/festago/data/repository/FestivalDefaultRepository.kt
  android/festago/app/src/main/java/com/festago/festago/data/repository/ReservationTicketDefaultRepository.kt
  android/festago/app/src/main/java/com/festago/festago/data/repository/SchoolDefaultRepository.kt
  android/festago/app/src/main/java/com/festago/festago/data/repository/StudentVerificationDefaultRepository.kt
  android/festago/app/src/main/java/com/festago/festago/data/repository/TicketDefaultRepository.kt
  android/festago/app/src/main/java/com/festago/festago/data/repository/TokenDefaultRepository.kt
  android/festago/app/src/main/java/com/festago/festago/data/repository/UserDefaultRepository.kt
  android/festago/app/src/main/java/com/festago/festago/data/retrofit/TokenManager.kt
  android/festago/app/src/main/java/com/festago/festago/di/AnalysisContainer.kt
  android/festago/app/src/main/java/com/festago/festago/di/AuthServiceContainer.kt
  android/festago/app/src/main/java/com/festago/festago/di/LocalDataSourceContainer.kt
  android/festago/app/src/main/java/com/festago/festago/di/NormalServiceContainer.kt
  android/festago/app/src/main/java/com/festago/festago/di/RepositoryContainer.kt
  android/festago/app/src/main/java/com/festago/festago/di/TokenContainer.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ViewModelFactory.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/customview/OkDialogFragment.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/HomeActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/HomeViewModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListFragment.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListViewModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageFragment.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageViewModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListFragment.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/ticketlist/TicketListViewModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/reservationcomplete/ReservationCompleteActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/signin/SignInActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/signin/SignInViewModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/studentverification/StudentVerificationActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/studentverification/StudentVerificationViewModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryViewModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/tickethistory/TicketHistoryActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/tickethistory/TicketHistoryViewModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/TicketReserveViewModel.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketreserve/bottomsheet/TicketReserveBottomSheetFragment.kt
  android/festago/build.gradle.kts
Labels: AN, USER, 리팩터링

#465 [BE] refactor: Ticket의 school not null 제약조건 제거
  backend/src/main/java/com/festago/festival/domain/Festival.java
  backend/src/main/java/com/festago/ticket/domain/Ticket.java
  backend/src/main/resources/db/migration/V4__add_school_fk.sql
Labels: BE

#461 [AN/USER] feat: 학교 선택 화면 구현(#374)
  android/festago/app/src/main/AndroidManifest.xml
  android/festago/app/src/main/java/com/festago/festago/data/di/ViewModelScopeModule.kt
  android/festago/app/src/main/java/com/festago/festago/data/di/singletonscope/RepositoryModule.kt
  android/festago/app/src/main/java/com/festago/festago/data/di/singletonscope/ServiceModule.kt
  android/festago/app/src/main/java/com/festago/festago/data/dto/SchoolResponse.kt
  android/festago/app/src/main/java/com/festago/festago/data/dto/SchoolsResponse.kt
  android/festago/app/src/main/java/com/festago/festago/data/repository/SchoolDefaultRepository.kt
  android/festago/app/src/main/java/com/festago/festago/data/service/SchoolRetrofitService.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageFragment.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/selectschool/SelectSchoolActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/selectschool/SelectSchoolEvent.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/selectschool/SelectSchoolUiState.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/selectschool/SelectSchoolViewModel.kt
  android/festago/app/src/main/res/layout/activity_select_school.xml
  android/festago/app/src/main/res/layout/item_select_school.xml
  android/festago/app/src/main/res/values/strings.xml
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/selectschool/SelectSchoolViewModelTest.kt
  android/festago/domain/src/main/java/com/festago/festago/model/School.kt
  android/festago/domain/src/main/java/com/festago/festago/repository/SchoolRepository.kt
Labels: AN, USER

#470 [AN/USER] feat: 학생 인증 API 연동(#456)
  android/festago/app/src/main/java/com/festago/festago/data/dto/SendVerificationRequest.kt
  android/festago/app/src/main/java/com/festago/festago/data/dto/VerificationRequest.kt
  android/festago/app/src/main/java/com/festago/festago/data/repository/StudentVerificationDefaultRepository.kt
  android/festago/app/src/main/java/com/festago/festago/data/service/StudentVerificationRetrofitService.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/studentverification/StudentVerificationActivity.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/studentverification/StudentVerificationEvent.kt
  android/festago/app/src/main/java/com/festago/festago/presentation/ui/studentverification/StudentVerificationViewModel.kt
  android/festago/app/src/main/res/layout/activity_student_verification.xml
  android/festago/app/src/test/java/com/festago/festago/presentation/ui/studentverification/StudentVerificationViewModelTest.kt
Labels: AN, USER
