Repository woowacourse-teams/2023-festa-go, pull requests merged in 2024-05, with the labels that each got.

#902 [AN/USER] fix: 요구사항에 맞게 기능을 수정한다(#900)
  android/festago/data/src/main/java/com/festago/festago/data/repository/DefaultSearchRepository.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/artistdetail/ArtistDetailViewModel.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/artistdetail/adapter/festival/ArtistDetailFestivalViewHolder.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/festivaldetail/FestivalDetailFragment.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/festival/FestivalListFestivalViewHolder.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/schooldetail/SchoolDetailFestivalViewHolder.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/schooldetail/SchoolDetailViewModel.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/search/festivalsearch/FestivalSearchViewHolder.kt
  android/festago/presentation/src/main/res/values/strings.xml
Labels: AN, USER

#901 [AN/USER] feat: 카카오 로그인 및 토큰 관리(#861)
  android/festago/common/build.gradle.kts
  android/festago/common/src/main/java/com/festago/festago/common/kakao/KakaoAuthorization.kt
  android/festago/data/build.gradle.kts
  android/festago/data/src/main/java/com/festago/festago/data/datasource/token/TokenDataSource.kt
  android/festago/data/src/main/java/com/festago/festago/data/datasource/token/TokenLocalDataSource.kt
  android/festago/data/src/main/java/com/festago/festago/data/datasource/userinfo/UserInfoDataSource.kt
  android/festago/data/src/main/java/com/festago/festago/data/datasource/userinfo/UserInfoLocalDataSource.kt
  android/festago/data/src/main/java/com/festago/festago/data/di/singletonscope/ApiModule.kt
  android/festago/data/src/main/java/com/festago/festago/data/di/singletonscope/DataSourceModule.kt
  android/festago/data/src/main/java/com/festago/festago/data/di/singletonscope/RepositoryModule.kt
  android/festago/data/src/main/java/com/festago/festago/data/di/singletonscope/ServiceModule.kt
  android/festago/data/src/main/java/com/festago/festago/data/dto/user/RefreshRequest.kt
  android/festago/data/src/main/java/com/festago/festago/data/dto/user/RefreshResponse.kt
  android/festago/data/src/main/java/com/festago/festago/data/dto/user/SignInRequest.kt
  android/festago/data/src/main/java/com/festago/festago/data/dto/user/SignInResponse.kt
  android/festago/data/src/main/java/com/festago/festago/data/dto/user/TokenResponse.kt
  android/festago/data/src/main/java/com/festago/festago/data/model/TokenEntity.kt
  android/festago/data/src/main/java/com/festago/festago/data/model/UserInfoEntity.kt
  android/festago/data/src/main/java/com/festago/festago/data/repository/DefaultUserRepository.kt
  android/festago/data/src/main/java/com/festago/festago/data/repository/FakeUserRepository.kt
  android/festago/data/src/main/java/com/festago/festago/data/retrofit/AuthInterceptor.kt
  android/festago/data/src/main/java/com/festago/festago/data/service/AuthRetrofitService.kt
  android/festago/data/src/main/java/com/festago/festago/data/util/ResponseExt.kt
  android/festago/data/src/main/java/com/festago/festago/data/util/SharedPrefExt.kt
  android/festago/domain/src/main/java/com/festago/festago/domain/exception/UnauthorizedException.kt
  android/festago/domain/src/main/java/com/festago/festago/domain/model/nonce/NonceGenerator.kt
  android/festago/domain/src/main/java/com/festago/festago/domain/model/user/Token.kt
  android/festago/domain/src/main/java/com/festago/festago/domain/model/user/UserInfo.kt
  android/festago/domain/src/main/java/com/festago/festago/domain/repository/UserRepository.kt
  android/festago/presentation/src/main/AndroidManifest.xml
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/signin/SignInActivity.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/signin/SignInEvent.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/signin/SignInViewModel.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/splash/SplashActivity.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/splash/SplashEvent.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/splash/SplashViewModel.kt
  android/festago/presentation/src/main/res/drawable/bg_kakao_sign_in.xml
  android/festago/presentation/src/main/res/drawable/bg_sign_in.png
  android/festago/presentation/src/main/res/drawable/ic_kakao_logo.xml
  android/festago/presentation/src/main/res/layout/activity_sign_in.xml
  android/festago/presentation/src/main/res/values/strings.xml
Labels: AN, USER

#923 [AN/USER] feat: 북마크 추가 버튼 기능 구현 및 API 연동(#922)
  android/festago/data/src/main/java/com/festago/festago/data/di/singletonscope/RepositoryModule.kt
  android/festago/data/src/main/java/com/festago/festago/data/di/singletonscope/ServiceModule.kt
  android/festago/data/src/main/java/com/festago/festago/data/repository/DefaultBookmarkRepository.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/artistdetail/ArtistDetailEvent.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/artistdetail/ArtistDetailFragment.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/artistdetail/ArtistDetailViewModel.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/artistdetail/uistate/ArtistDetailUiState.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/festivaldetail/FestivalDetailEvent.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/festivaldetail/FestivalDetailFragment.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/festivaldetail/FestivalDetailViewModel.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/festivaldetail/uiState/FestivalDetailUiState.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/bookmarklist/festivalbookmark/FestivalBookmarkViewModel.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/schooldetail/SchoolDetailEvent.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/schooldetail/SchoolDetailFragment.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/schooldetail/SchoolDetailViewModel.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/schooldetail/uistate/SchoolDetailUiState.kt
  android/festago/presentation/src/main/res/layout/fragment_artist_detail.xml
  android/festago/presentation/src/main/res/layout/fragment_festival_detail.xml
  android/festago/presentation/src/main/res/layout/fragment_school_detail.xml
Labels: AN, USER, 🏗️ 기능

#913 [AN/USER] feat: 검색 기능 바텀 네비에 추가(#904)
  android/festago/presentation/src/main/res/menu/menu_bottom_navigation.xml
  android/festago/presentation/src/main/res/navigation/home_graph.xml
  android/festago/presentation/src/main/res/navigation/search.xml
  android/festago/presentation/src/main/res/values/strings.xml
Labels: AN, USER

#921 [BE] fix: 아티스트 목록 스웨거 문서에서 정확하게 표시되도록 변경 (#920)
  backend/src/main/java/com/festago/artist/dto/ArtistFestivalDetailV1Response.java
  backend/src/main/java/com/festago/artist/infrastructure/JsonArtistsSerializer.java
  backend/src/main/java/com/festago/festival/dto/FestivalSearchV1Response.java
  backend/src/main/java/com/festago/festival/dto/FestivalV1Response.java
  backend/src/main/java/com/festago/festival/dto/StageV1Response.java
  backend/src/main/java/com/festago/school/dto/v1/SchoolFestivalV1Response.java
Labels: BE, 🛠 수정

#919 [BE] fix: Swagger 문서에 표시되는 memberId 파라미터 삭제 및 인증 필요한 API 표식 추가, 레거시 코드 삭제 (#918)
  backend/src/main/java/com/festago/auth/annotation/Member.java
  backend/src/main/java/com/festago/auth/annotation/MemberAuth.java
  backend/src/main/java/com/festago/auth/application/AuthFacadeService.java
  backend/src/main/java/com/festago/auth/application/AuthService.java
  backend/src/main/java/com/festago/auth/dto/LoginMemberDto.java
  backend/src/main/java/com/festago/auth/dto/LoginRequest.java
  backend/src/main/java/com/festago/auth/dto/LoginResponse.java
  backend/src/main/java/com/festago/auth/presentation/AuthController.java
  backend/src/test/java/com/festago/auth/application/AuthFacadeServiceTest.java
  backend/src/test/java/com/festago/auth/application/AuthServiceTest.java
  backend/src/test/java/com/festago/auth/application/integration/AuthFacadeServiceIntegrationTest.java
  backend/src/test/java/com/festago/presentation/auth/AuthControllerTest.java
Labels: BE, ⚙️ 리팩터링, 🛠 수정

#887 [BE] feat: 커서 기반 페이징 처리 시 last 여부를 설정하는 로직을 공통으로 처리 (#885)
  backend/src/main/java/com/festago/artist/repository/ArtistDetailV1QueryDslRepository.java
  backend/src/main/java/com/festago/common/querydsl/QueryDslHelper.java
  backend/src/main/java/com/festago/common/querydsl/QueryDslRepositorySupport.java
  backend/src/main/java/com/festago/festival/repository/FestivalSearchCondition.java
  backend/src/main/java/com/festago/festival/repository/FestivalV1QueryDslRepository.java
  backend/src/main/java/com/festago/school/repository/v1/SchoolV1QueryDslRepository.java
Labels: BE, ⚙️ 리팩터링

#934 [AN/USER] fix: 축제 목록 아이템 높이 수정(#932)
  android/festago/app/build.gradle.kts
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/splash/SplashActivity.kt
  android/festago/presentation/src/main/res/layout/item_artist_detail_festival.xml
  android/festago/presentation/src/main/res/layout/item_festival_list_festival.xml
  android/festago/presentation/src/main/res/layout/item_school_detail_festival.xml
  android/festago/presentation/src/main/res/layout/item_search_festival.xml
Labels: AN, USER, 🐛 버그

#939 fix: SocialMediaUpdateCommand, SocialMediaCreateCommand 빌더 패턴 사용 (#938)
  backend/src/main/java/com/festago/admin/dto/socialmedia/SocialMediaCreateV1Request.java
  backend/src/main/java/com/festago/admin/dto/socialmedia/SocialMediaUpdateV1Request.java
  backend/src/main/java/com/festago/socialmedia/dto/command/SocialMediaCreateCommand.java
  backend/src/main/java/com/festago/socialmedia/dto/command/SocialMediaUpdateCommand.java
Labels: BE, 🚨 우선순위上, 🔥 핫픽스, ADMIN, 🛠 수정

#949 [BE] fix: 아티스트 생성, 수정, 삭제 이벤트 발행 추가 (#948)
  backend/src/main/java/com/festago/artist/application/ArtistCommandService.java
  backend/src/test/java/com/festago/artist/application/ArtistCommandServiceTest.java
Labels: BE, 🚨 우선순위上, 🛠 수정

#942 [AN/USER] fix: refresh 토큰 인증 오류 수정(#941)
  android/festago/app/build.gradle.kts
  android/festago/data/src/main/java/com/festago/festago/data/repository/DefaultUserRepository.kt
  android/festago/data/src/main/java/com/festago/festago/data/repository/FakeUserRepository.kt
  android/festago/data/src/main/java/com/festago/festago/data/retrofit/AuthInterceptor.kt
  android/festago/domain/src/main/java/com/festago/festago/domain/repository/UserRepository.kt
Labels: AN, USER, 🚨 우선순위上, 🛠 수정

#960 [AN/USER] fix: 축제 목록 지역 선택 crash 발생 해결(#958)
  android/festago/app/build.gradle.kts
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListFragment.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/bottomsheet/RegionBottomSheetDialogFragment.kt
Labels: AN, USER, 🔥 핫픽스, 🐛 버그

#954 [BE] feat: School domain 유니크 제약조건 삭제 (#935)
  backend/src/main/java/com/festago/school/application/SchoolCommandService.java
  backend/src/main/java/com/festago/school/domain/School.java
  backend/src/main/resources/db/migration/V4__remove_school_unique_domain.sql
  backend/src/test/java/com/festago/school/application/SchoolCommandServiceTest.java
Labels: BE, 🛠 수정, ☢️ DB

#961 [BE] fix: Swagger 문서에 잘못된 Parameter 수정 및 형식 통일 (#959)
  backend/src/main/java/com/festago/artist/application/ArtistDetailV1QueryService.java
  backend/src/main/java/com/festago/artist/dto/ArtistFestivalV1Response.java
  backend/src/main/java/com/festago/artist/dto/ArtistMediaV1Response.java
  backend/src/main/java/com/festago/artist/presentation/v1/ArtistSearchV1Controller.java
  backend/src/main/java/com/festago/artist/presentation/v1/ArtistV1Controller.java
  backend/src/main/java/com/festago/artist/repository/ArtistDetailV1QueryDslRepository.java
  backend/src/main/java/com/festago/auth/presentation/v1/MemberAuthV1Controller.java
  backend/src/main/java/com/festago/bookmark/presentation/v1/ArtistBookmarkV1Controller.java
  backend/src/main/java/com/festago/bookmark/presentation/v1/BookmarkManagementV1Controller.java
  backend/src/main/java/com/festago/bookmark/presentation/v1/FestivalBookmarkV1Controller.java
  backend/src/main/java/com/festago/bookmark/presentation/v1/SchoolBookmarkV1Controller.java
  backend/src/main/java/com/festago/common/presentation/PingController.java
  backend/src/main/java/com/festago/entry/presentation/MemberEntranceController.java
  backend/src/main/java/com/festago/entry/presentation/StaffMemberTicketController.java
  backend/src/main/java/com/festago/fcm/presentation/MemberFCMController.java
  backend/src/main/java/com/festago/festival/presentation/v1/FestivalSearchV1Controller.java
  backend/src/main/java/com/festago/festival/presentation/v1/FestivalV1Controller.java
  backend/src/main/java/com/festago/festival/presentation/v1/PopularFestivalV1Controller.java
  backend/src/main/java/com/festago/member/presentation/MemberController.java
  backend/src/main/java/com/festago/school/presentation/v1/SchoolSearchV1Controller.java
  backend/src/main/java/com/festago/school/presentation/v1/SchoolV1Controller.java
  backend/src/main/java/com/festago/student/presentation/StudentController.java
  backend/src/main/java/com/festago/ticketing/presentation/MemberTicketController.java
  backend/src/test/java/com/festago/artist/application/integration/ArtistDetailV1QueryServiceIntegrationTest.java
  backend/src/test/java/com/festago/artist/presentation/v1/ArtistV1ControllerTest.java
Labels: BE, 🛠 수정

#953 [BE] 기본 이미지 URL 정책 빈 문자열로 변경 (#952)
  backend/src/main/java/com/festago/admin/dto/artist/ArtistV1CreateRequest.java
  backend/src/main/java/com/festago/admin/dto/artist/ArtistV1UpdateRequest.java
  backend/src/main/java/com/festago/admin/dto/socialmedia/SocialMediaCreateV1Request.java
  backend/src/main/java/com/festago/admin/dto/socialmedia/SocialMediaUpdateV1Request.java
  backend/src/main/java/com/festago/artist/domain/Artist.java
  backend/src/main/java/com/festago/common/util/ImageUrlHelper.java
  backend/src/main/java/com/festago/festival/domain/Festival.java
  backend/src/main/java/com/festago/member/domain/Member.java
  backend/src/main/java/com/festago/mock/domain/MockFestivalsGenerator.java
  backend/src/main/java/com/festago/mock/domain/MockSchoolsGenerator.java
  backend/src/main/java/com/festago/school/domain/School.java
  backend/src/main/java/com/festago/socialmedia/domain/SocialMedia.java
  backend/src/test/java/com/festago/member/domain/MemberTest.java
  backend/src/test/java/com/festago/school/domain/SchoolTest.java
Labels: BE, 🛠 수정, 🏗️ 기능

#966 fix: member 테이블 social_id 컬럼 길이 45글자 수정 (#965)
  backend/src/main/resources/db/migration/V5__modify_member_social_id.sql
Labels: BE, 🚨 우선순위上, 🛠 수정, ☢️ DB

#927 [BE] feat: 축제 대학교 검색 기능 보완 및 정렬(#926)
  backend/src/main/java/com/festago/festival/application/FestivalSearchV1QueryService.java
  backend/src/main/java/com/festago/festival/repository/ArtistFestivalSearchV1QueryDslRepository.java
  backend/src/test/java/com/festago/festival/application/integration/query/FestivalSearchV1QueryServiceTest.java
Labels: BE, ⚙️ 리팩터링

#937 [BE] feat: FestivalQueryInfo, StageQueryInfo를 재갱신하는 어드민 API 추가 (#933)
  backend/src/main/java/com/festago/admin/application/AdminQueryInfoRenewalService.java
  backend/src/main/java/com/festago/admin/dto/queryinfo/QueryInfoRenewalFestivalPeriodV1Request.java
  backend/src/main/java/com/festago/admin/presentation/v1/AdminQueryInfoRenewalV1Controller.java
  backend/src/main/java/com/festago/admin/repository/AdminFestivalIdResolverQueryDslRepository.java
  backend/src/main/java/com/festago/admin/repository/AdminStageIdResolverQueryDslRepository.java
  backend/src/main/java/com/festago/stage/application/StageQueryInfoEventListener.java
  backend/src/main/java/com/festago/stage/application/StageQueryInfoService.java
  backend/src/test/java/com/festago/admin/presentation/v1/AdminQueryInfoRenewalV1ControllerTest.java
  backend/src/test/java/com/festago/admin/repository/AdminFestivalIdResolverQueryDslRepositoryTest.java
  backend/src/test/java/com/festago/admin/repository/AdminStageIdResolverQueryDslRepositoryTest.java
  backend/src/test/java/com/festago/artist/infrastructure/DelimiterArtistsSerializer.java
  backend/src/test/java/com/festago/stage/application/StageQueryInfoServiceTest.java
  backend/src/test/java/com/festago/stage/repository/MemoryStageQueryInfoRepository.java
  backend/src/test/java/com/festago/support/fixture/FestivalFixture.java
Labels: BE, ADMIN, 📬 API, 🏗️ 기능

#943 [BE] refactor: CreateCommand, UpdateCommand 클래스 빌더 패턴 적용 및 테스트 코드 적용 (#940)
  backend/src/main/java/com/festago/admin/dto/artist/ArtistV1CreateRequest.java
  backend/src/main/java/com/festago/admin/dto/artist/ArtistV1UpdateRequest.java
  backend/src/main/java/com/festago/admin/dto/festival/FestivalV1CreateRequest.java
  backend/src/main/java/com/festago/admin/dto/festival/FestivalV1UpdateRequest.java
  backend/src/main/java/com/festago/admin/dto/school/SchoolV1CreateRequest.java
  backend/src/main/java/com/festago/admin/dto/school/SchoolV1UpdateRequest.java
  backend/src/main/java/com/festago/admin/dto/stage/StageV1CreateRequest.java
  backend/src/main/java/com/festago/admin/dto/stage/StageV1UpdateRequest.java
  backend/src/main/java/com/festago/artist/dto/command/ArtistCreateCommand.java
  backend/src/main/java/com/festago/artist/dto/command/ArtistUpdateCommand.java
  backend/src/main/java/com/festago/auth/dto/AdminLoginV1Request.java
  backend/src/main/java/com/festago/auth/dto/AdminSignupV1Request.java
  backend/src/main/java/com/festago/auth/dto/command/AdminLoginCommand.java
  backend/src/main/java/com/festago/auth/dto/command/AdminSignupCommand.java
  backend/src/main/java/com/festago/festival/dto/command/FestivalCreateCommand.java
  backend/src/main/java/com/festago/festival/dto/command/FestivalUpdateCommand.java
  backend/src/main/java/com/festago/school/application/SchoolCommandService.java
  backend/src/main/java/com/festago/school/application/SchoolDeleteService.java
  backend/src/main/java/com/festago/school/dto/SchoolCreateCommand.java
  backend/src/main/java/com/festago/school/dto/SchoolUpdateCommand.java
  backend/src/main/java/com/festago/school/dto/command/SchoolCreateCommand.java
  backend/src/main/java/com/festago/school/dto/command/SchoolUpdateCommand.java
  backend/src/main/java/com/festago/school/dto/event/SchoolCreatedEvent.java
  backend/src/main/java/com/festago/school/dto/event/SchoolDeletedEvent.java
  backend/src/main/java/com/festago/school/dto/event/SchoolUpdatedEvent.java
  backend/src/main/java/com/festago/stage/dto/command/StageCreateCommand.java
  backend/src/main/java/com/festago/stage/dto/command/StageUpdateCommand.java
  backend/src/main/java/com/festago/upload/application/school/AsyncSchoolUploadImagesStatusChangeEventListener.java
  backend/src/test/java/com/festago/acceptance/steps/AdminStepDefinitions.java
  backend/src/test/java/com/festago/acceptance/steps/FestivalStepDefinitions.java
  backend/src/test/java/com/festago/admin/presentation/v1/AdminSchoolV1ControllerTest.java
  backend/src/test/java/com/festago/artist/application/ArtistCommandServiceTest.java
  backend/src/test/java/com/festago/auth/application/command/AdminAuthCommandServiceTest.java
  backend/src/test/java/com/festago/festival/application/QueryDslSchoolSearchRecentFestivalV1QueryServiceIntegrationTest.java
  backend/src/test/java/com/festago/festival/application/integration/command/FestivalCreateServiceTest.java
  backend/src/test/java/com/festago/festival/application/integration/command/FestivalUpdateServiceTest.java
  backend/src/test/java/com/festago/festival/application/integration/query/FestivalDetailV1QueryServiceIntegrationTest.java
  backend/src/test/java/com/festago/festival/application/integration/query/FestivalV1QueryServiceIntegrationTest.java
  backend/src/test/java/com/festago/festival/application/integration/query/PopularFestivalV1QueryServiceIntegrationTest.java
  backend/src/test/java/com/festago/school/application/SchoolCommandServiceTest.java
  backend/src/test/java/com/festago/socialmedia/application/SocialMediaCommandServiceTest.java
  backend/src/test/java/com/festago/stage/application/command/StageCommandServiceIntegrationTest.java
  backend/src/test/java/com/festago/stage/application/command/StageCreateServiceTest.java
  backend/src/test/java/com/festago/stage/application/command/StageUpdateServiceTest.java
Labels: BE, ⚙️ 리팩터링

#947 [BE] feat: ImageFileUploadService jpeg 확장자 지원 추가 (#946)
  backend/src/main/java/com/festago/upload/application/ImageFileUploadService.java
  backend/src/main/java/com/festago/upload/domain/FileExtension.java
  backend/src/test/java/com/festago/upload/application/ImageFileUploadServiceTest.java
Labels: BE, 🏗️ 기능

#951 [BE] refactor: OpenIdUserInfoProvider 삭제 및 OpenIdClient에 비즈니스 로직 구현 (#950)
  backend/src/main/java/com/festago/auth/domain/OpenIdUserInfoProvider.java
  backend/src/main/java/com/festago/auth/infrastructure/openid/KakaoOpenIdClient.java
  backend/src/main/java/com/festago/auth/infrastructure/openid/KakaoOpenIdUserInfoProvider.java
  backend/src/test/java/com/festago/auth/infrastructure/KakaoOpenIdClientTest.java
Labels: BE, ⚙️ 리팩터링

#957 [BE] feat: Uploaded 상태로 오래되거나 Abandoned 상태의 UploadFile을 삭제하는 기능 추가 (#956)
  backend/src/main/java/com/festago/admin/dto/upload/AdminDeleteAbandonedPeriodUploadFileV1Request.java
  backend/src/main/java/com/festago/admin/presentation/v1/AdminUploadFileDeleteV1Controller.java
  backend/src/main/java/com/festago/admin/presentation/v1/AdminUploadImageV1Controller.java
  backend/src/main/java/com/festago/upload/application/UploadFileDeleteService.java
  backend/src/main/java/com/festago/upload/domain/StorageClient.java
  backend/src/main/java/com/festago/upload/infrastructure/R2StorageClient.java
  backend/src/main/java/com/festago/upload/repository/UploadFileRepository.java
  backend/src/test/java/com/festago/admin/presentation/v1/AdminUploadFileDeleteV1ControllerTest.java
  backend/src/test/java/com/festago/admin/presentation/v1/AdminUploadImageV1ControllerTest.java
  backend/src/test/java/com/festago/upload/application/UploadFileDeleteServiceTest.java
  backend/src/test/java/com/festago/upload/infrastructure/FakeStorageClient.java
  backend/src/test/java/com/festago/upload/repository/MemoryUploadFileRepository.java
Labels: BE, ADMIN, 📬 API, 🏗️ 기능

#964 [BE] feat: Artist 생성 시 중복 이름 검증 추가 (#963)
  backend/src/main/java/com/festago/artist/application/ArtistCommandService.java
  backend/src/main/java/com/festago/artist/repository/ArtistRepository.java
  backend/src/main/java/com/festago/common/exception/ErrorCode.java
  backend/src/test/java/com/festago/artist/application/ArtistCommandServiceTest.java
  backend/src/test/java/com/festago/artist/repository/MemoryArtistRepository.java
Labels: BE, ADMIN, 🏗️ 기능

#973 [BE] feat: 라인업이 공개된 축제가 인기 라인업으로 검색되게 변경 (#971)
  backend/src/main/java/com/festago/common/handler/GlobalExceptionHandler.java
  backend/src/main/java/com/festago/festival/application/PopularFestivalV1QueryService.java
  backend/src/main/java/com/festago/festival/repository/PopularFestivalV1QueryDslRepository.java
  backend/src/test/java/com/festago/festival/application/integration/query/PopularFestivalV1QueryServiceIntegrationTest.java
  backend/src/test/java/com/festago/support/fixture/FestivalQueryInfoFixture.java
Labels: BE, 🏗️ 기능

#974 [BE] feat: 사용자 기본 닉네임 정책 추가 (#972)
  backend/src/main/java/com/festago/auth/application/command/MemberAuthCommandService.java
  backend/src/main/java/com/festago/auth/domain/UserInfo.java
  backend/src/main/java/com/festago/auth/domain/UserInfoMemberMapper.java
  backend/src/main/java/com/festago/member/config/DefaultNicknamePolicyConfig.java
  backend/src/main/java/com/festago/member/domain/DefaultNicknamePolicy.java
  backend/src/main/java/com/festago/member/domain/Member.java
  backend/src/main/java/com/festago/member/infrastructure/DefaultNicknamePolicyImpl.java
  backend/src/test/java/com/festago/auth/application/command/MemberAuthCommandServiceTest.java
  backend/src/test/java/com/festago/member/domain/MemberTest.java
  backend/src/test/java/com/festago/member/infrastructure/DefaultNicknamePolicyImplTest.java
Labels: BE, 🏗️ 기능

#977 [AN/USER] 디자인 수정 및 선택 업데이트 룰 추가 (#955)
  android/festago/app/build.gradle.kts
  android/festago/data/src/main/java/com/festago/festago/data/dto/school/SocialMediaResponse.kt
  android/festago/data/src/main/java/com/festago/festago/data/dto/schooldetail/SchoolInfoResponse.kt
  android/festago/data/src/main/java/com/festago/festago/data/repository/FakeArtistRepository.kt
  android/festago/data/src/main/java/com/festago/festago/data/repository/FakeFestivals.kt
  android/festago/data/src/main/java/com/festago/festago/data/repository/FakeSchool.kt
  android/festago/domain/src/main/java/com/festago/festago/domain/model/social/SocialMedia.kt
  android/festago/domain/src/main/java/com/festago/festago/domain/model/social/SocialMediaType.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/artistdetail/ArtistDetailFragment.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/artistdetail/adapter/festival/ArtistDetailFestivalViewHolder.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/festivaldetail/FestivalDetailFragment.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/festivaldetail/adapter/stage/StageViewHolder.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/bookmarklist/festivalbookmark/adapater/FestivalBookmarkViewHolder.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/festival/FestivalListFestivalViewHolder.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/schooldetail/SchoolDetailFestivalViewHolder.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/schooldetail/SchoolDetailFragment.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/search/SearchFragment.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/search/festivalsearch/FestivalSearchViewHolder.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/splash/SplashActivity.kt
  android/festago/presentation/src/main/res/animator/nav_default_enter_anim.xml
  android/festago/presentation/src/main/res/animator/nav_default_exit_anim.xml
  android/festago/presentation/src/main/res/animator/nav_default_pop_enter_anim.xml
  android/festago/presentation/src/main/res/animator/nav_default_pop_exit_anim.xml
  android/festago/presentation/src/main/res/drawable/bg_artist_stroke.xml
  android/festago/presentation/src/main/res/drawable/bg_festival_list_festival.xml
  android/festago/presentation/src/main/res/drawable/ic_facebook.xml
  android/festago/presentation/src/main/res/drawable/ic_instagram.xml
  android/festago/presentation/src/main/res/drawable/ic_user_profile_default.xml
  android/festago/presentation/src/main/res/drawable/ic_x.xml
  android/festago/presentation/src/main/res/drawable/ic_youtube.xml
  android/festago/presentation/src/main/res/drawable/img_default_school.png
  android/festago/presentation/src/main/res/drawable/img_school_background.png
  android/festago/presentation/src/main/res/layout/fragment_artist_detail.xml
  android/festago/presentation/src/main/res/layout/fragment_festival_detail.xml
  android/festago/presentation/src/main/res/layout/fragment_my_page.xml
  android/festago/presentation/src/main/res/layout/fragment_school_detail.xml
  android/festago/presentation/src/main/res/layout/fragment_search.xml
  android/festago/presentation/src/main/res/layout/item_artist_bookmark.xml
  android/festago/presentation/src/main/res/layout/item_artist_detail_artist.xml
  android/festago/presentation/src/main/res/layout/item_artist_detail_festival.xml
  android/festago/presentation/src/main/res/layout/item_festival_bookmark.xml
  android/festago/presentation/src/main/res/layout/item_festival_bookmark_artist.xml
  android/festago/presentation/src/main/res/layout/item_festival_detail_stage.xml
  android/festago/presentation/src/main/res/layout/item_festival_detail_stage_artist.xml
  android/festago/presentation/src/main/res/layout/item_festival_list_artist.xml
  android/festago/presentation/src/main/res/layout/item_festival_list_festival.xml
  android/festago/presentation/src/main/res/layout/item_festival_list_popular.xml
  android/festago/presentation/src/main/res/layout/item_media.xml
  android/festago/presentation/src/main/res/layout/item_school_detail_artist.xml
  android/festago/presentation/src/main/res/layout/item_school_detail_festival.xml
  android/festago/presentation/src/main/res/layout/item_search_festival.xml
  android/festago/presentation/src/main/res/layout/item_search_festival_artist.xml
  android/festago/presentation/src/main/res/values/strings.xml
Labels: AN, USER

#970 [AN/USER] fix: 지역별 필터, 기타 디자인 수정(#969)
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListFragment.kt
  android/festago/presentation/src/main/res/color/selector_btn_region_color.xml
  android/festago/presentation/src/main/res/drawable/ic_bottom_nav_search.xml
  android/festago/presentation/src/main/res/layout/activity_home.xml
  android/festago/presentation/src/main/res/layout/fragment_artist_detail.xml
  android/festago/presentation/src/main/res/layout/fragment_region_bottom_sheet.xml
  android/festago/presentation/src/main/res/layout/item_artist_bookmark.xml
  android/festago/presentation/src/main/res/layout/item_festival_list_popular.xml
  android/festago/presentation/src/main/res/layout/item_region.xml
  android/festago/presentation/src/main/res/layout/item_school_bookmark.xml
  android/festago/presentation/src/main/res/menu/menu_bottom_navigation.xml
Labels: AN, USER

#979 [AN/USER] 디자인 수정 및 Domain Exception 추가 (#978)
  android/festago/data/src/main/java/com/festago/festago/data/util/ResponseExt.kt
  android/festago/domain/src/main/java/com/festago/festago/domain/exception/BookmarkLimitExeededException.kt
  android/festago/domain/src/main/java/com/festago/festago/domain/exception/NetworkException.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/artistdetail/ArtistDetailViewModel.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/festivaldetail/FestivalDetailViewModel.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/schooldetail/SchoolDetailViewModel.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/search/artistsearch/ArtistSearchViewHolder.kt
  android/festago/presentation/src/main/res/layout/fragment_bookmark_list.xml
  android/festago/presentation/src/main/res/layout/item_search_artist.xml
  android/festago/presentation/src/main/res/values/strings.xml
Labels: AN, USER, ⚙️ 리팩터링

#987 [AN/USER] fix: 상세 화면 축제 목록 요청 로직 변경 및 Throwable 예외 처리 제거(#986)
  android/festago/data/src/main/java/com/festago/festago/data/util/ResponseExt.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/artistdetail/ArtistDetailViewModel.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/artistdetail/adapter/festival/ArtistDetailFestivalViewHolder.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/bookmarklist/festivalbookmark/adapater/FestivalBookmarkViewHolder.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/festival/FestivalListFestivalViewHolder.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/mypage/MyPageFragment.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/schooldetail/SchoolDetailFestivalViewHolder.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/schooldetail/SchoolDetailFragment.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/schooldetail/SchoolDetailViewModel.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/search/festivalsearch/FestivalSearchViewHolder.kt
  android/festago/presentation/src/main/res/layout/fragment_bookmark_list.xml
  android/festago/presentation/src/main/res/layout/fragment_my_page.xml
  android/festago/presentation/src/main/res/layout/item_artist_detail_festival.xml
  android/festago/presentation/src/main/res/layout/item_festival_bookmark.xml
  android/festago/presentation/src/main/res/layout/item_festival_list_festival.xml
  android/festago/presentation/src/main/res/layout/item_school_bookmark.xml
  android/festago/presentation/src/main/res/layout/item_school_detail_festival.xml
  android/festago/presentation/src/main/res/layout/item_search_artist.xml
  android/festago/presentation/src/main/res/layout/item_search_festival.xml
  android/festago/presentation/src/main/res/layout/item_search_school.xml
Labels: AN, USER, 🐛 버그

#976 [BE] feat: AppleOpenId 로직 리팩터링(#975)
  backend/src/main/java/com/festago/auth/infrastructure/openid/AppleOpenIdClient.java
  backend/src/main/java/com/festago/auth/infrastructure/openid/AppleOpenIdPublicKeyLocator.java
  backend/src/main/java/com/festago/auth/infrastructure/openid/CachedAppleOpenIdKeyProvider.java
  backend/src/main/java/com/festago/auth/infrastructure/openid/CachedOpenIdKeyProvider.java
  backend/src/test/java/com/festago/auth/infrastructure/openid/AppleOpenIdClientTest.java
  backend/src/test/java/com/festago/auth/infrastructure/openid/AppleOpenIdJwksClientTest.java
Labels: BE, ⚙️ 리팩터링

#990 [BE] chore: Spring Boot 3.2.5 버전 업그레이드 (#989)
  backend/build.gradle.kts
  backend/src/main/java/com/festago/bookmark/domain/Bookmark.java
  backend/src/main/java/com/festago/member/domain/Member.java
  backend/src/main/java/com/festago/school/domain/School.java
  backend/src/main/java/com/festago/socialmedia/domain/SocialMedia.java
  backend/src/main/java/com/festago/stage/domain/Stage.java
  backend/src/main/java/com/festago/ticket/domain/Ticket.java
  backend/src/main/java/com/festago/ticketing/domain/MemberTicket.java
  backend/src/main/java/com/festago/upload/domain/UploadFile.java
Labels: BE

#997 [BE] chore: TODO 주석 제거 (#996)
  backend/src/main/java/com/festago/auth/dto/command/AdminLoginResult.java
  backend/src/main/java/com/festago/entry/presentation/MemberEntranceController.java
  backend/src/main/java/com/festago/school/application/SchoolCommandService.java
  backend/src/main/java/com/festago/socialmedia/application/SocialMediaCommandService.java
  backend/src/test/java/com/festago/presentation/MemberTicketControllerTest.java
  backend/src/test/java/com/festago/school/application/integration/SchoolDeleteServiceIntegrationTest.java
  backend/src/test/java/com/festago/school/domain/SchoolTest.java
  backend/src/test/java/com/festago/socialmedia/application/SocialMediaCommandServiceTest.java
  backend/src/test/resources/features/query_festival.feature
Labels: BE, 💤 우선순위下

#995 [BE] refactor: KakaoOAuth2Client UserInfo 반환 KakaoOpenIdClient 사용하도록 변경 (#994)
  backend/src/main/java/com/festago/auth/application/OAuth2Client.java
  backend/src/main/java/com/festago/auth/application/command/MemberAuthFacadeService.java
  backend/src/main/java/com/festago/auth/dto/KakaoOAuth2TokenResponse.java
  backend/src/main/java/com/festago/auth/dto/KakaoUserInfo.java
  backend/src/main/java/com/festago/auth/infrastructure/oauth2/FestagoOAuth2Client.java
  backend/src/main/java/com/festago/auth/infrastructure/oauth2/KakaoOAuth2Client.java
  backend/src/main/java/com/festago/auth/infrastructure/oauth2/KakaoOAuth2TokenClient.java
  backend/src/main/java/com/festago/auth/infrastructure/oauth2/KakaoOAuth2UserInfoClient.java
  backend/src/main/java/com/festago/auth/infrastructure/oauth2/KakaoOAuth2UserInfoErrorHandler.java
  backend/src/main/java/com/festago/auth/infrastructure/openid/KakaoOpenIdClient.java
  backend/src/test/java/com/festago/auth/domain/OAuth2ClientsTest.java
  backend/src/test/java/com/festago/auth/infrastructure/KakaoOAuth2TokenClientTest.java
  backend/src/test/java/com/festago/auth/infrastructure/KakaoOAuth2UserInfoClientTest.java
Labels: BE, ⚙️ 리팩터링

#991 [BE] Stage 생성, 수정, 삭제 시 발생하는 비효율적인 쿼리 개선 (#988)
  backend/src/main/java/com/festago/admin/application/AdminQueryInfoRenewalService.java
  backend/src/main/java/com/festago/admin/repository/AdminStageIdResolverQueryDslRepository.java
  backend/src/main/java/com/festago/admin/repository/AdminStageResolverQueryDslRepository.java
  backend/src/main/java/com/festago/stage/application/StageQueryInfoEventListener.java
  backend/src/main/java/com/festago/stage/application/StageQueryInfoService.java
  backend/src/main/java/com/festago/stage/application/command/StageCreateService.java
  backend/src/main/java/com/festago/stage/application/command/StageDeleteService.java
  backend/src/main/java/com/festago/stage/application/command/StageUpdateService.java
  backend/src/main/java/com/festago/stage/domain/FestivalIdStageArtistsResolverImpl.java
  backend/src/main/java/com/festago/stage/domain/Stage.java
  backend/src/main/java/com/festago/stage/infrastructure/FestivalIdStageArtistsQueryDslResolver.java
  backend/src/main/java/com/festago/stage/repository/StageArtistRepository.java
  backend/src/main/java/com/festago/stage/repository/StageRepository.java
  backend/src/main/java/com/festago/stage/repository/StageRepositoryCustom.java
  backend/src/main/java/com/festago/stage/repository/StageRepositoryCustomImpl.java
  backend/src/test/java/com/festago/admin/repository/AdminStageResolverQueryDslRepositoryTest.java
  backend/src/test/java/com/festago/stage/application/StageQueryInfoServiceTest.java
  backend/src/test/java/com/festago/stage/application/command/StageCreateServiceTest.java
  backend/src/test/java/com/festago/stage/application/command/StageDeleteServiceTest.java
  backend/src/test/java/com/festago/stage/application/command/StageUpdateServiceTest.java
  backend/src/test/java/com/festago/stage/domain/StageTest.java
  backend/src/test/java/com/festago/stage/infrastructure/FestivalIdStageArtistsQueryDslResolverTest.java
  backend/src/test/java/com/festago/stage/repository/MemoryStageArtistRepository.java
  backend/src/test/java/com/festago/stage/repository/MemoryStageRepository.java
  backend/src/test/java/com/festago/stage/repository/StageRepositoryTest.java
Labels: BE, ⚙️ 리팩터링
