Repository woowacourse-teams/2023-festa-go, pull requests merged in 2024-03, with the labels that each got.

#749 [BE] feat: 관리자 축제 조회 기능 추가 (#745)
  backend/src/main/java/com/festago/admin/application/AdminFestivalV1QueryService.java
  backend/src/main/java/com/festago/admin/dto/AdminFestivalV1Response.java
  backend/src/main/java/com/festago/admin/presentation/v1/AdminFestivalV1Controller.java
  backend/src/main/java/com/festago/admin/repository/AdminFestivalV1QueryDslRepository.java
  backend/src/main/java/com/festago/common/querydsl/OrderSpecifierUtils.java
  backend/src/main/java/com/festago/common/querydsl/QueryDslHelper.java
  backend/src/test/java/com/festago/admin/application/integration/AdminFestivalV1QueryServiceIntegrationTest.java
  backend/src/test/java/com/festago/admin/presentation/v1/AdminFestivalV1ControllerTest.java
Labels: BE, ADMIN, 📬 API

#767 [AN/USER] feat: 바텀 네비게이션 상단에 줄 추가(#766)
  android/festago/presentation/src/main/res/layout/activity_home.xml
Labels: AN, USER

#724 [AN/USER] feat: 축제 목록 화면 페이징 작업(#673)
  android/festago/data/src/main/java/com/festago/festago/data/repository/FakeFestivalRepository.kt
  android/festago/data/src/main/java/com/festago/festago/data/repository/FakeFestivals.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListFragment.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListViewModel.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/festival/FestivalListAdapter.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/festival/FestivalListMoreItemViewHolder.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/festival/FestivalListTabViewHolder.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/uistate/FestivalFilterUiState.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/uistate/FestivalListUiState.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/uistate/FestivalMoreItemUiState.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/uistate/FestivalTabUiState.kt
  android/festago/presentation/src/main/res/layout/item_festival_list_more_item.xml
Labels: AN, USER

#772 [AN/USER] feat: 알림 화면을 구현한다(#771)
  android/festago/presentation/src/main/AndroidManifest.xml
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListFragment.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/notificationlist/NotificationListActivity.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/notificationlist/NotificationListViewModel.kt
  android/festago/presentation/src/main/res/layout/activity_notification_list.xml
  android/festago/presentation/src/main/res/values/strings.xml
Labels: AN, USER

#763 [AN/USER] feat: 축제 상세 페이지 구현(#750)
  android/festago/data/src/main/java/com/festago/festago/data/dto/festival/FestivalDetailResponse.kt
  android/festago/data/src/main/java/com/festago/festago/data/dto/stage/StageResponse.kt
  android/festago/data/src/main/java/com/festago/festago/data/repository/FakeArtistRepository.kt
  android/festago/data/src/main/java/com/festago/festago/data/repository/FakeFestivalRepository.kt
  android/festago/data/src/main/java/com/festago/festago/data/repository/FakeFestivals.kt
  android/festago/data/src/main/java/com/festago/festago/data/repository/FestivalDefaultRepository.kt
  android/festago/data/src/main/java/com/festago/festago/data/service/FestivalRetrofitService.kt
  android/festago/domain/src/main/java/com/festago/festago/domain/model/artist/Stages.kt
  android/festago/domain/src/main/java/com/festago/festago/domain/model/festival/FestivalDetail.kt
  android/festago/domain/src/main/java/com/festago/festago/domain/model/stage/Stage.kt
  android/festago/domain/src/main/java/com/festago/festago/domain/repository/ArtistRepository.kt
  android/festago/domain/src/main/java/com/festago/festago/domain/repository/FestivalRepository.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/artistdetail/ArtistDetailViewModel.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/artistdetail/adapter/festival/ArtistDetailAdapter.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/artistdetail/adapter/festival/ArtistDetailFestivalViewHolder.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/artistdetail/uistate/ArtistDetailUiState.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/artistdetail/uistate/FestivalItemUiState.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/festivaldetail/FestivalDetailEvent.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/festivaldetail/FestivalDetailFragment.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/festivaldetail/FestivalDetailViewModel.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/festivaldetail/adapter/artist/ArtistAdapter.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/festivaldetail/adapter/artist/ArtistViewHolder.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/festivaldetail/adapter/stage/StageListAdapter.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/festivaldetail/adapter/stage/StageViewHolder.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/festivaldetail/uiState/ArtistItemUiState.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/festivaldetail/uiState/FestivalDetailUiState.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/festivaldetail/uiState/FestivalUiState.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/festivaldetail/uiState/StageItemUiState.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/HomeActivity.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListEvent.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListFragment.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListViewModel.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/uistate/FestivalItemUiState.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/schooldetail/SchoolDetailFragment.kt
  android/festago/presentation/src/main/res/drawable/bg_festival_detail_dday_end.xml
  android/festago/presentation/src/main/res/layout/fragment_artist_detail.xml
  android/festago/presentation/src/main/res/layout/fragment_festival_detail.xml
  android/festago/presentation/src/main/res/layout/fragment_festival_list.xml
  android/festago/presentation/src/main/res/layout/fragment_school_detail.xml
  android/festago/presentation/src/main/res/layout/item_artist_detail_festival.xml
  android/festago/presentation/src/main/res/layout/item_festival_detail_stage.xml
  android/festago/presentation/src/main/res/layout/item_festival_detail_stage_artist.xml
  android/festago/presentation/src/main/res/layout/item_festival_list_festival.xml
  android/festago/presentation/src/main/res/layout/item_popular_festival_foreground.xml
  android/festago/presentation/src/main/res/layout/item_school_detail_festival.xml
  android/festago/presentation/src/main/res/values/strings.xml
Labels: AN, USER

#778 [AN/USER] 축제 목록, 공연 목록의 디자인을 수정한다.(#777)
  android/festago/presentation/src/main/res/layout/item_artist_detail_artist.xml
  android/festago/presentation/src/main/res/layout/item_festival_detail_stage.xml
  android/festago/presentation/src/main/res/layout/item_festival_list_artist.xml
  android/festago/presentation/src/main/res/layout/item_school_detail_artist.xml
Labels: AN, USER

#776 [AN/USER] feat: 이미지 로딩 전까지 기본 이미지를 보여준다.(#775)
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/bindingadapter/Image.kt
Labels: AN, USER

#773 [AN/USER] feat: 학교 상세 화면 API 연동 및 API 명세 변경 사항 반영 (#757)
  android/festago/data/src/main/java/com/festago/festago/data/di/singletonscope/ServiceModule.kt
  android/festago/data/src/main/java/com/festago/festago/data/dto/school/SchoolInfoResponse.kt
  android/festago/data/src/main/java/com/festago/festago/data/dto/schooldetail/SchoolFestivalArtistResponse.kt
  android/festago/data/src/main/java/com/festago/festago/data/dto/schooldetail/SchoolFestivalResponse.kt
  android/festago/data/src/main/java/com/festago/festago/data/dto/schooldetail/SchoolFestivalsResponse.kt
  android/festago/data/src/main/java/com/festago/festago/data/dto/schooldetail/SchoolInfoResponse.kt
  android/festago/data/src/main/java/com/festago/festago/data/repository/FakeSchoolRepository.kt
  android/festago/data/src/main/java/com/festago/festago/data/repository/SchoolDefaultRepository.kt
  android/festago/data/src/main/java/com/festago/festago/data/service/SchoolRetrofitService.kt
  android/festago/domain/src/main/java/com/festago/festago/domain/repository/SchoolRepository.kt
Labels: AN, USER

#781 [AN/USER] 안드로이드 네비게이션을 적용한다. (#758)
  android/festago/build.gradle.kts
  android/festago/data/src/main/java/com/festago/festago/data/repository/FakeArtistRepository.kt
  android/festago/gradle.properties
  android/festago/presentation/build.gradle.kts
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/artistdetail/ArtistDetailEvent.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/artistdetail/ArtistDetailFragment.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/artistdetail/ArtistDetailViewModel.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/artistdetail/adapter/artistlist/ArtistAdapter.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/artistdetail/adapter/artistlist/ArtistViewHolder.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/artistdetail/adapter/festival/ArtistDetailAdapter.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/artistdetail/adapter/festival/ArtistDetailFestivalViewHolder.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/artistdetail/uistate/ArtistUiState.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/artistdetail/uistate/FestivalItemUiState.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/festivaldetail/FestivalDetailFragment.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/festivaldetail/FestivalDetailViewModel.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/HomeActivity.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListFragment.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/schooldetail/SchoolDetailFragment.kt
  android/festago/presentation/src/main/res/layout/activity_home.xml
  android/festago/presentation/src/main/res/layout/item_artist_detail_artist.xml
  android/festago/presentation/src/main/res/layout/item_artist_detail_festival.xml
  android/festago/presentation/src/main/res/menu/menu_bottom_navigation.xml
  android/festago/presentation/src/main/res/navigation/book_mark.xml
  android/festago/presentation/src/main/res/navigation/festival_list.xml
  android/festago/presentation/src/main/res/navigation/home_graph.xml
  android/festago/presentation/src/main/res/navigation/my_page.xml
  android/festago/presentation/src/main/res/navigation/ticket_list.xml
Labels: AN, USER

#795 [AN/USER] API 변경 사항 반영 (#792)
  android/festago/data/src/main/java/com/festago/festago/data/dto/artist/ArtistResponse.kt
  android/festago/data/src/main/java/com/festago/festago/data/dto/festival/FestivalResponse.kt
Labels: AN, USER

#770 [BE] feat: 아티스트 검색 기능 구현 (#761)
  backend/src/main/java/com/festago/artist/application/ArtistSearchStageCountV1QueryService.java
  backend/src/main/java/com/festago/artist/application/ArtistSearchV1QueryService.java
  backend/src/main/java/com/festago/artist/application/ArtistTotalSearchV1Service.java
  backend/src/main/java/com/festago/artist/dto/ArtistSearchStageCountV1Response.java
  backend/src/main/java/com/festago/artist/dto/ArtistSearchV1Response.java
  backend/src/main/java/com/festago/artist/dto/ArtistTotalSearchV1Response.java
  backend/src/main/java/com/festago/artist/presentation/v1/ArtistSearchV1Controller.java
  backend/src/main/java/com/festago/artist/repository/ArtistSearchV1QueryDslRepository.java
  backend/src/main/java/com/festago/common/exception/ErrorCode.java
  backend/src/test/java/com/festago/artist/application/ArtistTotalSearchV1ServiceTest.java
  backend/src/test/java/com/festago/artist/application/integration/ArtistDetailV1QueryServiceIntegrationTest.java
  backend/src/test/java/com/festago/artist/application/integration/ArtistSearchStageCountV1QueryServiceIntegrationTest.java
  backend/src/test/java/com/festago/artist/application/integration/ArtistSearchV1QueryServiceIntegrationTest.java
  backend/src/test/java/com/festago/artist/presentation/v1/ArtistSearchV1ControllerTest.java
Labels: BE, 📬 API

#769 [BE] feat: 학교 검색 기능 구현 (#761)
  backend/src/main/java/com/festago/festival/application/QueryDslSchoolSearchUpcomingFestivalV1QueryService.java
  backend/src/main/java/com/festago/festival/dto/RecentSchoolFestivalV1Response.java
  backend/src/main/java/com/festago/festival/repository/RecentSchoolFestivalV1QueryDslRepository.java
  backend/src/main/java/com/festago/school/application/v1/SchoolSearchUpcomingFestivalV1QueryService.java
  backend/src/main/java/com/festago/school/application/v1/SchoolSearchV1QueryService.java
  backend/src/main/java/com/festago/school/application/v1/SchoolTotalSearchV1QueryService.java
  backend/src/main/java/com/festago/school/dto/v1/SchoolSearchUpcomingFestivalV1Response.java
  backend/src/main/java/com/festago/school/dto/v1/SchoolSearchV1Response.java
  backend/src/main/java/com/festago/school/dto/v1/SchoolTotalSearchV1Response.java
  backend/src/main/java/com/festago/school/presentation/v1/SchoolSearchV1Controller.java
  backend/src/main/java/com/festago/school/repository/v1/SchoolSearchV1QueryDslRepository.java
  backend/src/test/java/com/festago/festival/application/QueryDslSchoolSearchRecentFestivalV1QueryServiceIntegrationTest.java
  backend/src/test/java/com/festago/school/application/integration/SchoolSearchV1QueryServiceIntegrationTest.java
  backend/src/test/java/com/festago/school/presentation/v1/SchoolSearchV1ControllerTest.java
Labels: BE, 📬 API, 🏗️ 기능

#790 [BE] feat: 컨트롤러의 핸들러 메서드에 어노테이션을 붙여 인증을 수행하는 기능 추가 (#789)
  backend/src/main/java/com/festago/auth/annotation/MemberAuth.java
  backend/src/main/java/com/festago/auth/config/LoginConfig.java
  backend/src/main/java/com/festago/common/interceptor/AnnotationDelegateInterceptor.java
  backend/src/test/java/com/festago/auth/config/LoginConfigTest.java
Labels: BE, 🏗️ 기능

#582 [BE] feat: 사용자의 FCM을 등록하는 API 분리 (#579)
  backend/src/main/java/com/festago/auth/application/AuthService.java
  backend/src/main/java/com/festago/auth/config/LoginConfig.java
  backend/src/main/java/com/festago/auth/dto/LoginRequest.java
  backend/src/main/java/com/festago/auth/dto/event/MemberCreatedEvent.java
  backend/src/main/java/com/festago/auth/dto/event/MemberDeleteEvent.java
  backend/src/main/java/com/festago/auth/dto/event/MemberDeletedEvent.java
  backend/src/main/java/com/festago/auth/dto/event/MemberRegisterEvent.java
  backend/src/main/java/com/festago/auth/presentation/AuthController.java
  backend/src/main/java/com/festago/fcm/application/FCMMemberDeleteEventListener.java
  backend/src/main/java/com/festago/fcm/application/FCMNotificationEventListener.java
  backend/src/main/java/com/festago/fcm/application/MemberDeletionEventListener.java
  backend/src/main/java/com/festago/fcm/application/MemberFCMService.java
  backend/src/main/java/com/festago/fcm/application/MemberRegisterEventListener.java
  backend/src/main/java/com/festago/fcm/dto/MemberFCMResponse.java
  backend/src/main/java/com/festago/fcm/dto/MemberFCMsResponse.java
  backend/src/main/java/com/festago/fcm/dto/MemberFcmCreateRequest.java
  backend/src/main/java/com/festago/fcm/presentation/MemberFCMController.java
  backend/src/main/java/com/festago/fcm/repository/MemberFCMRepository.java
  backend/src/test/java/com/festago/auth/application/AuthServiceTest.java
  backend/src/test/java/com/festago/fcm/application/FCMNotificationEventListenerTest.java
  backend/src/test/java/com/festago/fcm/application/MemberFCMServiceTest.java
  backend/src/test/java/com/festago/fcm/presentation/MemberFCMControllerTest.java
  backend/src/test/java/com/festago/fcm/repository/MemberFCMRepositoryTest.java
  backend/src/test/java/com/festago/presentation/auth/AuthControllerTest.java
  backend/src/test/java/com/festago/support/CustomWebMvcTest.java
  backend/src/test/java/com/festago/support/MockEventPublisherConfig.java
Labels: BE, AN, 📬 API

#805 [BE] fix: AnnotationDelegateInterceptor에 경로 추가하여 ClassCastException 방지 (#804)
  backend/src/main/java/com/festago/auth/config/LoginConfig.java
  backend/src/test/java/com/festago/auth/config/LoginConfigTest.java
Labels: BE, 🚨 우선순위上, 🛠 수정

#807 [BE] refactor: 테스트 픽스쳐 개선 (#806)
  backend/src/test/java/com/festago/auth/application/AuthFacadeServiceTest.java
  backend/src/test/java/com/festago/auth/application/AuthServiceTest.java
  backend/src/test/java/com/festago/auth/application/integration/AuthFacadeServiceIntegrationTest.java
  backend/src/test/java/com/festago/entry/application/EntryServiceTest.java
  backend/src/test/java/com/festago/entry/infrastructure/JwtEntryCodeProviderTest.java
  backend/src/test/java/com/festago/festival/application/command/FestivalCreateServiceTest.java
  backend/src/test/java/com/festago/festival/application/command/FestivalDeleteServiceTest.java
  backend/src/test/java/com/festago/festival/application/command/FestivalUpdateServiceTest.java
  backend/src/test/java/com/festago/festival/domain/FestivalTest.java
  backend/src/test/java/com/festago/member/repository/MemberRepositoryTest.java
  backend/src/test/java/com/festago/school/application/integration/SchoolCommandServiceIntegrationTest.java
  backend/src/test/java/com/festago/school/application/integration/SchoolDeleteServiceIntegrationTest.java
  backend/src/test/java/com/festago/school/application/integration/SchoolV1QueryServiceIntegrationTest.java
  backend/src/test/java/com/festago/stage/application/command/StageCreateServiceTest.java
  backend/src/test/java/com/festago/stage/application/command/StageDeleteServiceTest.java
  backend/src/test/java/com/festago/stage/application/command/StageUpdateServiceTest.java
  backend/src/test/java/com/festago/stage/domain/StageTest.java
  backend/src/test/java/com/festago/stage/domain/validator/festival/OutOfDateStageFestivalUpdateValidatorTest.java
  backend/src/test/java/com/festago/stage/repository/StageRepositoryTest.java
  backend/src/test/java/com/festago/student/application/StudentServiceTest.java
  backend/src/test/java/com/festago/student/domain/StudentCodeTest.java
  backend/src/test/java/com/festago/student/repository/StudentRepositoryTest.java
  backend/src/test/java/com/festago/support/fixture/AdminFixture.java
  backend/src/test/java/com/festago/support/fixture/ArtistFixture.java
  backend/src/test/java/com/festago/support/fixture/BaseFixture.java
  backend/src/test/java/com/festago/support/fixture/FestivalFixture.java
  backend/src/test/java/com/festago/support/fixture/FestivalQueryInfoFixture.java
  backend/src/test/java/com/festago/support/fixture/MemberFixture.java
  backend/src/test/java/com/festago/support/fixture/MemberTicketFixture.java
  backend/src/test/java/com/festago/support/fixture/SchoolFixture.java
  backend/src/test/java/com/festago/support/fixture/SocialMediaFixture.java
  backend/src/test/java/com/festago/support/fixture/StageArtistFixture.java
  backend/src/test/java/com/festago/support/fixture/StageFixture.java
  backend/src/test/java/com/festago/support/fixture/StageQueryInfoFixture.java
  backend/src/test/java/com/festago/support/fixture/StudentCodeFixture.java
  backend/src/test/java/com/festago/support/fixture/StudentFixture.java
  backend/src/test/java/com/festago/support/fixture/TicketFixture.java
  backend/src/test/java/com/festago/ticket/application/TicketServiceTest.java
  backend/src/test/java/com/festago/ticket/application/integration/TicketServiceIntegrationTest.java
  backend/src/test/java/com/festago/ticket/domain/TicketTest.java
  backend/src/test/java/com/festago/ticket/repository/TicketRepositoryTest.java
  backend/src/test/java/com/festago/ticketing/application/MemberTicketServiceTest.java
  backend/src/test/java/com/festago/ticketing/application/TicketingServiceTest.java
  backend/src/test/java/com/festago/ticketing/application/integration/MemberTicketIntegrationTest.java
  backend/src/test/java/com/festago/ticketing/application/integration/TicketingServiceIntegrationTest.java
  backend/src/test/java/com/festago/ticketing/domain/MemberTicketTest.java
  backend/src/test/java/com/festago/ticketing/repository/MemberTicketRepositoryTest.java
Labels: BE, ⚙️ 리팩터링, 🧪 테스트

#762 [BE] feat: 축제 검색 구현(#761)
  backend/src/main/java/com/festago/common/exception/ErrorCode.java
  backend/src/main/java/com/festago/festival/application/FestivalSearchV1QueryService.java
  backend/src/main/java/com/festago/festival/dto/FestivalSearchV1Response.java
  backend/src/main/java/com/festago/festival/presentation/v1/FestivalSearchV1Controller.java
  backend/src/main/java/com/festago/festival/repository/ArtistFestivalSearchV1QueryDslRepository.java
  backend/src/main/java/com/festago/festival/repository/SchoolFestivalSearchV1QueryDslRepository.java
  backend/src/test/java/com/festago/festival/application/integration/FestivalSearchV1QueryServiceTest.java
Labels: BE, 📬 API, 🏗️ 기능

#794 [BE] feat: 관리자용 특정 축제의 공연 목록 조회 API 추가 (#786)
  backend/src/main/java/com/festago/admin/application/AdminStageV1QueryService.java
  backend/src/main/java/com/festago/admin/dto/stage/AdminStageArtistV1Response.java
  backend/src/main/java/com/festago/admin/dto/stage/AdminStageV1Response.java
  backend/src/main/java/com/festago/admin/presentation/v1/AdminFestivalV1Controller.java
  backend/src/main/java/com/festago/admin/repository/AdminStageV1QueryDslRepository.java
  backend/src/test/java/com/festago/admin/application/integration/AdminStageV1QueryServiceIntegrationTest.java
  backend/src/test/java/com/festago/admin/presentation/v1/AdminFestivalV1ControllerTest.java
Labels: BE, ADMIN, 📬 API, 🏗️ 기능

#803 [BE] refactor: RequestWrappingFilter 개선 (#798)
  backend/src/main/java/com/festago/common/aop/LogRequestBodyAspect.java
  backend/src/main/java/com/festago/common/filter/wrapping/UriPatternInitializer.java
  backend/src/main/java/com/festago/common/filter/wrapping/UriPatternMatcher.java
  backend/src/main/java/com/festago/common/filter/wrapping/UriPatternRequestWrappingFilter.java
  backend/src/main/java/com/festago/config/RequestWrappingFilter.java
  backend/src/test/java/com/festago/common/filter/wrapping/UriPatternMatcherTest.java
Labels: BE, ⚙️ 리팩터링

#791 [BE] feat: 축제 북마크 기능 구현 (#788)
  backend/src/main/java/com/festago/auth/config/LoginConfig.java
  backend/src/main/java/com/festago/bookmark/application/FestivalBookmarkCommandService.java
  backend/src/main/java/com/festago/bookmark/application/FestivalBookmarkV1QueryService.java
  backend/src/main/java/com/festago/bookmark/dto/FestivalBookmarkV1Response.java
  backend/src/main/java/com/festago/bookmark/presentation/v1/FestivalBookmarkV1Controller.java
  backend/src/main/java/com/festago/bookmark/repository/FestivalBookmarkOrder.java
  backend/src/main/java/com/festago/bookmark/repository/FestivalBookmarkV1QueryDslRepository.java
  backend/src/main/java/com/festago/festival/repository/FestivalRepository.java
  backend/src/test/java/com/festago/bookmark/application/FestivalBookmarkCommandServiceTest.java
  backend/src/test/java/com/festago/bookmark/application/integration/FestivalBookmarkV1QueryServiceIntegrationTest.java
  backend/src/test/java/com/festago/bookmark/presentation/v1/FestivalBookmarkV1ControllerTest.java
  backend/src/test/java/com/festago/festival/repository/MemoryFestivalRepository.java
Labels: BE, 📬 API, 🏗️ 기능

#821 [BE] feat: 목 데이터 스케쥴러 구현(#725)
  backend/src/main/java/com/festago/config/SchedulerConfig.java
  backend/src/main/java/com/festago/mock/CommandLineAppStartupRunner.java
  backend/src/main/java/com/festago/mock/MockArtist.java
  backend/src/main/java/com/festago/mock/MockDataService.java
  backend/src/main/java/com/festago/mock/MockFestivalDateGenerator.java
  backend/src/main/java/com/festago/mock/MockScheduler.java
  backend/src/main/java/com/festago/mock/RandomMockFestivalDateGenerator.java
  backend/src/main/java/com/festago/mock/repository/ForMockArtistRepository.java
  backend/src/main/java/com/festago/mock/repository/ForMockFestivalInfoRepository.java
  backend/src/main/java/com/festago/mock/repository/ForMockFestivalRepository.java
  backend/src/main/java/com/festago/mock/repository/ForMockSchoolRepository.java
  backend/src/main/java/com/festago/mock/repository/ForMockStageArtistRepository.java
  backend/src/main/java/com/festago/mock/repository/ForMockStageQueryInfoRepository.java
  backend/src/main/java/com/festago/mock/repository/ForMockStageRepository.java
  backend/src/test/java/com/festago/mock/application/MockDataServiceTest.java
  backend/src/test/java/com/festago/mock/config/MockDataConfig.java
Labels: BE
