Repository woowacourse-teams/2023-festa-go, pull requests merged in 2024-02, with the labels that each got.

#701 [AN/USER] feat: 축제 목록 디자인 수정(#698)
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/festival/FestivalListPopularViewHolder.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/popularfestival/PopularFestivalViewPagerAdapter.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/popularfestival/foreground/PopularFestivalForegroundViewHolder.kt
  android/festago/presentation/src/main/res/drawable/ic_dot_default.xml
  android/festago/presentation/src/main/res/drawable/ic_dot_selected.xml
  android/festago/presentation/src/main/res/layout/item_festival_list_popular.xml
  android/festago/presentation/src/main/res/layout/item_festival_list_tab.xml
  android/festago/presentation/src/main/res/layout/item_popular_festival_foreground.xml
Labels: AN, USER

#700 [BE] feat: Admin 로그인 쿠키에 sameSite=None 추가 (#696)
  backend/src/main/java/com/festago/auth/presentation/AdminAuthController.java
  backend/src/test/java/com/festago/auth/presentation/AdminAuthControllerTest.java
Labels: BE, 🛠 수정

#690 [BE] feat: School 도메인 region 검증, 수정 메서드 추가 및 주석 처리된 기능 활성화 (#689)
  backend/src/main/java/com/festago/school/application/SchoolCommandService.java
  backend/src/main/java/com/festago/school/domain/School.java
  backend/src/main/java/com/festago/school/presentation/v1/SchoolV1Controller.java
  backend/src/test/java/com/festago/school/application/integration/SchoolCommandServiceIntegrationTest.java
Labels: BE

#694 [BE] feat: Controller에 누락된 @Valid 어노테이션 추가, Admin Controller 테스트에 권한 검증 테스트 추가 (#693)
  backend/src/main/java/com/festago/admin/presentation/v1/AdminSchoolV1Controller.java
  backend/src/test/java/com/festago/admin/presentation/v1/AdminArtistV1ControllerTest.java
  backend/src/test/java/com/festago/admin/presentation/v1/AdminSchoolV1ControllerTest.java
Labels: BE, 🛠 수정, 🧪 테스트

#704 [BE] feat: 헬스 체크용 PingController 추가 (#703)
  backend/src/main/java/com/festago/common/presentation/PingController.java
  backend/src/test/java/com/festago/common/presentation/PingControllerTest.java
Labels: BE, 📬 API

#712 [BE] 잘못된 flyway 스크립트 수정 (#707-hotfix1)
  backend/src/main/resources/db/migration/V13__add_socialmedia.sql
  backend/src/main/resources/db/migration/V14__add_imageurl_school_artist.sql
Labels: BE, 🚨 우선순위上, 🛠 수정, ☢️ DB

#708 [BE] fix: "/api/v1/festivals"의 "filter" 쿼리 파리미터 기본 값 지정 및 핸들러 메서드의 형식 변경 (#705)
  backend/src/main/java/com/festago/common/exception/ErrorCode.java
  backend/src/main/java/com/festago/festival/presentation/v1/FestivalV1Controller.java
  backend/src/main/java/com/festago/festival/repository/FestivalV1QueryDslRepository.java
  backend/src/main/java/com/festago/school/domain/SchoolRegion.java
  backend/src/test/java/com/festago/festival/presentation/v1/FestivalV1ControllerTest.java
Labels: BE, 🛠 수정

#711 [BE] refactor: build.gradle build.gradle.kts 변경 (#710)
  backend/build.gradle
  backend/build.gradle.kts
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/settings.gradle
  backend/settings.gradle.kts
Labels: BE, ⚙️ 리팩터링, 🙋‍♀️ 제안

#727 [BE] refactor: application-local.yml .gitignore 등록 (#726)
  backend/.gitignore
  backend/src/main/resources/application-local.yml
Labels: BE, ⚙️ 리팩터링

#720 [BE] refactor: AdminAuthService 도메인 상수 도메인으로 이동 (#612)
  backend/src/main/java/com/festago/admin/domain/Admin.java
  backend/src/main/java/com/festago/auth/application/AdminAuthService.java
Labels: BE, ⚙️ 리팩터링

#715 [BE] refactor: FestivalV1QueryDslRepository 리팩터링, 추천 축제 조회 Service, Repository 분리 (#709)
  backend/src/main/java/com/festago/festival/application/PopularFestivalV1QueryService.java
  backend/src/main/java/com/festago/festival/repository/FestivalV1QueryDslRepository.java
  backend/src/main/java/com/festago/festival/repository/PopularFestivalV1QueryDslRepository.java
  backend/src/test/java/com/festago/festival/application/integration/FestivalV1QueryServiceIntegrationTest.java
  backend/src/test/java/com/festago/festival/application/integration/PopularFestivalV1QueryServiceIntegrationTest.java
  backend/src/test/java/com/festago/festival/application/integration/PopularFestivalV1QueryServiceTest.java
Labels: BE, ⚙️ 리팩터링

#734 [BE] refactor: Bean Validation 메시지 개선 (#733)
  backend/src/main/java/com/festago/common/exception/dto/ErrorResponse.java
  backend/src/main/java/com/festago/common/exception/dto/ValidErrorResponse.java
  backend/src/main/java/com/festago/common/handler/GlobalExceptionHandler.java
  backend/src/main/java/com/festago/config/WebConfig.java
Labels: BE, ⚙️ 리팩터링

#741 [BE] feat: 관리자 로그아웃 API 추가 (#740)
  backend/src/main/java/com/festago/auth/presentation/AdminAuthController.java
  backend/src/test/java/com/festago/auth/presentation/AdminAuthControllerTest.java
Labels: BE, 📬 API

#742 [BE] feat: SchoolRegion 지역 추가 (#718)
  backend/src/main/java/com/festago/school/domain/SchoolRegion.java
Labels: BE

#744 [BE] School 생성, 수정에 누락된 필드 추가 (#731)
  backend/src/main/java/com/festago/admin/presentation/v1/dto/SchoolV1CreateRequest.java
  backend/src/main/java/com/festago/admin/presentation/v1/dto/SchoolV1UpdateRequest.java
  backend/src/main/java/com/festago/school/application/SchoolCommandService.java
  backend/src/main/java/com/festago/school/domain/School.java
  backend/src/main/java/com/festago/school/dto/SchoolCreateCommand.java
  backend/src/main/java/com/festago/school/dto/SchoolUpdateCommand.java
  backend/src/test/java/com/festago/acceptance/steps/AdminSchoolStepDefinitions.java
  backend/src/test/java/com/festago/admin/presentation/v1/AdminSchoolV1ControllerTest.java
  backend/src/test/java/com/festago/school/application/integration/SchoolCommandServiceIntegrationTest.java
  backend/src/test/java/com/festago/school/domain/SchoolTest.java
  backend/src/test/java/com/festago/support/SchoolFixture.java
Labels: BE, 🛠 수정, 📬 API

#695 [BE] feat: 새로운 FestivalCommandService 추가 (#684)
  backend/src/main/java/com/festago/admin/dto/FestivalV1CreateRequest.java
  backend/src/main/java/com/festago/admin/dto/FestivalV1UpdateRequest.java
  backend/src/main/java/com/festago/admin/presentation/AdminController.java
  backend/src/main/java/com/festago/admin/presentation/v1/AdminFestivalV1Controller.java
  backend/src/main/java/com/festago/common/exception/ErrorCode.java
  backend/src/main/java/com/festago/festival/application/FestivalQueryInfoEventListener.java
  backend/src/main/java/com/festago/festival/application/FestivalService.java
  backend/src/main/java/com/festago/festival/application/command/FestivalCommandFacadeService.java
  backend/src/main/java/com/festago/festival/application/command/FestivalCreateService.java
  backend/src/main/java/com/festago/festival/application/command/FestivalDeleteService.java
  backend/src/main/java/com/festago/festival/application/command/FestivalUpdateService.java
  backend/src/main/java/com/festago/festival/domain/Festival.java
  backend/src/main/java/com/festago/festival/domain/FestivalQueryInfo.java
  backend/src/main/java/com/festago/festival/domain/validator/FestivalDeleteValidator.java
  backend/src/main/java/com/festago/festival/domain/validator/FestivalUpdateValidator.java
  backend/src/main/java/com/festago/festival/domain/validator/school/ExistsFestivalSchoolDeleteValidator.java
  backend/src/main/java/com/festago/festival/dto/command/FestivalCreateCommand.java
  backend/src/main/java/com/festago/festival/dto/command/FestivalUpdateCommand.java
  backend/src/main/java/com/festago/festival/dto/event/FestivalCreatedEvent.java
  backend/src/main/java/com/festago/festival/dto/event/FestivalDeletedEvent.java
  backend/src/main/java/com/festago/festival/presentation/FestivalController.java
  backend/src/main/java/com/festago/festival/repository/FestivalInfoRepository.java
  backend/src/main/java/com/festago/festival/repository/FestivalRepository.java
  backend/src/main/java/com/festago/school/application/SchoolDeleteService.java
  backend/src/main/java/com/festago/school/domain/validator/SchoolDeleteValidator.java
  backend/src/main/java/com/festago/stage/application/FestivalStageServiceImpl.java
  backend/src/main/java/com/festago/stage/application/StageService.java
  backend/src/main/java/com/festago/stage/domain/validator/festival/ExistsStageFestivalDeleteValidator.java
  backend/src/main/java/com/festago/stage/domain/validator/festival/OutOfDateStageFestivalUpdateValidator.java
  backend/src/main/java/com/festago/stage/repository/StageRepository.java
  backend/src/main/java/com/festago/student/domain/validator/school/StudentSchoolDeleteValidator.java
  backend/src/test/java/com/festago/admin/presentation/v1/AdminFestivalV1ControllerTest.java
  backend/src/test/java/com/festago/festival/application/command/FestivalCreateServiceTest.java
  backend/src/test/java/com/festago/festival/application/command/FestivalDeleteServiceTest.java
  backend/src/test/java/com/festago/festival/application/command/FestivalUpdateServiceTest.java
  backend/src/test/java/com/festago/stage/application/FestivalStageServiceImplTest.java
  backend/src/test/java/com/festago/stage/application/StageServiceTest.java
  backend/src/test/java/com/festago/stage/domain/validator/festival/OutOfDateStageFestivalUpdateValidatorTest.java
  backend/src/test/java/com/festago/stage/repository/MemoryStageRepository.java
Labels: BE

#722 [AN/USER] feat: 학교 상세 페이지 구현 (#697)
  android/festago/data/src/main/java/com/festago/festago/data/di/singletonscope/RepositoryModule.kt
  android/festago/data/src/main/java/com/festago/festago/data/dto/school/SchoolInfoResponse.kt
  android/festago/data/src/main/java/com/festago/festago/data/dto/school/SocialMediaResponse.kt
  android/festago/data/src/main/java/com/festago/festago/data/repository/FakeSchool.kt
  android/festago/data/src/main/java/com/festago/festago/data/repository/FakeSchoolRepository.kt
  android/festago/domain/src/main/java/com/festago/festago/domain/model/school/SchoolInfo.kt
  android/festago/domain/src/main/java/com/festago/festago/domain/model/social/SocialMedia.kt
  android/festago/domain/src/main/java/com/festago/festago/domain/repository/SchoolRepository.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListFragment.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/schooldetail/ArtistAdapter.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/schooldetail/ArtistViewHolder.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/schooldetail/SchoolDetailFestivalViewHolder.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/schooldetail/SchoolDetailFragment.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/schooldetail/SchoolDetailViewModel.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/schooldetail/SchoolFestivalListAdapter.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/schooldetail/uistate/ArtistUiState.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/schooldetail/uistate/FestivalItemUiState.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/schooldetail/uistate/SchoolDetailUiState.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/schooldetail/uistate/SchoolUiState.kt
  android/festago/presentation/src/main/res/drawable/ic_back.xml
  android/festago/presentation/src/main/res/layout/fragment_school_detail.xml
  android/festago/presentation/src/main/res/layout/item_school_detail_artist.xml
  android/festago/presentation/src/main/res/layout/item_school_detail_festival.xml
  android/festago/presentation/src/main/res/layout/view_social_media.xml
Labels: AN, USER

#755 [BE] refactor: Validator hasBlank, isNegative 메서드 이름 변경 (#753)
  backend/src/main/java/com/festago/admin/domain/Admin.java
  backend/src/main/java/com/festago/admin/presentation/v1/AdminSchoolV1Controller.java
  backend/src/main/java/com/festago/common/util/Validator.java
  backend/src/main/java/com/festago/fcm/domain/MemberFCM.java
  backend/src/main/java/com/festago/festival/domain/Festival.java
  backend/src/main/java/com/festago/member/domain/Member.java
  backend/src/main/java/com/festago/school/domain/School.java
  backend/src/main/java/com/festago/student/domain/Student.java
  backend/src/main/java/com/festago/student/domain/StudentCode.java
  backend/src/main/java/com/festago/student/domain/VerificationCode.java
  backend/src/test/java/com/festago/common/util/ValidatorTest.java
Labels: BE, 🚨 우선순위上, ⚙️ 리팩터링

#756 [BE] feat: Artist 생성, 수정에 누락된 필드를 추가한다.(#732)
  backend/src/main/java/com/festago/admin/dto/ArtistCreateRequest.java
  backend/src/main/java/com/festago/admin/dto/ArtistUpdateRequest.java
  backend/src/main/java/com/festago/artist/application/ArtistCommandService.java
  backend/src/main/java/com/festago/artist/domain/Artist.java
  backend/src/test/java/com/festago/admin/presentation/v1/AdminArtistV1ControllerTest.java
  backend/src/test/java/com/festago/artist/application/integration/ArtistCommandServiceIntegrationTest.java
Labels: BE

#736 [AN/USER] feat: 축제 목록 화면 인기 축제 목록에 무한 스크롤을 적용한다(#735)
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListFragment.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListViewModel.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/festival/FestivalListPopularViewHolder.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/popularfestival/PopularFestivalViewPagerAdapter.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/popularfestival/foreground/PopularFestivalForegroundAdapter.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/uistate/FestivalListUiState.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/uistate/PopularFestivalUiState.kt
Labels: AN, USER
