Repository woowacourse-teams/2023-festa-go, pull requests merged in 2024-04, with the labels that each got.

#800 [AN/USER] feat: 축제 목록 화면 지역별 필터링 구현 (#768)
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListFragment.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListViewModel.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/bottomsheet/RegionAdapter.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/bottomsheet/RegionBottomSheetDialogFragment.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/bottomsheet/RegionItemViewHolder.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/festival/FestivalListAdapter.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/festival/FestivalListTabViewHolder.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/uistate/FestivalListUiState.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/uistate/FestivalTabUiState.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/uistate/SchoolRegionUiState.kt
  android/festago/presentation/src/main/res/drawable/bg_btn_region_check.xml
  android/festago/presentation/src/main/res/drawable/bg_btn_region_normal.xml
  android/festago/presentation/src/main/res/drawable/bg_region_bottom_sheet.xml
  android/festago/presentation/src/main/res/drawable/ic_pin_normal.xml
  android/festago/presentation/src/main/res/drawable/ic_pin_select.xml
  android/festago/presentation/src/main/res/drawable/selector_btn_region.xml
  android/festago/presentation/src/main/res/layout/fragment_region_bottom_sheet.xml
  android/festago/presentation/src/main/res/layout/item_festival_list_tab.xml
  android/festago/presentation/src/main/res/layout/item_region.xml
  android/festago/presentation/src/main/res/values/strings.xml
Labels: AN, USER

#832 fix: Artist 직렬화 ArtistQueryModel로 변환 후 직렬화 하도록 변경 (#831)
  backend/src/main/java/com/festago/artist/infrastructure/JsonArtistsSerializer.java
Labels: BE, 🚨 우선순위上, 🛠 수정

#823 [BE] feat: 북마크 기능 구현 (#787)
  backend/src/main/java/com/festago/artist/repository/ArtistRepository.java
  backend/src/main/java/com/festago/bookmark/application/ArtistBookmarkV1QueryService.java
  backend/src/main/java/com/festago/bookmark/application/FestivalBookmarkV1QueryService.java
  backend/src/main/java/com/festago/bookmark/application/SchoolBookmarkV1QueryService.java
  backend/src/main/java/com/festago/bookmark/application/command/ArtistBookmarkCommandService.java
  backend/src/main/java/com/festago/bookmark/application/command/BookmarkFacadeService.java
  backend/src/main/java/com/festago/bookmark/application/command/FestivalBookmarkCommandService.java
  backend/src/main/java/com/festago/bookmark/application/command/SchoolBookmarkCommandService.java
  backend/src/main/java/com/festago/bookmark/domain/Bookmark.java
  backend/src/main/java/com/festago/bookmark/domain/BookmarkType.java
  backend/src/main/java/com/festago/bookmark/dto/v1/ArtistBookmarkInfoV1Response.java
  backend/src/main/java/com/festago/bookmark/dto/v1/ArtistBookmarkV1Response.java
  backend/src/main/java/com/festago/bookmark/dto/v1/FestivalBookmarkV1Response.java
  backend/src/main/java/com/festago/bookmark/dto/v1/SchoolBookmarkInfoV1Response.java
  backend/src/main/java/com/festago/bookmark/dto/v1/SchoolBookmarkV1Response.java
  backend/src/main/java/com/festago/bookmark/presentation/v1/ArtistBookmarkV1Controller.java
  backend/src/main/java/com/festago/bookmark/presentation/v1/BookmarkManagementV1Controller.java
  backend/src/main/java/com/festago/bookmark/presentation/v1/FestivalBookmarkV1Controller.java
  backend/src/main/java/com/festago/bookmark/presentation/v1/SchoolBookmarkV1Controller.java
  backend/src/main/java/com/festago/bookmark/repository/BookmarkRepository.java
  backend/src/main/java/com/festago/bookmark/repository/FestivalBookmarkOrder.java
  backend/src/main/java/com/festago/bookmark/repository/v1/ArtistBookmarkV1QueryDslRepository.java
  backend/src/main/java/com/festago/bookmark/repository/v1/FestivalBookmarkV1QueryDslRepository.java
  backend/src/main/java/com/festago/bookmark/repository/v1/SchoolBookmarkV1QuerydslRepository.java
  backend/src/main/java/com/festago/common/exception/ErrorCode.java
  backend/src/main/java/com/festago/festival/repository/FestivalRepository.java
  backend/src/main/java/com/festago/member/repository/MemberRepository.java
  backend/src/main/java/com/festago/school/repository/SchoolRepository.java
  backend/src/main/resources/db/migration/V17__add_bookmark.sql
  backend/src/test/java/com/festago/artist/repository/MemoryArtistRepository.java
  backend/src/test/java/com/festago/bookmark/application/command/ArtistBookmarkCommandServiceTest.java
  backend/src/test/java/com/festago/bookmark/application/command/FestivalBookmarkCommandServiceTest.java
  backend/src/test/java/com/festago/bookmark/application/command/SchoolBookmarkCommandServiceTest.java
  backend/src/test/java/com/festago/bookmark/application/integration/ArtistBookmarkV1QueryServiceIntegrationTest.java
  backend/src/test/java/com/festago/bookmark/application/integration/FestivalBookmarkV1QueryServiceIntegrationTest.java
  backend/src/test/java/com/festago/bookmark/application/integration/SchoolBookmarkV1QueryServiceIntegrationTest.java
  backend/src/test/java/com/festago/bookmark/presentation/v1/ArtistBookmarkV1ControllerTest.java
  backend/src/test/java/com/festago/bookmark/presentation/v1/BookmarkManagementV1ControllerTest.java
  backend/src/test/java/com/festago/bookmark/presentation/v1/FestivalBookmarkV1ControllerTest.java
  backend/src/test/java/com/festago/bookmark/presentation/v1/SchoolBookmarkV1ControllerTest.java
  backend/src/test/java/com/festago/bookmark/repository/MemoryBookmarkRepository.java
  backend/src/test/java/com/festago/festival/repository/MemoryFestivalRepository.java
  backend/src/test/java/com/festago/member/repository/MemoryMemberRepository.java
  backend/src/test/java/com/festago/school/repository/MemorySchoolRepository.java
  backend/src/test/java/com/festago/school/repository/MemorySchoolRepositoryTest.java
  backend/src/test/java/com/festago/school/repository/SchoolRepositoryTest.java
  backend/src/test/java/com/festago/support/fixture/BookmarkFixture.java
Labels: BE, ☢️ DB, 📬 API, 🏗️ 기능

#822 [BE] refactor: stage 테스트 패키지에서 엔티티 생성을 픽스쳐를 사용하여 생성하도록 변경 (#813)
  backend/src/main/java/com/festago/artist/domain/ArtistsSerializer.java
  backend/src/test/java/com/festago/stage/application/command/StageCommandServiceIntegrationTest.java
  backend/src/test/java/com/festago/stage/application/command/StageCreateServiceTest.java
  backend/src/test/java/com/festago/stage/application/command/StageDeleteServiceTest.java
  backend/src/test/java/com/festago/stage/application/command/StageUpdateServiceTest.java
  backend/src/test/java/com/festago/stage/domain/validator/festival/OutOfDateStageFestivalUpdateValidatorTest.java
  backend/src/test/java/com/festago/support/fixture/FestivalQueryInfoFixture.java
Labels: BE, ⚙️ 리팩터링

#840 [BE] feat: AdminArtistV1Controller 아티스트 조회 응답 필드 수정, 검색 기능 페이징 추가 (#838)
  backend/src/main/java/com/festago/admin/application/AdminArtistV1QueryService.java
  backend/src/main/java/com/festago/admin/dto/artist/AdminArtistV1Response.java
  backend/src/main/java/com/festago/admin/presentation/v1/AdminArtistV1Controller.java
  backend/src/main/java/com/festago/admin/repository/AdminArtistV1QueryDslRepository.java
  backend/src/main/java/com/festago/artist/repository/ArtistRepository.java
  backend/src/main/java/com/festago/common/querydsl/SearchCondition.java
  backend/src/test/java/com/festago/admin/application/integration/AdminArtistV1QueryServiceIntegrationTest.java
  backend/src/test/java/com/festago/admin/application/integration/ArtistV1QueryServiceIntegrationTest.java
  backend/src/test/java/com/festago/admin/presentation/v1/AdminArtistV1ControllerTest.java
  backend/src/test/java/com/festago/artist/repository/MemoryArtistRepository.java
Labels: BE, ADMIN, ⚙️ 리팩터링, 🏗️ 기능

#836 [BE] refactor: school 테스트 패키지에서 엔티티 생성을 픽스쳐를 사용하여 생성하도록 변경 (#812)
  backend/src/main/java/com/festago/school/repository/SchoolRepository.java
  backend/src/test/java/com/festago/school/application/SchoolCommandServiceTest.java
  backend/src/test/java/com/festago/school/application/integration/SchoolV1QueryServiceIntegrationTest.java
  backend/src/test/java/com/festago/school/presentation/v1/SchoolV1ControllerTest.java
Labels: BE, ⚙️ 리팩터링, 🧪 테스트

#837 [BE] refactor: festival 테스트 패키지에서 엔티티 생성을 픽스쳐를 사용하여 생성하도록 변경 (#814)
  backend/src/test/java/com/festago/festival/application/integration/command/FestivalCreateServiceTest.java
  backend/src/test/java/com/festago/festival/application/integration/command/FestivalDeleteServiceTest.java
  backend/src/test/java/com/festago/festival/application/integration/command/FestivalUpdateServiceTest.java
  backend/src/test/java/com/festago/festival/application/integration/query/FestivalDetailV1QueryServiceIntegrationTest.java
  backend/src/test/java/com/festago/festival/application/integration/query/FestivalSearchV1QueryServiceTest.java
  backend/src/test/java/com/festago/festival/application/integration/query/FestivalV1QueryServiceIntegrationTest.java
  backend/src/test/java/com/festago/festival/application/integration/query/PopularFestivalV1QueryServiceIntegrationTest.java
Labels: BE, ⚙️ 리팩터링, 🧪 테스트

#845 fix: commons-logging.jar 로그 제거 및 빌드 시 제외 (#843)
  backend/build.gradle.kts
Labels: BE, 🛠 수정

#841 [BE] refactor: MemoryRepository를 추상화하여 중복 제거 (#819)
  backend/src/test/java/com/festago/admin/repository/MemoryAdminRepository.java
  backend/src/test/java/com/festago/artist/repository/MemoryArtistRepository.java
  backend/src/test/java/com/festago/bookmark/repository/MemoryBookmarkRepository.java
  backend/src/test/java/com/festago/festival/repository/MemoryFestivalQueryInfoRepository.java
  backend/src/test/java/com/festago/festival/repository/MemoryFestivalRepository.java
  backend/src/test/java/com/festago/member/repository/MemoryMemberRepository.java
  backend/src/test/java/com/festago/school/repository/MemorySchoolRepository.java
  backend/src/test/java/com/festago/stage/repository/MemoryStageArtistRepository.java
  backend/src/test/java/com/festago/stage/repository/MemoryStageRepository.java
  backend/src/test/java/com/festago/support/AbstractMemoryRepository.java
Labels: BE, ⚙️ 리팩터링, 🧪 테스트

#842 [AN/USER] feat: 학교 상세 화면과 축제 상세, 아티스트 상세 연결(#835)
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/schooldetail/SchoolDetailEvent.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/schooldetail/SchoolDetailFragment.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/schooldetail/SchoolDetailViewModel.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/schooldetail/uistate/ArtistUiState.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/schooldetail/uistate/FestivalItemUiState.kt
  android/festago/presentation/src/main/res/layout/item_school_detail_artist.xml
  android/festago/presentation/src/main/res/layout/item_school_detail_festival.xml
  android/festago/presentation/src/main/res/navigation/festival_list.xml
Labels: AN, USER

#851 [BE] refactor: 테스트 코드에 엔티티 생성 픽스쳐 사용하도록 변경 및 Deprecated 클래스, 메서드 제거 (#810)
  backend/src/main/java/com/festago/auth/application/AdminAuthService.java
  backend/src/main/java/com/festago/auth/dto/AdminLoginRequest.java
  backend/src/main/java/com/festago/auth/dto/AdminSignupRequest.java
  backend/src/main/java/com/festago/auth/dto/AdminSignupResponse.java
  backend/src/main/java/com/festago/auth/presentation/AdminAuthController.java
  backend/src/main/java/com/festago/member/domain/Member.java
  backend/src/main/java/com/festago/stage/domain/Stage.java
  backend/src/test/java/com/festago/acceptance/steps/AdminStepDefinitions.java
  backend/src/test/java/com/festago/artist/application/integration/ArtistSearchStageCountV1QueryServiceIntegrationTest.java
  backend/src/test/java/com/festago/artist/application/integration/ArtistSearchV1QueryServiceIntegrationTest.java
  backend/src/test/java/com/festago/auth/application/AdminAuthServiceTest.java
  backend/src/test/java/com/festago/auth/presentation/AdminAuthControllerTest.java
  backend/src/test/java/com/festago/bookmark/application/command/ArtistBookmarkCommandServiceTest.java
  backend/src/test/java/com/festago/bookmark/application/command/FestivalBookmarkCommandServiceTest.java
  backend/src/test/java/com/festago/bookmark/application/command/SchoolBookmarkCommandServiceTest.java
  backend/src/test/java/com/festago/fcm/repository/MemberFCMRepositoryTest.java
  backend/src/test/java/com/festago/festival/application/FestivalQueryInfoArtistRenewServiceTest.java
  backend/src/test/java/com/festago/festival/application/integration/command/FestivalDeleteServiceTest.java
  backend/src/test/java/com/festago/festival/application/integration/query/FestivalSearchV1QueryServiceTest.java
  backend/src/test/java/com/festago/student/application/StudentServiceTest.java
  backend/src/test/java/com/festago/ticketing/domain/MemberTicketTest.java
Labels: BE, ⚙️ 리팩터링, 🧪 테스트

#850 [BE] feat: 관리자 학교 응답 누락된 필드 추가, 관리자 아티스트 응답 createdAt, updatedAt 필드 추가 (#849)
  backend/src/main/java/com/festago/admin/dto/artist/AdminArtistV1Response.java
  backend/src/main/java/com/festago/admin/dto/school/AdminSchoolV1Response.java
  backend/src/main/java/com/festago/admin/repository/AdminArtistV1QueryDslRepository.java
  backend/src/main/java/com/festago/admin/repository/AdminSchoolV1QueryDslRepository.java
  backend/src/main/java/com/festago/artist/domain/Artist.java
  backend/src/test/java/com/festago/admin/presentation/v1/AdminArtistV1ControllerTest.java
  backend/src/test/java/com/festago/admin/presentation/v1/AdminSchoolV1ControllerTest.java
Labels: BE, ADMIN, 📬 API, 🏗️ 기능

#848 [BE] feat: 소셜미디어 CRUD 기능 추가 (#802)
  backend/src/main/java/com/festago/admin/application/AdminSocialMediaV1QueryService.java
  backend/src/main/java/com/festago/admin/dto/socialmedia/AdminSocialMediaV1Response.java
  backend/src/main/java/com/festago/admin/dto/socialmedia/SocialMediaCreateV1Request.java
  backend/src/main/java/com/festago/admin/dto/socialmedia/SocialMediaUpdateV1Request.java
  backend/src/main/java/com/festago/admin/presentation/v1/AdminSocialMediaV1Controller.java
  backend/src/main/java/com/festago/admin/repository/AdminSocialMediaV1QueryDslRepository.java
  backend/src/main/java/com/festago/common/exception/ErrorCode.java
  backend/src/main/java/com/festago/socialmedia/application/SocialMediaCommandService.java
  backend/src/main/java/com/festago/socialmedia/domain/OwnerType.java
  backend/src/main/java/com/festago/socialmedia/domain/SocialMedia.java
  backend/src/main/java/com/festago/socialmedia/dto/command/SocialMediaCreateCommand.java
  backend/src/main/java/com/festago/socialmedia/dto/command/SocialMediaUpdateCommand.java
  backend/src/main/java/com/festago/socialmedia/repository/SocialMediaRepository.java
  backend/src/test/java/com/festago/admin/application/integration/AdminSocialMediaV1QueryServiceIntegrationTest.java
  backend/src/test/java/com/festago/admin/presentation/v1/AdminSocialMediaV1ControllerTest.java
  backend/src/test/java/com/festago/socialmedia/application/SocialMediaCommandServiceTest.java
  backend/src/test/java/com/festago/socialmedia/repository/MemorySocialMediaRepository.java
Labels: BE, ADMIN, 📬 API, 🏗️ 기능

#847 [AN/USER] feat: 앱 아이콘 및 스플래시 화면 추가 및 원격 버전관리(#779)
  android/festago/app/build.gradle.kts
  android/festago/app/src/main/AndroidManifest.xml
  android/festago/app/src/main/ic_festago_logo-playstore.png
  android/festago/app/src/main/ic_festago_logo_playstore.png
  android/festago/common/build.gradle.kts
  android/festago/data-legacy/build.gradle.kts
  android/festago/data/build.gradle.kts
  android/festago/presentation-legacy/build.gradle.kts
  android/festago/presentation/build.gradle.kts
  android/festago/presentation/src/main/AndroidManifest.xml
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/splash/SplashActivity.kt
  android/festago/presentation/src/main/res/drawable-v24/ic_launcher_foreground.xml
  android/festago/presentation/src/main/res/drawable/ic_festago_text_logo.xml
  android/festago/presentation/src/main/res/drawable/ic_launcher_background.xml
  android/festago/presentation/src/main/res/layout/activity_splash.xml
  android/festago/presentation/src/main/res/layout/fragment_artist_detail.xml
  android/festago/presentation/src/main/res/layout/fragment_festival_detail.xml
  android/festago/presentation/src/main/res/layout/fragment_festival_list.xml
  android/festago/presentation/src/main/res/layout/fragment_school_detail.xml
  android/festago/presentation/src/main/res/layout/item_artist_detail_artist.xml
  android/festago/presentation/src/main/res/layout/item_artist_detail_festival.xml
  android/festago/presentation/src/main/res/layout/item_festival_detail_stage_artist.xml
  android/festago/presentation/src/main/res/layout/item_festival_list_artist.xml
  android/festago/presentation/src/main/res/layout/item_festival_list_festival.xml
  android/festago/presentation/src/main/res/layout/item_popular_festival_background.xml
  android/festago/presentation/src/main/res/layout/item_popular_festival_foreground.xml
  android/festago/presentation/src/main/res/layout/item_school_detail_artist.xml
  android/festago/presentation/src/main/res/layout/item_school_detail_festival.xml
  android/festago/presentation/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/festago/presentation/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/festago/presentation/src/main/res/mipmap-hdpi/ic_launcher.png
  android/festago/presentation/src/main/res/mipmap-hdpi/ic_launcher.webp
  android/festago/presentation/src/main/res/mipmap-hdpi/ic_launcher_background.png
  android/festago/presentation/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  android/festago/presentation/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  android/festago/presentation/src/main/res/mipmap-mdpi/ic_launcher.webp
  android/festago/presentation/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  android/festago/presentation/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/festago/presentation/src/main/res/mipmap-xhdpi/ic_launcher.webp
  android/festago/presentation/src/main/res/mipmap-xhdpi/ic_launcher_background.png
  android/festago/presentation/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  android/festago/presentation/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  android/festago/presentation/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/festago/presentation/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  android/festago/presentation/src/main/res/mipmap-xxhdpi/ic_launcher_background.png
  android/festago/presentation/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  android/festago/presentation/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  android/festago/presentation/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/festago/presentation/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  android/festago/presentation/src/main/res/mipmap-xxxhdpi/ic_launcher_background.png
  android/festago/presentation/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  android/festago/presentation/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  android/festago/presentation/src/main/res/values-night/themes.xml
  android/festago/presentation/src/main/res/values/strings.xml
  android/festago/presentation/src/main/res/values/themes.xml
Labels: AN, USER

#856 [BE] feat: AdminStageV1Controller에 공연 단건 조회 기능 추가 (#855)
  backend/src/main/java/com/festago/admin/application/AdminStageV1QueryService.java
  backend/src/main/java/com/festago/admin/presentation/v1/AdminStageV1Controller.java
  backend/src/main/java/com/festago/admin/repository/AdminStageV1QueryDslRepository.java
  backend/src/test/java/com/festago/admin/application/integration/AdminStageV1QueryServiceIntegrationTest.java
  backend/src/test/java/com/festago/admin/presentation/v1/AdminStageV1ControllerTest.java
Labels: BE, ADMIN, 📬 API, 🏗️ 기능

#858 [BE] fix: 공연 삭제 메서드 순서 변경하여 외래키 제약 에러 수정 (#857)
  backend/src/main/java/com/festago/stage/application/command/StageDeleteService.java
Labels: BE, 🛠 수정

#872 [BE] fix: ArtistBookmarkInfoV1Response에 아티스트 식별자 추가 (#869)
  backend/src/main/java/com/festago/bookmark/application/ArtistBookmarkV1QueryService.java
  backend/src/main/java/com/festago/bookmark/dto/v1/ArtistBookmarkInfoV1Response.java
  backend/src/main/java/com/festago/bookmark/repository/v1/ArtistBookmarkV1QueryDslRepository.java
Labels: BE, 🚨 우선순위上, 🛠 수정, 📬 API

#860 [BE] refactor: MockData 설정 로직 리팩터링 및 테스트 속도 개선 (#839)
  backend/src/main/java/com/festago/festival/domain/FestivalDuration.java
  backend/src/main/java/com/festago/mock/CommandLineAppStartupRunner.java
  backend/src/main/java/com/festago/mock/MockDataInitialScheduler.java
  backend/src/main/java/com/festago/mock/MockDataService.java
  backend/src/main/java/com/festago/mock/MockDataStartupInitializer.java
  backend/src/main/java/com/festago/mock/MockFestivalDateGenerator.java
  backend/src/main/java/com/festago/mock/RandomMockFestivalDateGenerator.java
  backend/src/main/java/com/festago/mock/application/MockDataService.java
  backend/src/main/java/com/festago/mock/domain/MockArtist.java
  backend/src/main/java/com/festago/mock/domain/MockArtistsGenerator.java
  backend/src/main/java/com/festago/mock/domain/MockFestivalDurationGenerator.java
  backend/src/main/java/com/festago/mock/domain/MockFestivalsGenerator.java
  backend/src/main/java/com/festago/mock/domain/MockSchoolsGenerator.java
  backend/src/main/java/com/festago/mock/domain/MockStageArtistsGenerator.java
  backend/src/main/java/com/festago/mock/domain/MockStagesGenerator.java
  backend/src/main/java/com/festago/mock/domain/RandomMockFestivalDurationGenerator.java
  backend/src/main/java/com/festago/mock/repository/ForMockFestivalInfoRepository.java
  backend/src/main/java/com/festago/mock/repository/ForMockStageQueryInfoRepository.java
  backend/src/main/java/com/festago/stage/domain/StageArtist.java
  backend/src/test/java/com/festago/mock/application/MockDataServiceTest.java
  backend/src/test/java/com/festago/mock/application/integration/MockDataServiceIntegrationTest.java
  backend/src/test/java/com/festago/mock/config/MockDataConfig.java
  backend/src/test/java/com/festago/mock/domain/MockArtistsGeneratorTest.java
  backend/src/test/java/com/festago/mock/domain/MockFestivalsGeneratorTest.java
  backend/src/test/java/com/festago/mock/domain/MockSchoolsGeneratorTest.java
  backend/src/test/java/com/festago/mock/domain/MockStageArtistsGeneratorTest.java
  backend/src/test/java/com/festago/mock/domain/MockStagesGeneratorTest.java
Labels: BE, ⚙️ 리팩터링

#866 [BE] build: Thymeleaf 의존 제거 (#865)
  backend/build.gradle.kts
Labels: BE

#884 [BE] fix: 학교의 축제 목록을 조회할 때 last 여부가 반대로 반환되는 버그를 수정 (#883)
  backend/src/main/java/com/festago/school/repository/v1/SchoolV1QueryDslRepository.java
  backend/src/test/java/com/festago/school/application/integration/SchoolV1QueryServiceIntegrationTest.java
Labels: BE, 🛠 수정

#881 [BE] feat: Festival 엔티티 startDate, endDate 필드 FestivalDuration 값 타입 변경 및 thumbnail 필드명 변경 (#880)
  backend/src/main/java/com/festago/admin/repository/AdminFestivalDetailV1QueryDslRepository.java
  backend/src/main/java/com/festago/admin/repository/AdminFestivalV1QueryDslRepository.java
  backend/src/main/java/com/festago/artist/repository/ArtistDetailV1QueryDslRepository.java
  backend/src/main/java/com/festago/bookmark/repository/v1/FestivalBookmarkV1QueryDslRepository.java
  backend/src/main/java/com/festago/festival/application/command/FestivalCreateService.java
  backend/src/main/java/com/festago/festival/application/command/FestivalUpdateService.java
  backend/src/main/java/com/festago/festival/domain/Festival.java
  backend/src/main/java/com/festago/festival/domain/FestivalDuration.java
  backend/src/main/java/com/festago/festival/dto/command/FestivalCreateCommand.java
  backend/src/main/java/com/festago/festival/repository/ArtistFestivalSearchV1QueryDslRepository.java
  backend/src/main/java/com/festago/festival/repository/FestivalDetailV1QueryDslRepository.java
  backend/src/main/java/com/festago/festival/repository/FestivalV1QueryDslRepository.java
  backend/src/main/java/com/festago/festival/repository/PopularFestivalV1QueryDslRepository.java
  backend/src/main/java/com/festago/festival/repository/RecentSchoolFestivalV1QueryDslRepository.java
  backend/src/main/java/com/festago/festival/repository/SchoolFestivalSearchV1QueryDslRepository.java
  backend/src/main/java/com/festago/mock/domain/MockFestivalsGenerator.java
  backend/src/main/java/com/festago/school/repository/v1/SchoolV1QueryDslRepository.java
  backend/src/main/java/com/festago/ticketing/dto/MemberTicketFestivalResponse.java
  backend/src/test/java/com/festago/admin/presentation/v1/AdminFestivalV1ControllerTest.java
  backend/src/test/java/com/festago/festival/application/integration/command/FestivalCreateServiceTest.java
  backend/src/test/java/com/festago/festival/application/integration/command/FestivalUpdateServiceTest.java
  backend/src/test/java/com/festago/festival/domain/FestivalDurationTest.java
  backend/src/test/java/com/festago/festival/domain/FestivalTest.java
  backend/src/test/java/com/festago/stage/domain/validator/festival/OutOfDateStageFestivalUpdateValidatorTest.java
  backend/src/test/java/com/festago/support/fixture/FestivalFixture.java
Labels: BE, ⚙️ 리팩터링

#882 [AN/USER] feat: 애니메이션 수정 축제 로딩 개선(#876)
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListFragment.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/festival/FestivalListMoreItemViewHolder.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/uistate/FestivalMoreItemUiState.kt
  android/festago/presentation/src/main/res/anim/fade_in.xml
  android/festago/presentation/src/main/res/anim/fade_out.xml
  android/festago/presentation/src/main/res/anim/no_anim.xml
  android/festago/presentation/src/main/res/anim/slide_in.xml
  android/festago/presentation/src/main/res/anim/slide_out.xml
  android/festago/presentation/src/main/res/layout/fragment_search.xml
  android/festago/presentation/src/main/res/layout/item_artist_detail_festival.xml
  android/festago/presentation/src/main/res/layout/item_festival_list_popular.xml
  android/festago/presentation/src/main/res/layout/item_festival_list_tab.xml
  android/festago/presentation/src/main/res/navigation/festival_list.xml
Labels: AN, USER

#877 [AN/USER] feat: 디자인 변경 사항을 적용한다(#868)
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/artistdetail/ArtistDetailFragment.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/artistdetail/uistate/ArtistDetailUiState.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/festivaldetail/FestivalDetailEvent.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/festivaldetail/FestivalDetailFragment.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/festivaldetail/FestivalDetailViewModel.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/festivaldetail/uiState/FestivalDetailUiState.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/festivaldetail/uiState/FestivalUiState.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListFragment.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/festival/FestivalListAdapter.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/festival/FestivalListEmptyItemViewHolder.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/uistate/FestivalEmptyItemUiState.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/schooldetail/uistate/SchoolDetailUiState.kt
  android/festago/presentation/src/main/res/drawable/ic_pin_location.xml
  android/festago/presentation/src/main/res/layout/fragment_artist_detail.xml
  android/festago/presentation/src/main/res/layout/fragment_festival_detail.xml
  android/festago/presentation/src/main/res/layout/fragment_school_detail.xml
  android/festago/presentation/src/main/res/layout/item_festival_list_empty_item.xml
  android/festago/presentation/src/main/res/navigation/book_mark.xml
  android/festago/presentation/src/main/res/navigation/festival_list.xml
  android/festago/presentation/src/main/res/values/strings.xml
Labels: AN, USER

#896 [BE] fix: 학교 검색 시 발생하는 NPE 수정 (#895)
  backend/src/main/java/com/festago/festival/application/QueryDslSchoolUpcomingFestivalStartDateV1QueryService.java
  backend/src/main/java/com/festago/festival/repository/RecentSchoolFestivalV1QueryDslRepository.java
  backend/src/main/java/com/festago/school/application/v1/SchoolSearchUpcomingFestivalV1QueryService.java
  backend/src/main/java/com/festago/school/application/v1/SchoolTotalSearchV1QueryService.java
  backend/src/main/java/com/festago/school/application/v1/SchoolUpcomingFestivalStartDateV1QueryService.java
  backend/src/main/java/com/festago/school/dto/v1/SchoolTotalSearchV1Response.java
  backend/src/main/java/com/festago/school/dto/v1/SchoolUpcomingFestivalStartDateV1Response.java
  backend/src/test/java/com/festago/festival/application/QueryDslSchoolSearchRecentFestivalV1QueryServiceIntegrationTest.java
Labels: BE, 🚨 우선순위上, 🛠 수정

#899 [AN/USER] feat: 에러 화면, 새로고침 적용 (#898)
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/artistdetail/ArtistDetailFragment.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/artistdetail/ArtistDetailViewModel.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/artistdetail/uistate/ArtistDetailUiState.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/festivaldetail/FestivalDetailFragment.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/festivaldetail/FestivalDetailViewModel.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/festivaldetail/uiState/FestivalDetailUiState.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListFragment.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListViewModel.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/uistate/FestivalListUiState.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/schooldetail/SchoolDetailFragment.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/schooldetail/SchoolDetailViewModel.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/schooldetail/uistate/SchoolDetailUiState.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/search/SearchFragment.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/search/SearchViewModel.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/search/uistate/SearchUiState.kt
  android/festago/presentation/src/main/res/layout/fragment_artist_detail.xml
  android/festago/presentation/src/main/res/layout/fragment_festival_detail.xml
  android/festago/presentation/src/main/res/layout/fragment_festival_list.xml
  android/festago/presentation/src/main/res/layout/fragment_school_detail.xml
  android/festago/presentation/src/main/res/layout/fragment_search.xml
Labels: AN, USER

#892 [BE] feat: 관리자용 Actuator API 추가 (#890)
  backend/src/main/java/com/festago/admin/application/AdminActuatorProxyService.java
  backend/src/main/java/com/festago/admin/infrastructure/ActuatorProxyClient.java
  backend/src/main/java/com/festago/admin/infrastructure/AdminActuatorProxyErrorHandler.java
  backend/src/main/java/com/festago/admin/presentation/AdminActuatorController.java
  backend/src/main/java/com/festago/common/exception/ErrorCode.java
  backend/src/test/java/com/festago/admin/infrastructure/ActuatorProxyClientTest.java
  backend/src/test/java/com/festago/admin/presentation/AdminActuatorControllerTest.java
  backend/src/test/resources/application-test.yml
Labels: BE, ADMIN, 📬 API, 🏗️ 기능

#910 [BE] feat: OpenID Connect 방식의 인증 기능 추가 (#909)
  backend/src/main/java/com/festago/auth/application/command/MemberAuthFacadeService.java
  backend/src/main/java/com/festago/auth/config/AuthConfig.java
  backend/src/main/java/com/festago/auth/domain/OpenIdClient.java
  backend/src/main/java/com/festago/auth/domain/OpenIdClients.java
  backend/src/main/java/com/festago/auth/domain/OpenIdNonceValidator.java
  backend/src/main/java/com/festago/auth/domain/OpenIdUserInfoProvider.java
  backend/src/main/java/com/festago/auth/domain/UserInfo.java
  backend/src/main/java/com/festago/auth/dto/KakaoUserInfo.java
  backend/src/main/java/com/festago/auth/dto/v1/OpenIdLoginV1Request.java
  backend/src/main/java/com/festago/auth/infrastructure/CachedOpenIdKeyProvider.java
  backend/src/main/java/com/festago/auth/infrastructure/FestagoOpenIdClient.java
  backend/src/main/java/com/festago/auth/infrastructure/KakaoOpenIdClient.java
  backend/src/main/java/com/festago/auth/infrastructure/KakaoOpenIdJwksClient.java
  backend/src/main/java/com/festago/auth/infrastructure/KakaoOpenIdJwksErrorHandler.java
  backend/src/main/java/com/festago/auth/infrastructure/KakaoOpenIdPublicKeyLocator.java
  backend/src/main/java/com/festago/auth/infrastructure/KakaoOpenIdUserInfoProvider.java
  backend/src/main/java/com/festago/auth/infrastructure/NoopOpenIdNonceValidator.java
  backend/src/main/java/com/festago/auth/presentation/v1/MemberAuthV1Controller.java
  backend/src/main/java/com/festago/common/exception/ErrorCode.java
  backend/src/test/java/com/festago/auth/infrastructure/CachedOpenIdKeyProviderTest.java
  backend/src/test/java/com/festago/auth/infrastructure/KakaoOpenIdJwksClientTest.java
  backend/src/test/java/com/festago/auth/infrastructure/KakaoOpenIdUserInfoProviderTest.java
  backend/src/test/java/com/festago/auth/presentation/v1/MemberAuthV1ControllerTest.java
Labels: BE, 📬 API, 🏗️ 기능
