Repository woowacourse-teams/2023-festa-go, pull requests merged in 2024-01, with the labels that each got.

#642 [BE] feat: CD 작업 수행 시, 기존 CD 작업의 실행을 취소하여 동시에 CD가 되는 것을 방지 (#641)
  .github/workflows/cd-back-dev.yml
Labels: 💯 BE, 🏢 인프라

#644 [BE] feat: 의존성을 정리한다(#643)
  backend/src/main/java/com/festago/admin/presentation/AdminController.java
  backend/src/main/java/com/festago/admin/presentation/AdminViewController.java
  backend/src/main/java/com/festago/auth/AuthInterceptor.java
  backend/src/main/java/com/festago/auth/AuthenticateContext.java
  backend/src/main/java/com/festago/auth/RoleArgumentResolver.java
  backend/src/main/java/com/festago/auth/config/LoginConfig.java
  backend/src/main/java/com/festago/auth/dto/event/MemberDeleteEvent.java
  backend/src/main/java/com/festago/auth/dto/event/MemberRegisterEvent.java
  backend/src/main/java/com/festago/auth/presentation/AdminAuthController.java
  backend/src/main/java/com/festago/auth/presentation/AuthController.java
  backend/src/main/java/com/festago/common/exception/ErrorCode.java
  backend/src/main/java/com/festago/common/filter/ErrorFilter.java
  backend/src/main/java/com/festago/common/handler/GlobalExceptionHandler.java
  backend/src/main/java/com/festago/entry/presentation/MemberEntranceController.java
  backend/src/main/java/com/festago/entry/presentation/StaffMemberTicketController.java
  backend/src/main/java/com/festago/fcm/application/MemberDeletionEventListener.java
  backend/src/main/java/com/festago/fcm/application/MemberFCMService.java
  backend/src/main/java/com/festago/fcm/application/MemberRegisterEventListener.java
  backend/src/main/java/com/festago/fcm/repository/MemberFCMRepository.java
  backend/src/main/java/com/festago/festival/application/FestivalService.java
  backend/src/main/java/com/festago/festival/application/FestivalStageService.java
  backend/src/main/java/com/festago/festival/dto/DetailFestivalResponse.java
  backend/src/main/java/com/festago/festival/dto/FestivalDetailResponse.java
  backend/src/main/java/com/festago/festival/dto/FestivalDetailStageResponse.java
  backend/src/main/java/com/festago/festival/dto/FestivalDetailTicketResponse.java
  backend/src/main/java/com/festago/festival/presentation/FestivalController.java
  backend/src/main/java/com/festago/member/presentation/MemberController.java
  backend/src/main/java/com/festago/school/presentation/SchoolController.java
  backend/src/main/java/com/festago/stage/application/FestivalStageServiceImpl.java
  backend/src/main/java/com/festago/stage/presentation/StageController.java
  backend/src/main/java/com/festago/student/presentation/StudentController.java
  backend/src/main/java/com/festago/ticket/domain/ReservationSequence.java
  backend/src/main/java/com/festago/ticket/domain/Ticket.java
  backend/src/main/java/com/festago/ticket/domain/TicketReserveInfo.java
  backend/src/main/java/com/festago/ticketing/application/TicketingService.java
  backend/src/main/java/com/festago/ticketing/domain/MemberTicket.java
  backend/src/main/java/com/festago/ticketing/presentation/MemberTicketController.java
  backend/src/test/java/com/festago/acceptance/EntryPoint.java
  backend/src/test/java/com/festago/acceptance/steps/ExampleStep.java
  backend/src/test/java/com/festago/acceptance/steps/ExampleStep2.java
  backend/src/test/java/com/festago/fcm/application/MemberFCMServiceTest.java
  backend/src/test/java/com/festago/festival/application/FestivalServiceTest.java
  backend/src/test/java/com/festago/festival/application/integration/FestivalServiceIntegrationTest.java
  backend/src/test/java/com/festago/presentation/FestivalControllerTest.java
  backend/src/test/java/com/festago/presentation/auth/AuthControllerTest.java
  backend/src/test/java/com/festago/presentation/auth/RoleArgumentResolverTest.java
  backend/src/test/java/com/festago/stage/application/FestivalStageServiceImplTest.java
  backend/src/test/java/com/festago/support/CustomWebMvcTest.java
  backend/src/test/java/com/festago/support/MockAuthExtractor.java
  backend/src/test/java/com/festago/support/MockAuthTestExecutionListener.java
  backend/src/test/java/com/festago/support/MockEventPublisherConfig.java
  backend/src/test/java/com/festago/support/TestAuthConfig.java
  backend/src/test/java/com/festago/ticket/domain/ReservationSequenceTest.java
  backend/src/test/java/com/festago/ticket/domain/TicketTest.java
  backend/src/test/java/com/festago/ticketing/domain/MemberTicketTest.java
  backend/src/test/resources/features/example.feature
Labels: 💯 BE, ⚙️ 리팩터링

#647 feat: Controller 단위 테스트에서 Service 클래스 Mock 빈으로 자동 등록하도록 변경 (#646)
  backend/src/test/java/com/festago/support/CustomWebMvcTest.java
  backend/src/test/java/com/festago/support/MockAllServiceBeanFactoryPostProcessor.java
  backend/src/test/java/com/festago/support/MockAllServiceConfig.java
  backend/src/test/java/com/festago/support/ResetMockTestExecutionListener.java
Labels: 💯 BE, ⚙️ 리팩터링, 🧪 테스트

#653 fix: AdminAuthController API 경로 수정 (#652)
  backend/src/main/java/com/festago/auth/presentation/AdminAuthController.java
  backend/src/test/java/com/festago/auth/presentation/AdminAuthControllerTest.java
Labels: BE, 🚨 우선순위上, 🛠 수정

#663 [BE] feat: CI 스크립트 대상 브랜치 feat/** 추가 (#662)
  .github/workflows/ci-back.yml
Labels: BE, 🏢 인프라, 🛠 수정

#670 [AN/USER] feat: 안드로이드 메인 화면 하단을 구성한다. (#668)
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FakeFestivals.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListFragment.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/festival/FestivalListAdapter.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/festival/FestivalListFestivalViewHolder.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/festival/FestivalListPopularViewHolder.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/festival/FestivalListTabViewHolder.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/festival/FestivalListViewHolder.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/festival/artistlist/ArtistAdapter.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/festival/artistlist/ArtistViewHolder.kt
  android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/uistate/FestivalTabUiState.kt
  android/festago/presentation/src/main/res/drawable/bg_festival_list_dday_in_progress.xml
  android/festago/presentation/src/main/res/drawable/bg_festival_list_festival.xml
  android/festago/presentation/src/main/res/layout/fragment_festival_list.xml
  android/festago/presentation/src/main/res/layout/item_festival_list_artist.xml
  android/festago/presentation/src/main/res/layout/item_festival_list_festival.xml
  android/festago/presentation/src/main/res/layout/item_festival_list_popular.xml
  android/festago/presentation/src/main/res/layout/item_festival_list_tab.xml
  android/festago/presentation/src/main/res/values/colors.xml
  android/festago/presentation/src/main/res/values/strings.xml
Labels: AN, USER

#667 feat: 축제 목록 조회 구현 (#658)
  backend/src/main/java/com/festago/artist/repository/ArtistRepository.java
  backend/src/main/java/com/festago/common/exception/ErrorCode.java
  backend/src/main/java/com/festago/common/exception/dto/ErrorResponse.java
  backend/src/main/java/com/festago/festival/application/FestivalV1QueryService.java
  backend/src/main/java/com/festago/festival/domain/FestivalInfoSerializer.java
  backend/src/main/java/com/festago/festival/domain/FestivalQueryInfo.java
  backend/src/main/java/com/festago/festival/dto/FestivalV1QueryRequest.java
  backend/src/main/java/com/festago/festival/dto/FestivalV1Response.java
  backend/src/main/java/com/festago/festival/dto/SchoolV1Response.java
  backend/src/main/java/com/festago/festival/infrastructure/FestivalInfoSerializerImpl.java
  backend/src/main/java/com/festago/festival/presentation/v1/FestivalV1Controller.java
  backend/src/main/java/com/festago/festival/repository/FestivalInfoRepository.java
  backend/src/main/java/com/festago/festival/repository/FestivalRepositoryCustom.java
  backend/src/main/java/com/festago/festival/repository/FestivalRepositoryCustomImpl.java
  backend/src/main/java/com/festago/festival/repository/FestivalSearchCondition.java
  backend/src/main/java/com/festago/festival/repository/FestivalV1QueryDslRepository.java
  backend/src/main/java/com/festago/festival/repository/OldFestivalRepository.java
  backend/src/main/java/com/festago/school/domain/School.java
  backend/src/main/java/com/festago/school/domain/SchoolRegion.java
  backend/src/main/java/com/festago/school/repository/SchoolRepository.java
  backend/src/main/resources/db/migration/V11__modify_school.sql
  backend/src/test/java/com/festago/festival/application/integration/FestivalV1QueryServiceTest.java
  backend/src/test/java/com/festago/festival/domain/FestivalFilterTest.java
  backend/src/test/java/com/festago/festival/presentation/v1/FestivalV1ControllerTest.java
  backend/src/test/java/com/festago/school/repository/SchoolRepositoryTest.java
  backend/src/test/java/com/festago/support/RepositoryBeanConfig.java
  backend/src/test/java/com/festago/support/RepositoryTest.java
Labels: BE, ☢️ DB

#666 [BE] feat: 아티스트 CRUD 기능을 새롭게 추가 (#665)
  backend/src/main/java/com/festago/admin/dto/ArtistCreateRequest.java
  backend/src/main/java/com/festago/admin/dto/ArtistUpdateRequest.java
  backend/src/main/java/com/festago/admin/dto/ArtistV1Response.java
  backend/src/main/java/com/festago/admin/presentation/v1/AdminArtistV1Controller.java
  backend/src/main/java/com/festago/artist/application/ArtistCommandService.java
  backend/src/main/java/com/festago/artist/application/ArtistV1QueryService.java
  backend/src/main/java/com/festago/artist/domain/Artist.java
  backend/src/main/java/com/festago/artist/repository/ArtistRepository.java
  backend/src/main/java/com/festago/common/exception/ErrorCode.java
  backend/src/test/java/com/festago/admin/presentation/v1/AdminArtistV1ControllerTest.java
  backend/src/test/java/com/festago/artist/application/integration/ArtistCommandServiceIntegrationTest.java
  backend/src/test/java/com/festago/artist/application/integration/ArtistV1QueryServiceIntegrationTest.java
Labels: BE, 📬 API

#661 [BE] feat: 새로운 학교 CRUD 기능 추가 (#658)
  backend/src/main/java/com/festago/admin/presentation/AdminController.java
  backend/src/main/java/com/festago/admin/presentation/v1/AdminSchoolV1Controller.java
  backend/src/main/java/com/festago/admin/presentation/v1/dto/SchoolV1CreateRequest.java
  backend/src/main/java/com/festago/admin/presentation/v1/dto/SchoolV1UpdateRequest.java
  backend/src/main/java/com/festago/common/exception/ErrorCode.java
  backend/src/main/java/com/festago/common/querydsl/QueryDslRepositorySupport.java
  backend/src/main/java/com/festago/common/querydsl/SearchCondition.java
  backend/src/main/java/com/festago/festival/application/FestivalSchoolDeleteValidator.java
  backend/src/main/java/com/festago/festival/repository/FestivalRepository.java
  backend/src/main/java/com/festago/school/application/SchoolCommandService.java
  backend/src/main/java/com/festago/school/application/SchoolDeleteService.java
  backend/src/main/java/com/festago/school/application/SchoolDeleteValidator.java
  backend/src/main/java/com/festago/school/application/SchoolV1QueryService.java
  backend/src/main/java/com/festago/school/dto/SchoolCreateCommand.java
  backend/src/main/java/com/festago/school/dto/SchoolCreateRequest.java
  backend/src/main/java/com/festago/school/dto/SchoolResponse.java
  backend/src/main/java/com/festago/school/dto/SchoolUpdateCommand.java
  backend/src/main/java/com/festago/school/dto/SchoolUpdateRequest.java
  backend/src/main/java/com/festago/school/dto/SchoolsResponse.java
  backend/src/main/java/com/festago/school/presentation/SchoolController.java
  backend/src/main/java/com/festago/school/presentation/v1/SchoolV1Controller.java
  backend/src/main/java/com/festago/school/presentation/v1/dto/SchoolV1Response.java
  backend/src/main/java/com/festago/school/repository/SchoolRepository.java
  backend/src/main/java/com/festago/school/repository/SchoolV1QueryDslRepository.java
  backend/src/main/java/com/festago/student/application/StudentSchoolDeleteValidator.java
  backend/src/main/java/com/festago/student/repository/StudentRepository.java
  backend/src/main/resources/application-local.yml
  backend/src/test/java/com/festago/admin/presentation/v1/AdminSchoolV1ControllerTest.java
  backend/src/test/java/com/festago/school/application/integration/SchoolCommandServiceIntegrationTest.java
  backend/src/test/java/com/festago/school/application/integration/SchoolDeleteServiceIntegrationTest.java
  backend/src/test/java/com/festago/school/application/integration/SchoolV1QueryServiceIntegrationTest.java
  backend/src/test/java/com/festago/school/presentation/v1/SchoolV1ControllerTest.java
Labels: BE, 📬 API

#679 [BE] refactor: FestivalV1QueryService에서 FestivalV1QueryDslRepository을 의존하도록 변경 (#678)
  backend/src/main/java/com/festago/festival/application/FestivalV1QueryService.java
  backend/src/main/java/com/festago/festival/repository/FestivalRepositoryCustom.java
  backend/src/main/java/com/festago/festival/repository/FestivalRepositoryCustomImpl.java
  backend/src/main/java/com/festago/festival/repository/OldFestivalRepository.java
  backend/src/test/java/com/festago/support/RepositoryBeanConfig.java
  backend/src/test/java/com/festago/support/RepositoryTest.java
Labels: BE, ⚙️ 리팩터링

#674 [BE] test: 큐컴버 테스트 추가 (#658)
  backend/src/main/java/com/festago/common/exception/ErrorCode.java
  backend/src/main/java/com/festago/school/repository/SchoolRepository.java
  backend/src/test/java/com/festago/acceptance/CucumberClient.java
  backend/src/test/java/com/festago/acceptance/CucumberSpringConfiguration.java
  backend/src/test/java/com/festago/acceptance/EntryPoint.java
  backend/src/test/java/com/festago/acceptance/steps/AdminStepDefinitions.java
  backend/src/test/java/com/festago/acceptance/steps/ExampleStep.java
  backend/src/test/java/com/festago/acceptance/steps/ExampleStep2.java
  backend/src/test/java/com/festago/acceptance/steps/FestivalStepDefinitions.java
  backend/src/test/java/com/festago/acceptance/steps/SchoolStepDefinitions.java
  backend/src/test/java/com/festago/acceptance/steps/TimeStepDefinitions.java
  backend/src/test/java/com/festago/support/ResetMockTestExecutionListener.java
  backend/src/test/resources/features/admin_school.feature
  backend/src/test/resources/features/query_festival.feature
  backend/src/test/resources/features/time.feature
Labels: BE, 🧪 테스트, 🙋‍♀️ 제안

#682 [BE] feat: 인기 축제 목록 구현(#657)
  backend/src/main/java/com/festago/festival/application/PopularFestivalV1QueryService.java
  backend/src/main/java/com/festago/festival/dto/FestivalV1Response.java
  backend/src/main/java/com/festago/festival/dto/PopularFestivalsV1Response.java
  backend/src/main/java/com/festago/festival/dto/SchoolV1Response.java
  backend/src/main/java/com/festago/festival/presentation/v1/PopularFestivalV1Controller.java
  backend/src/main/java/com/festago/festival/repository/FestivalRepositoryCustomImpl.java
  backend/src/main/java/com/festago/festival/repository/FestivalV1QueryDslRepository.java
  backend/src/test/java/com/festago/festival/application/integration/FestivalV1QueryServiceTest.java
  backend/src/test/java/com/festago/festival/application/integration/PopularFestivalV1QueryServiceTest.java
Labels: BE, 📬 API

#675 [BE] feat: Pageable 최대 size 검증하는 AOP 추가 (#658)
  backend/src/main/java/com/festago/common/aop/ValidPageable.java
  backend/src/main/java/com/festago/common/aop/ValidPageableAspect.java
  backend/src/main/java/com/festago/common/exception/ErrorCode.java
  backend/src/main/java/com/festago/school/presentation/v1/SchoolV1Controller.java
  backend/src/test/java/com/festago/common/aop/ValidPageableAspectTest.java
  backend/src/test/java/com/festago/support/CustomWebMvcTest.java
Labels: BE

#681 [BE] refactor: FestivalV1Controller에서 Pageable을 받도록 변경, FestivalV1QueryService 통합 테스트 개선 (#680)
  backend/src/main/java/com/festago/festival/application/FestivalV1QueryService.java
  backend/src/main/java/com/festago/festival/dto/FestivalV1QueryRequest.java
  backend/src/main/java/com/festago/festival/presentation/v1/FestivalV1Controller.java
  backend/src/test/java/com/festago/festival/application/integration/FestivalV1QueryServiceTest.java
  backend/src/test/java/com/festago/festival/presentation/v1/FestivalV1ControllerTest.java
  backend/src/test/java/com/festago/support/TimeInstantProvider.java
Labels: BE, ⚙️ 리팩터링, 🧪 테스트, 📬 API

#686 [BE] feat: FesitvalQueryInfo에 BaseTimeEntity 상속, 유니크 인덱스 추가 (#685)
  backend/src/main/java/com/festago/festival/domain/FestivalQueryInfo.java
  backend/src/main/resources/db/migration/V11__modify_school_and_festival_query_info.sql
  backend/src/main/resources/db/migration/V12__add_festival_startdate_desc_index.sql
Labels: BE, ☢️ DB

#687 [BE] feat: Swagger annotaion 추가 (#683)
  backend/src/main/java/com/festago/festival/presentation/v1/FestivalV1Controller.java
  backend/src/main/java/com/festago/festival/presentation/v1/PopularFestivalV1Controller.java
Labels: BE
